&nbsp;

&nbsp;

# Enhancer-derived lncRNA (down5p)

- enhancer の近傍にある lncRNA を調査する
- [ENCODE-rE2G](https://github.com/EngreitzLab/ENCODE_rE2G) の予測結果に該当する遺伝子を調査する
- これまでの定義では、紐づく fanta.bio の CRE が `ELA` であることを条件としていたが、enhancer から転写されるとされる `ENEMAL` の近傍にある CRE が `PLA` であり、見逃していることに気づいた
- このような背景から、[ENCODE-rE2G](https://github.com/EngreitzLab/ENCODE_rE2G) の予測結果とオーバーラップするデータを、enhancer-derived lncRNA として調査する
- [../05_ENCODE_rE2G/04_encode_re2g_parse_ctrl.ipynb](../05_ENCODE_rE2G/04_encode_re2g_parse_ctrl.ipynb)で処理した結果と、down5p transcript list を `join`する

In [1]:
import datetime
import os
import pathlib

import polars as pl
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
os.environ["POLARS_MAX_THREADS"] = "16"

&nbsp;

&nbsp;

&nbsp;

## 1. e2g dataset (Non stress)

- `TargetGene` の近傍ではない enhancer を標的とする
- `isSelfPromoter` == False でフィルタリングする

In [2]:
e2g_join_filter = pl.scan_parquet(
    "../../out/ENCODE_rE2G/parquet_file/encode_re2g_ctrl_encode_predictions_v261006.parquet"
).filter(
    pl.col("isSelfPromoter") == False
)

display(e2g_join_filter.head(5).collect())

shape: (5, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ENCODE-rE ┆ re2g_data ┆ Model     ┆ sample_in ┆ … ┆ fantabio_ ┆ target_ts ┆ target_cr ┆ target_c │
│ 2G.Score  ┆ set       ┆ ---       ┆ fo        ┆   ┆ enhancer_ ┆ s_info    ┆ e_info    ┆ re_overl │
│ ---       ┆ ---       ┆ cat       ┆ ---       ┆   ┆ cre       ┆ ---       ┆ ---       ┆ ap_info  │
│ f64       ┆ cat       ┆           ┆ struct[4] ┆   ┆ ---       ┆ struct[5] ┆ struct[10 ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ struct[3] ┆           ┆ ]         ┆ struct[2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.824621  ┆ ENCSR045W ┆ DNase-onl ┆ {"GM18507 ┆ … ┆ {960949,9 ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ CT_ENCFF2 ┆ y         ┆ _ENCSR000 ┆   ┆ 61425,-0. ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ 92SIC     ┆           ┆ EJI","GM1 ┆   ┆ 483871}   ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆ 8507","ce ┆   ┆           ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆ ll line", ┆   ┆           ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆ "EFO:0002 ┆   ┆           ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆ 787"}     ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.813417  ┆ ENCSR157D ┆ DNase-onl ┆ {"iPS-NIH ┆ … ┆ {960949,9 ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ JQ_ENCFF9 ┆ y         ┆ i7_ENCSR0 ┆   ┆ 61425,-0. ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ 01GNX     ┆           ┆ 00EKK","i ┆   ┆ 483871}   ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆ PS-NIHi7" ┆   ┆           ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆ ,"cell    ┆   ┆           ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆ line","EF ┆   ┆           ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆ O:0007953 ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆ "}        ┆   ┆           ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.595841  ┆ ENCSR167E ┆ DNase-onl ┆ {"HAP-1_E ┆ … ┆ {960949,9 ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ CG_ENCFF9 ┆ y         ┆ NCSR620QN ┆   ┆ 61425,-0. ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ 47UAT     ┆           ┆ S","HAP-1 ┆   ┆ 483871}   ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆ ","cell   ┆   ┆           ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆ line","EF ┆   ┆           ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆ O:0007598 ┆   ┆           ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆ "}        ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.72318   ┆ ENCSR213X ┆ DNase-onl ┆ {"common_ ┆ … ┆ {960949,9 ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ EF_ENCFF3 ┆ y         ┆ myeloid_p ┆   ┆ 61425,-0. ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ 12ZPL     ┆           ┆ rogenitor ┆   ┆ 483871}   ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆ __CD34-po ┆   ┆           ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆ sitive_EN ┆   ┆           ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆ CSR122VUW ┆   ┆           ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆ ","common ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆ myeloid   ┆   ┆           ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆ progenito ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆ r, CD34-p ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆ ositive", ┆   ┆           ┆           ┆ 864177}   ┆          │
│           ┆           ┆           ┆ "primary  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ cell","CL ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ :0001059" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ }         ┆   ┆           ┆           ┆           ┆          │
│ 0.558777  ┆ ENCSR221F ┆ DNase-onl ┆ {"L1-S8_E ┆ … ┆ {960949,9 ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ YS_ENCFF4 ┆ y         ┆ NCSR314EZ ┆   ┆ 61425,-0. ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ 31CEI     ┆           ┆ Y","L1-S8 ┆   ┆ 483871}   ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆ ","cell   ┆   ┆           ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆ line","EF ┆   ┆           ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆ O:0007599 ┆   ┆           ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆ "}        ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
e2g_join_filter_unique_count = e2g_join_filter.group_by(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "target_cre_id",
    "target_cre_name",
    "target_fantabio_cre_class"
).agg(
    pl.col("re2g_dataset").unique().alias("re2g_dataset"),
    pl.col("re2g_dataset").n_unique().alias("re2g_dataset_count"),
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre").alias("enhancer_cre_overlap_frac_of_fantabio_cre"),
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre").min().alias("enhancer_cre_overlap_frac_of_fantabio_cre_min"),
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre").max().alias("enhancer_cre_overlap_frac_of_fantabio_cre_max"),
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre").mean().alias("enhancer_cre_overlap_frac_of_fantabio_cre_mean"), # 該当するデータセットで同定された enhancer と fantabio の CRE の重複率の平均値

    pl.col("ENCODE-rE2G.Score").alias("ENCODE-rE2G.Score"),
    pl.col("ENCODE-rE2G.Score").min().alias("ENCODE-rE2G.Score_min"),
    pl.col("ENCODE-rE2G.Score").max().alias("ENCODE-rE2G.Score_max"),
    pl.col("ENCODE-rE2G.Score").mean().alias("ENCODE-rE2G.Score_mean"), # 該当するデータセットで同定された enhancer と target promoter の相互作用のスコアの平均値

    # pl.col("ENCODE-rE2G.Score").quantile(0.25).alias("ENCODE-rE2G.Score_q1"),
    # pl.col("ENCODE-rE2G.Score").median().alias("ENCODE-rE2G.Score_median"),
    # pl.col("ENCODE-rE2G.Score").quantile(0.75).alias("ENCODE-rE2G.Score_q3"),
    # pl.col("ENCODE-rE2G.Score").std().alias("ENCODE-rE2G.Score_std"),
).sort(
    by=["re2g_dataset_count"],
    descending=True
).collect(
    engine="streaming"
)

print(f"ENCODE-rE2G enhancer - target region interaction unique pair count (fanta.bio cre level): {e2g_join_filter_unique_count.select(['cre_id', 'target_cre_id']).n_unique()}")
display(e2g_join_filter_unique_count)

ENCODE-rE2G enhancer - target region interaction unique pair count (fanta.bio cre level): 1527047

shape: (1_527_047, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ ENCODE-rE ┆ ENCODE-rE ┆ ENCODE-rE ┆ ENCODE-r │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ 2G.Score  ┆ 2G.Score_ ┆ 2G.Score_ ┆ E2G.Scor │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ min       ┆ max       ┆ e_mean   │
│           ┆           ┆ str       ┆ str       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_1147 ┆ FCHS_1147 ┆ PLA       ┆ FCHS_1147 ┆ … ┆ [0.987368 ┆ 0.633907  ┆ 0.997872  ┆ 0.983285 │
│ 63        ┆ 63        ┆           ┆ 59        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.988221, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.954474] ┆           ┆           ┆          │
│ FCHS_3595 ┆ cp5@GCLC  ┆ PLA       ┆ FCHS_3595 ┆ … ┆ [0.995265 ┆ 0.861669  ┆ 0.99779   ┆ 0.99017  │
│ 20        ┆           ┆           ┆ 18        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.994528, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.993794] ┆           ┆           ┆          │
│ FCHS_1726 ┆ FCHS_1726 ┆ PLA       ┆ FCHS_1726 ┆ … ┆ [0.987729 ┆ 0.329063  ┆ 0.99659   ┆ 0.956294 │
│ 74        ┆ 74        ┆           ┆ 78        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.970177, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.98429]  ┆           ┆           ┆          │
│ FCHS_2673 ┆ FCHS_2673 ┆ PLA       ┆ FCHS_2676 ┆ … ┆ [0.95048, ┆ 0.234617  ┆ 0.980875  ┆ 0.867362 │
│ 9         ┆ 9         ┆           ┆ 5         ┆   ┆ 0.889279, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.74397]  ┆           ┆           ┆          │
│ FCHS_2673 ┆ FCHS_2673 ┆ PLA       ┆ FCHS_2672 ┆ … ┆ [0.97879, ┆ 0.417009  ┆ 0.995714  ┆ 0.958852 │
│ 9         ┆ 9         ┆           ┆ 8         ┆   ┆ 0.944927, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.915287] ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_1714 ┆ FCHS_1714 ┆ ELA       ┆ FCHS_1714 ┆ … ┆ [0.234971 ┆ 0.234971  ┆ 0.234971  ┆ 0.234971 │
│ 45        ┆ 45        ┆           ┆ 77        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_5444 ┆ FCHS_5444 ┆ PLA       ┆ FCHS_2953 ┆ … ┆ [0.721841 ┆ 0.721841  ┆ 0.721841  ┆ 0.721841 │
│ 46        ┆ 46        ┆           ┆ 10        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_2006 ┆ FCHS_2006 ┆ ELA       ┆ FCHS_2020 ┆ … ┆ [0.372632 ┆ 0.372632  ┆ 0.372632  ┆ 0.372632 │
│ 53        ┆ 53        ┆           ┆ 79        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_1087 ┆ FCHS_1087 ┆ PLA       ┆ FCHS_1087 ┆ … ┆ [0.214367 ┆ 0.214367  ┆ 0.214367  ┆ 0.214367 │
│ 47        ┆ 47        ┆           ┆ 08        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_3542 ┆ FCHS_3542 ┆ ELA       ┆ FCHS_5639 ┆ … ┆ [0.552023 ┆ 0.552023  ┆ 0.552023  ┆ 0.552023 │
│ 22        ┆ 22        ┆           ┆ 60        ┆   ┆ ]         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

## 2. down5p transcript list

In [4]:
down5p_fantabio = pl.read_parquet(
    "../../out/fantabio/parquet_file/bottom5p_transcript_fantabio_v261001.parquet"
)

pl.Config.set_tbl_rows(2)
display(down5p_fantabio)

shape: (66_960, 39)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ directional ┆ fantabio_cr ┆ itemRgb    ┆ itemRgb_na │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ity         ┆ e_class     ┆ ---        ┆ me         │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ ---         ┆ str        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆ f64         ┆ str         ┆            ┆ str        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ 0.952663    ┆ ELA         ┆ 255,202,74 ┆ yellow     │
│ 4029.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ -0.368421   ┆ ELA         ┆ 255,202,74 ┆ yellow     │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. Selection of transcript (DOWN-DOWN)

- 上記のセルで読み込んだ enhancer 側の transcript と、target promoter 側の transcript をそれぞれ candidate として選択する
- enhancer 側の transcript と、target promoter 側の transcript はこの時点では同じ数になり、join することによってフィルタリングしていく

In [5]:
# enhancer side transcript entry (enhancer potential transcript - CRE pair)
fantabio_HN2_down5p_enhancer_transcript_candidate = down5p_fantabio.select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "transcript_id",
    "HN2",
    "transcript_type",
    "gene_id",
    "gene_symbol",
    "strand",
    "RNACentral_ID",
    "annotation_remarks",
    "tags"
).unique().rename(
    # assign frag name "e" to enhancer side
    {
        "transcript_id": "e_transcript_id",
        "HN2": "e_HN2",
        "transcript_type": "e_transcript_type",
        "gene_id": "e_gene_id",
        "gene_symbol": "e_gene_symbol",
        "strand": "e_strand",
        "RNACentral_ID": "e_RNACentral_ID",
        "annotation_remarks": "e_annotation_remarks",
        "tags": "e_tags"
    }
)

display(fantabio_HN2_down5p_enhancer_transcript_candidate)

shape: (66_960, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ e_transcr ┆ … ┆ e_strand ┆ e_RNACent ┆ e_annotat ┆ e_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ ipt_id    ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_1682 ┆ cp6@SNHG2 ┆ ELA       ┆ ENST00000 ┆ … ┆ +        ┆ URS0000EF ┆ ["Assembl ┆ ["TAGENE" │
│ 02        ┆ 9         ┆           ┆ 480811.6  ┆   ┆          ┆ 50B5      ┆ ed from   ┆ ]         │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ PacBio    ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ CLS reads ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ - CAGE_Po ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ lyA_HiSeq ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ (GSE93848 ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ )"]       ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_2387 ┆ cp4@LINC0 ┆ ELA       ┆ ENST00000 ┆ … ┆ -        ┆ URS0002A5 ┆ ["CLS3    ┆ ["TAGENE" │
│ 7         ┆ 1138      ┆           ┆ 614292.2  ┆   ┆          ┆ 9B74      ┆ project"] ┆ ]         │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## JOIN (1)

- 標的となる promoter の近傍にある transcript は一旦統合せず、enhancer RNA の potential がある transcript だけを一旦出力する

In [7]:
e2g_join_filter_unique_count_join = e2g_join_filter_unique_count.join(
    fantabio_HN2_down5p_enhancer_transcript_candidate,
    on=["cre_id", "cre_name", "fantabio_cre_class"],
    how="inner"
).filter(
    pl.col("e_transcript_type") == "lncRNA" # lncRNA のみを対象とする
)


display(e2g_join_filter_unique_count_join)

shape: (30_083, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ e_strand ┆ e_RNACent ┆ e_annotat ┆ e_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_3483 ┆ FCHS_3483 ┆ PLA       ┆ FCHS_3483 ┆ … ┆ +        ┆ URS00004E ┆ null      ┆ ["basic"] │
│ 63        ┆ 63        ┆           ┆ 67        ┆   ┆          ┆ 6312      ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_1837 ┆ cp2@LOC10 ┆ PLA       ┆ FCHS_1862 ┆ … ┆ +        ┆ URS000042 ┆ null      ┆ ["basic", │
│ 94        ┆ 5371912   ┆           ┆ 67        ┆   ┆          ┆ 88D2      ┆           ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ", "GENCO │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ DE_Primar │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ y"]       │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [8]:
e2g_join_filter_unique_count_join.write_parquet(
    "../../out/transcript_classification/enhancer_derived_lncRNA/down5p_enhancer_derived_lncRNA_v261010.parquet"
)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Join (2) (DOWN (enhancer proximal lncRNA) - DOWN (target promoter proximal transcript))

- このプロセスで `join`することで得られるのは、enhancer - promoter 両方の近傍にある transcript が発現低下したとみなしている transcript
- 予測された enhancer 側で、`PLA` or `ELA` でもフィルタリングしないことに決定

In [9]:
# target promoter side transcript candidate
fantabio_HN2_down5p_target_transcript_candidate = down5p_fantabio.select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "transcript_id",
    "HN2",
    "transcript_type",
    "gene_id",
    "gene_symbol",
    "strand",
    "RNACentral_ID",
    "annotation_remarks",
    "tags"
).unique().rename(
    # assign frag name "t" to target promoter side
    {
        "cre_id": "target_cre_id",
        "cre_name": "target_cre_name",
        "fantabio_cre_class": "target_fantabio_cre_class",
        "transcript_id": "t_transcript_id",
        "HN2": "t_HN2",
        "transcript_type": "t_transcript_type",
        "gene_id": "t_gene_id",
        "gene_symbol": "t_gene_symbol",
        "strand": "t_strand",
        "RNACentral_ID": "t_RNACentral_ID",
        "annotation_remarks": "t_annotation_remarks",
        "tags": "t_tags"
    }
)

display(fantabio_HN2_down5p_target_transcript_candidate)

shape: (66_960, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ target_cr ┆ target_cr ┆ target_fa ┆ t_transcr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ e_id      ┆ e_name    ┆ ntabio_cr ┆ ipt_id    ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ ---       ┆ ---       ┆ e_class   ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆ str       ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_1669 ┆ cp8@PFAS  ┆ PLA       ┆ ENST00000 ┆ … ┆ -        ┆ null      ┆ ["DanaFar ┆ ["basic", │
│ 29        ┆           ┆           ┆ 868169.1  ┆   ┆          ┆           ┆ ber"]     ┆ "GENCODE_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ Primary", │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "TAGENE"] │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_3483 ┆ cp6@PRP4K ┆ ELA       ┆ ENST00000 ┆ … ┆ +        ┆ null      ┆ ["LRGASP" ┆ ["basic", │
│ 68        ┆           ┆           ┆ 935173.1  ┆   ┆          ┆           ┆ ]         ┆ "GENCODE_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ Primary", │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ … "appris │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ _alternat │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ive_2"]   │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [10]:
e2g_join_filter_unique_count_join_down_down = e2g_join_filter_unique_count.join(
    fantabio_HN2_down5p_enhancer_transcript_candidate,
    on=["cre_id", "cre_name", "fantabio_cre_class"],
    how="inner"
).join(
    fantabio_HN2_down5p_target_transcript_candidate,
    on=["target_cre_id", "target_cre_name", "target_fantabio_cre_class"],
    how="inner"
).sort(
    by=["e_HN2", "t_HN2", "re2g_dataset_count"],
    descending=[True, True, True]
).filter(
    pl.col("e_transcript_type") == "lncRNA" # lncRNA のみを対象とする
)

e2g_join_filter_unique_count_join_down_down.write_parquet(
    "../../out/transcript_classification/enhancer_derived_lncRNA/down5p_enhancer_derived_lncRNA_v261010_DOWN_DOWN.parquet"
)

display(e2g_join_filter_unique_count_join_down_down)

shape: (27_033, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_2830 ┆ cp7@SLC25 ┆ PLA       ┆ FCHS_2830 ┆ … ┆ -        ┆ URS0002A5 ┆ ["CLS3    ┆ ["TAGENE" │
│ 74        ┆ A38       ┆           ┆ 71        ┆   ┆          ┆ 1F68      ┆ project"] ┆ ]         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_1730 ┆ cp2@SMARC ┆ ELA       ┆ FCHS_1730 ┆ … ┆ +        ┆ URS0002A5 ┆ ["CLS3    ┆ ["basic", │
│ 68        ┆ E1        ┆           ┆ 69        ┆   ┆          ┆ 4E6E      ┆ project", ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ "Assemble ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ d from    ┆ ", …      │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ PacBio    ┆ "TAGENE"] │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ CLS3      ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ reads"]   ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘