&nbsp;

&nbsp;

# Enhancer-derived lncRNA (up5p)

- enhancer の近傍にある lncRNA を調査する
- [ENCODE-rE2G](https://github.com/EngreitzLab/ENCODE_rE2G) の予測結果に該当する遺伝子を調査する
- これまでの定義では、紐づく fanta.bio の CRE が `ELA` であることを条件としていたが、enhancer から転写されるとされる `ENEMAL` の近傍にある CRE が `PLA` であり、見逃していることに気づいた
- このような背景から、[ENCODE-rE2G](https://github.com/EngreitzLab/ENCODE_rE2G) の予測結果とオーバーラップするデータを、enhancer-derived lncRNA として調査する
- [../05_ENCODE_rE2G/encode_re2g_parse.ipynb](../05_ENCODE_rE2G/encode_re2g_parse.ipynb)で処理した結果と、up5p transcript list を `join`する

In [1]:
import datetime
import os
import pathlib

import polars as pl
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
os.environ["POLARS_MAX_THREADS"] = "16"

&nbsp;

&nbsp;

&nbsp;

## 1. e2g dataset (Heat stress)

- `TargetGene` の近傍ではない enhancer を標的とする
- `isSelfPromoter` == False でフィルタリングする

In [2]:
e2g_join_filter = pl.read_parquet(
    "../../out/ENCODE_rE2G/parquet_file/encode_re2g_hs_join_v261003.parquet"
).filter(
    pl.col("isSelfPromoter") == False
)

display(e2g_join_filter)

shape: (902_211, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ENCODE-rE ┆ re2g_data ┆ cre_id    ┆ cre_name  ┆ … ┆ re2g_feat ┆ target_ts ┆ target_cr ┆ target_c │
│ 2G.Score  ┆ set       ┆ ---       ┆ ---       ┆   ┆ ures      ┆ s_info    ┆ e_info    ┆ re_overl │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ap_info  │
│ f64       ┆ str       ┆           ┆           ┆   ┆ struct[8] ┆ struct[5] ┆ struct[10 ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ]         ┆ struct[2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.342709  ┆ GSE154744 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33082177 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {390,0.7 │
│           ┆ _K562_42C ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3081927,3 ┆ 3081878,3 ┆ 8}       │
│           ┆ _25min    ┆           ┆           ┆   ┆ 00142920" ┆ 3082427,0 ┆ 3082317,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.383964 ┆ ,"+"}     ┆ ,".",3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 1878,3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 44833,2,1 ┆           ┆ 2179,"255 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,220.5978 ┆           ┆ ,202,74", ┆          │
│           ┆           ┆           ┆           ┆   ┆ 81}       ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nality:1| ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ class:ELA ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1.0}    ┆          │
│ 0.320048  ┆ GSE154744 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33082177 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {390,0.7 │
│           ┆ _K562_42C ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3081927,3 ┆ 3081878,3 ┆ 8}       │
│           ┆ _60min    ┆           ┆           ┆   ┆ 00142920" ┆ 3082427,0 ┆ 3082317,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.402521 ┆ ,"+"}     ┆ ,".",3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 1878,3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 44762,4,1 ┆           ┆ 2179,"255 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,253.0904 ┆           ┆ ,202,74", ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nality:1| ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ class:ELA ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1.0}    ┆          │
│ 0.312414  ┆ GSE267931 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33082177 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {390,0.7 │
│           ┆ _HUVEC_39 ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3081927,3 ┆ 3081878,3 ┆ 8}       │
│           ┆ C_120min  ┆           ┆           ┆   ┆ 00142920" ┆ 3082427,0 ┆ 3082317,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.466515 ┆ ,"+"}     ┆ ,".",3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 1878,3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 44839,4,1 ┆           ┆ 2179,"255 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,506.0419 ┆           ┆ ,202,74", ┆          │
│           ┆           ┆           ┆           ┆   ┆ 96}       ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nality:1| ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ class:ELA ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1.0}    ┆          │
│ 0.194134  ┆ GSE267931 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33182070 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {461,0.9 │
│           ┆ _HUVEC_39 ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3181820,3 ┆ 3181859,3 ┆ 22}      │
│           ┆ C_120min  ┆           ┆           ┆   ┆ 00116525" ┆ 3182320,0 ┆ 3182582,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.524194 ┆ ,"-"}     ┆ ,".",3318 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 2047,3318 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 13442,13, ┆           ┆ 2188,"0,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 1,506.041 ┆           ┆ ,204","di ┆          │
│           ┆           ┆           ┆           ┆   ┆ 996}      ┆           ┆ rectional ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ity:-0.99 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9247|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .999247}  ┆          │
│ 0.291194  ┆ GSE173536 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {85836540 ┆ {"chr12", ┆ {"chr12", ┆ {442,0.8 │
│           ┆ _lymphbla ┆ 26        ┆ 26        ┆   ┆ ,"ENSG000 ┆ 85836290, ┆ 85836188, ┆ 84}      │
│           ┆ stoid_d21 ┆           ┆           ┆   ┆ 00198774" ┆ 85836790, ┆ 85836732, ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ ,0.357834 ┆ 0,"-"}    ┆ 0,".",858 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 36213,858 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0446,9,1, ┆           ┆ 36732,"0, ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.0}      ┆           ┆ 0,255","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:-1|c ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lass:PLA" ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ,-1.0}    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.644669  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {85036320 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 85036070, ┆ 85036236, ┆ 24}      │
│           ┆ 60min     ┆           ┆           ┆   ┆ 00133640" ┆ 85036570, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.470943 ┆ 0,"+"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 36875,2,2 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.311435  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {84912829 ┆ {"chr12", ┆ {"chr12", ┆ {500,1.0 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 84912579, ┆ 84912565, ┆ }        │
│           ┆ 120min    ┆           ┆           ┆   ┆ 00072041" ┆ 84913079, ┆ 84913337, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.486403 ┆ 0,"-"}    ┆ 0,".",849 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 12757,849 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 14404,3,1 ┆           ┆ 12903,"0, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 0,204","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:-0.9 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9533|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .99533}   ┆          │
│ 0.291244  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {84912829 ┆ {"chr12", ┆ {"chr12", ┆ {500,1.0 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 84912579, ┆ 84912565, ┆ }        │
│           ┆ 60min     ┆           ┆           ┆   ┆ 00072041" ┆ 84913079, ┆ 84913337, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.581099 ┆ 0,"-"}    ┆ 0,".",849 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 12757,849 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 14404,6,1 ┆           ┆ 12903,"0, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 0,204","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:-0.9 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9533|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .99533}   ┆          │
│ 0.634666  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ 120min    ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.410312 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 36906,1,2 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.648746  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ 60min     ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.464773 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 36903,2,2 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
e2g_join_filter_unique_count = e2g_join_filter.group_by(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "target_cre_id",
    "target_cre_name",
    "target_fantabio_cre_class"
).agg(
    pl.col("re2g_dataset").unique().alias("re2g_dataset"),
    pl.col("re2g_dataset").n_unique().alias("re2g_dataset_count"),
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre").alias("enhancer_cre_overlap_frac_of_fantabio_cre"),
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre").min().alias("enhancer_cre_overlap_frac_of_fantabio_cre_min"),
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre").max().alias("enhancer_cre_overlap_frac_of_fantabio_cre_max"),
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre").mean().alias("enhancer_cre_overlap_frac_of_fantabio_cre_mean"), # 該当するデータセットで同定された enhancer と fantabio の CRE の重複率の平均値

    pl.col("ENCODE-rE2G.Score").alias("ENCODE-rE2G.Score"),
    pl.col("ENCODE-rE2G.Score").min().alias("ENCODE-rE2G.Score_min"),
    pl.col("ENCODE-rE2G.Score").max().alias("ENCODE-rE2G.Score_max"),
    pl.col("ENCODE-rE2G.Score").mean().alias("ENCODE-rE2G.Score_mean"), # 該当するデータセットで同定された enhancer と target promoter の相互作用のスコアの平均値

    # pl.col("ENCODE-rE2G.Score").quantile(0.25).alias("ENCODE-rE2G.Score_q1"),
    # pl.col("ENCODE-rE2G.Score").median().alias("ENCODE-rE2G.Score_median"),
    # pl.col("ENCODE-rE2G.Score").quantile(0.75).alias("ENCODE-rE2G.Score_q3"),
    # pl.col("ENCODE-rE2G.Score").std().alias("ENCODE-rE2G.Score_std"),
).sort(
    by=["re2g_dataset_count"],
    descending=True
)

print(f"ENCODE-rE2G enhancer - target region interaction unique pair count (fanta.bio cre level): {e2g_join_filter_unique_count.select(['cre_id', 'target_cre_id']).n_unique()}")
display(e2g_join_filter_unique_count)

ENCODE-rE2G enhancer - target region interaction unique pair count (fanta.bio cre level): 368398

shape: (368_398, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ ENCODE-rE ┆ ENCODE-rE ┆ ENCODE-rE ┆ ENCODE-r │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ 2G.Score  ┆ 2G.Score_ ┆ 2G.Score_ ┆ E2G.Scor │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ min       ┆ max       ┆ e_mean   │
│           ┆           ┆ str       ┆ str       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_2020 ┆ FCHS_2020 ┆ ELA       ┆ FCHS_2020 ┆ … ┆ [0.932402 ┆ 0.441195  ┆ 0.988182  ┆ 0.862936 │
│ 36        ┆ 36        ┆           ┆ 35        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.896114, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.685487] ┆           ┆           ┆          │
│ FCHS_5000 ┆ FCHS_5000 ┆ ELA       ┆ FCHS_1626 ┆ … ┆ [0.610364 ┆ 0.267399  ┆ 0.905857  ┆ 0.748022 │
│ 39        ┆ 39        ┆           ┆ 86        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.807375, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.867379] ┆           ┆           ┆          │
│ FCHS_1184 ┆ FCHS_1184 ┆ PLA       ┆ FCHS_1185 ┆ … ┆ [0.914299 ┆ 0.352148  ┆ 0.920479  ┆ 0.674624 │
│ 81        ┆ 81        ┆           ┆ 49        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.920479, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.850441] ┆           ┆           ┆          │
│ FCHS_3559 ┆ FCHS_3559 ┆ PLA       ┆ FCHS_3559 ┆ … ┆ [0.181076 ┆ 0.181076  ┆ 0.835387  ┆ 0.568878 │
│ 57        ┆ 57        ┆           ┆ 32        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.476446, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.225056] ┆           ┆           ┆          │
│ FCHS_3936 ┆ cp1@RNY3  ┆ ELA       ┆ FCHS_3936 ┆ … ┆ [0.931632 ┆ 0.771432  ┆ 0.969518  ┆ 0.897168 │
│ 92        ┆           ┆           ┆ 95        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.891956, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.906371] ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_1976 ┆ FCHS_1976 ┆ ELA       ┆ FCHS_1976 ┆ … ┆ [0.376168 ┆ 0.376168  ┆ 0.376168  ┆ 0.376168 │
│ 08        ┆ 08        ┆           ┆ 11        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_1970 ┆ FCHS_1970 ┆ ELA       ┆ FCHS_1963 ┆ … ┆ [0.328062 ┆ 0.328062  ┆ 0.328062  ┆ 0.328062 │
│ 52        ┆ 52        ┆           ┆ 17        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_2888 ┆ cp19@FOXP ┆ PLA       ┆ FCHS_2892 ┆ … ┆ [0.538279 ┆ 0.538279  ┆ 0.538279  ┆ 0.538279 │
│ 50        ┆ 1         ┆           ┆ 70        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_1163 ┆ FCHS_1163 ┆ ELA       ┆ FCHS_1166 ┆ … ┆ [0.350203 ┆ 0.350203  ┆ 0.350203  ┆ 0.350203 │
│ 80        ┆ 80        ┆           ┆ 20        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_3854 ┆ FCHS_3854 ┆ ELA       ┆ FCHS_3854 ┆ … ┆ [0.273147 ┆ 0.273147  ┆ 0.273147  ┆ 0.273147 │
│ 22        ┆ 22        ┆           ┆ 30        ┆   ┆ ]         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

## 2. up5p transcript list

In [4]:
up5p_fantabio = pl.read_parquet(
    "../../out/fantabio/parquet_file/up5p_transcript_fantabio_v261001.parquet"
)

pl.Config.set_tbl_rows(2)
display(up5p_fantabio)

shape: (63_099, 39)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ directional ┆ fantabio_cr ┆ itemRgb    ┆ itemRgb_na │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ity         ┆ e_class     ┆ ---        ┆ me         │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ ---         ┆ str        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆ f64         ┆ str         ┆            ┆ str        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ 0.982111    ┆ PLA         ┆ 204,0,0    ┆ red        │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ 0.5         ┆ ELA         ┆ 255,202,74 ┆ yellow     │
│ 4581.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. Selection of transcript (UP-UP)

- 上記のセルで読み込んだ `up5p_fantabio` データフレームから、enhancer 側の transcript と、target promoter 側の transcript をそれぞれ candidate として選択する
- enhancer 側の transcript と、target promoter 側の transcript はこの時点では同じ数になり、join することによってフィルタリングしていく

In [5]:
# enhancer side transcript entry (enhancer potential transcript - CRE pair)
fantabio_HN2_up5p_enhancer_transcript_candidate = up5p_fantabio.select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "transcript_id",
    "HN2",
    "transcript_type",
    "gene_id",
    "gene_symbol",
    "strand",
    "RNACentral_ID",
    "annotation_remarks",
    "tags"
).unique().rename(
    # assign frag name "e" to enhancer side
    {
        "transcript_id": "e_transcript_id",
        "HN2": "e_HN2",
        "transcript_type": "e_transcript_type",
        "gene_id": "e_gene_id",
        "gene_symbol": "e_gene_symbol",
        "strand": "e_strand",
        "RNACentral_ID": "e_RNACentral_ID",
        "annotation_remarks": "e_annotation_remarks",
        "tags": "e_tags"
    }
)

display(fantabio_HN2_up5p_enhancer_transcript_candidate)

shape: (63_099, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ e_transcr ┆ … ┆ e_strand ┆ e_RNACent ┆ e_annotat ┆ e_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ ipt_id    ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_2021 ┆ cp4@RAB8A ┆ PLA       ┆ ENST00000 ┆ … ┆ +        ┆ null      ┆ ["DanaFar ┆ ["basic", │
│ 91        ┆           ┆           ┆ 860860.1  ┆   ┆          ┆           ┆ ber"]     ┆ "TAGENE"] │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_3560 ┆ cp3@SRPK1 ┆ PLA       ┆ ENST00000 ┆ … ┆ -        ┆ null      ┆ null      ┆ ["mRNA_en │
│ 03        ┆           ┆           ┆ 510290.5  ┆   ┆          ┆           ┆           ┆ d_NF",    │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "cds_end_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ NF"]      │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## JOIN (1)

- 標的となる promoter の近傍にある transcript は一旦統合せず、enhancer RNA の potential がある transcript だけを一旦出力する

In [6]:
e2g_join_filter_unique_count_join = e2g_join_filter_unique_count.join(
    fantabio_HN2_up5p_enhancer_transcript_candidate,
    on=["cre_id", "cre_name", "fantabio_cre_class"],
    how="inner"
).filter(
    pl.col("e_transcript_type") == "lncRNA" # lncRNA のみを対象とする
)


display(e2g_join_filter_unique_count_join)

shape: (12_630, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ e_strand ┆ e_RNACent ┆ e_annotat ┆ e_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_9445 ┆ FCHS_9445 ┆ PLA       ┆ FCHS_9449 ┆ … ┆ -        ┆ URS0002A2 ┆ ["CLS3    ┆ ["basic", │
│ 1         ┆ 1         ┆           ┆ 9         ┆   ┆          ┆ 36EE      ┆ project"] ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ", …      │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "TAGENE"] │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_2656 ┆ cp2@LOC10 ┆ ELA       ┆ FCHS_2658 ┆ … ┆ +        ┆ URS0002A5 ┆ ["CLS3    ┆ ["basic", │
│ 30        ┆ 5369306   ┆           ┆ 30        ┆   ┆          ┆ 7053      ┆ project"] ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ", …      │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "TAGENE"] │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [7]:
e2g_join_filter_unique_count_join.write_parquet(
    "../../out/transcript_classification/enhancer_derived_lncRNA/up5p_enhancer_derived_lncRNA_v261010.parquet"
)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Join (2) (UP (enhancer proximal lncRNA) - UP (target promoter proximal transcript))

- このプロセスで `join`することで得られるのは、enhancer - promoter 両方の近傍にある transcript が 発現上昇したとみなしている transcirpt
- 予測された enhancer 側 で、`PLA` or `ELA` でも フィルタリングしないことに決定

In [8]:
# target promoter side transcript candidate
fantabio_HN2_up5p_target_transcript_candidate = up5p_fantabio.select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "transcript_id",
    "HN2",
    "transcript_type",
    "gene_id",
    "gene_symbol",
    "strand",
    "RNACentral_ID",
    "annotation_remarks",
    "tags"
).unique().rename(
    # assign frag name "t" to target promoter side
    {
        "cre_id": "target_cre_id",
        "cre_name": "target_cre_name",
        "fantabio_cre_class": "target_fantabio_cre_class",
        "transcript_id": "t_transcript_id",
        "HN2": "t_HN2",
        "transcript_type": "t_transcript_type",
        "gene_id": "t_gene_id",
        "gene_symbol": "t_gene_symbol",
        "strand": "t_strand",
        "RNACentral_ID": "t_RNACentral_ID",
        "annotation_remarks": "t_annotation_remarks",
        "tags": "t_tags"
    }
)

display(fantabio_HN2_up5p_target_transcript_candidate)

shape: (63_099, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ target_cr ┆ target_cr ┆ target_fa ┆ t_transcr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ e_id      ┆ e_name    ┆ ntabio_cr ┆ ipt_id    ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ ---       ┆ ---       ┆ e_class   ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆ str       ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_1124 ┆ cp3@TPT1, ┆ PLA       ┆ ENST00000 ┆ … ┆ +        ┆ null      ┆ ["Assembl ┆ ["TAGENE" │
│ 60        ┆ cp3@TPT1- ┆           ┆ 662212.1  ┆   ┆          ┆           ┆ ed from   ┆ ]         │
│           ┆ AS1       ┆           ┆           ┆   ┆          ┆           ┆ SLRseq    ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ reads (SR ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ P049776)" ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ ]         ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_1239 ┆ cp1@JKAMP ┆ ELA       ┆ ENST00000 ┆ … ┆ +        ┆ null      ┆ null      ┆ []        │
│ 76        ┆           ┆           ┆ 554754.5  ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [9]:
e2g_join_filter_unique_count_join = e2g_join_filter_unique_count.join(
    fantabio_HN2_up5p_enhancer_transcript_candidate,
    on=["cre_id", "cre_name", "fantabio_cre_class"],
    how="inner"
).join(
    fantabio_HN2_up5p_target_transcript_candidate,
    on=["target_cre_id", "target_cre_name", "target_fantabio_cre_class"],
    how="inner"
).sort(
    by=["e_HN2", "t_HN2", "re2g_dataset_count"],
    descending=[True, True, True]
).filter(
    pl.col("e_transcript_type") == "lncRNA" # lncRNA のみを対象とする
)

e2g_join_filter_unique_count_join.write_parquet(
    "../../out/transcript_classification/enhancer_derived_lncRNA/up5p_enhancer_derived_lncRNA_v261010_UP_UP.parquet"
)

display(e2g_join_filter_unique_count_join)

shape: (12_993, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_2812 ┆ cp1@HSPA7 ┆ ELA       ┆ FCHS_2829 ┆ … ┆ +        ┆ null      ┆ ["DanaFar ┆ ["basic", │
│ 9         ┆           ┆           ┆ 9         ┆   ┆          ┆           ┆ ber"]     ┆ "TAGENE", │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "CCDS"]   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_2313 ┆ FCHS_2313 ┆ ELA       ┆ FCHS_2313 ┆ … ┆ +        ┆ null      ┆ ["ENCODE_ ┆ ["basic", │
│ 44        ┆ 44        ┆           ┆ 21        ┆   ┆          ┆           ┆ tissue"]  ┆ "TAGENE"] │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [10]:
# check (ENEMAL)
ENST00000701343_2 = e2g_join_filter_unique_count_join.filter(
    pl.col("e_gene_symbol") == "ENEMAL"
)

pl.Config.set_tbl_rows(2)
display(ENST00000701343_2)

shape: (40, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_7364 ┆ cp3@ENEMA ┆ ELA       ┆ FCHS_7385 ┆ … ┆ +        ┆ null      ┆ ["ENCODE_ ┆ ["basic", │
│ 8         ┆ L         ┆           ┆ 6         ┆   ┆          ┆           ┆ tissue"]  ┆ "GENCODE_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ Primary", │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "TAGENE"] │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_7365 ┆ cp6@ENEMA ┆ ELA       ┆ FCHS_4709 ┆ … ┆ -        ┆ URS0002A4 ┆ ["NR_1454 ┆ ["basic", │
│ 1         ┆ L         ┆           ┆ 91        ┆   ┆          ┆ D8F6      ┆ 59.1 is   ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ the basis ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ for this  ┆ ", …      │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ transcrip ┆ "TAGENE"] │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ t. Built  ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ in        ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ response  ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ to a      ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ GENCODE   ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ ticket as ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ RefSeq    ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ have this ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ gene anno ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ tated.    ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ Discovere ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ d as RNA  ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ using cop ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ recipitat ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ ion and   ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ then char ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ acterised ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ using     ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ strand    ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ sp…       ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 5. Join (UP (enhancer proximal lncRNA) - DOWN (target promoter proximal transcript))

- `silencer` 的な動きをしている enhancer-derived lncRNA も探索する！

In [11]:
down5p_fantabio = pl.read_parquet(
    "../../out/fantabio/parquet_file/bottom5p_transcript_fantabio_v261001.parquet"
)

display(down5p_fantabio)

shape: (66_960, 39)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ directional ┆ fantabio_cr ┆ itemRgb    ┆ itemRgb_na │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ity         ┆ e_class     ┆ ---        ┆ me         │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ ---         ┆ str        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆ f64         ┆ str         ┆            ┆ str        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ 0.952663    ┆ ELA         ┆ 255,202,74 ┆ yellow     │
│ 4029.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ -0.368421   ┆ ELA         ┆ 255,202,74 ┆ yellow     │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [12]:
# target promoter side transcript candidate
fantabio_HN2_down5p_target_transcript_candidate = down5p_fantabio.select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "transcript_id",
    "HN2",
    "transcript_type",
    "gene_id",
    "gene_symbol",
    "strand",
    "RNACentral_ID",
    "annotation_remarks",
    "tags"
).unique().rename(
    # assign frag name "t" to target promoter side
    {
        "cre_id": "target_cre_id",
        "cre_name": "target_cre_name",
        "fantabio_cre_class": "target_fantabio_cre_class",
        "transcript_id": "t_transcript_id",
        "HN2": "t_HN2",
        "transcript_type": "t_transcript_type",
        "gene_id": "t_gene_id",
        "gene_symbol": "t_gene_symbol",
        "strand": "t_strand",
        "RNACentral_ID": "t_RNACentral_ID",
        "annotation_remarks": "t_annotation_remarks",
        "tags": "t_tags"
    }
)

display(fantabio_HN2_down5p_target_transcript_candidate)

shape: (66_960, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ target_cr ┆ target_cr ┆ target_fa ┆ t_transcr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ e_id      ┆ e_name    ┆ ntabio_cr ┆ ipt_id    ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ ---       ┆ ---       ┆ e_class   ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆ str       ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_2002 ┆ cp3@SASS6 ┆ ELA       ┆ ENST00000 ┆ … ┆ +        ┆ null      ┆ null      ┆ []        │
│ 9         ┆           ┆           ┆ 482437.5  ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_3803 ┆ cp1@UBE2D ┆ PLA       ┆ ENST00000 ┆ … ┆ -        ┆ null      ┆ ["alterna ┆ ["mRNA_en │
│ 03        ┆ 4,cp12@UR ┆           ┆ 426198.5  ┆   ┆          ┆           ┆ tive 5'   ┆ d_NF",    │
│           ┆ GCP       ┆           ┆           ┆   ┆          ┆           ┆ UTR"]     ┆ "cds_end_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ NF", "alt │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ernative_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ 5_UTR"]   │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [13]:
e2g_join_filter_unique_count_join_up_down = e2g_join_filter_unique_count.join(
    fantabio_HN2_up5p_enhancer_transcript_candidate,
    on=["cre_id", "cre_name", "fantabio_cre_class"],
    how="inner"
).join(
    fantabio_HN2_down5p_target_transcript_candidate,
    on=["target_cre_id", "target_cre_name", "target_fantabio_cre_class"],
    how="inner"
).sort(
    by=["e_HN2", "t_HN2", "re2g_dataset_count"],
    descending=[True, True, True]
).filter(
    pl.col("e_transcript_type") == "lncRNA" # lncRNA のみを対象とする
)

e2g_join_filter_unique_count_join_up_down.write_parquet(
    "../../out/transcript_classification/enhancer_derived_lncRNA/up5p_enhancer_derived_lncRNA_v261010_UP_DOWN.parquet"
)

display(e2g_join_filter_unique_count_join_up_down)

shape: (10_194, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_2812 ┆ cp1@HSPA7 ┆ ELA       ┆ FCHS_2829 ┆ … ┆ +        ┆ null      ┆ ["DanaFar ┆ ["basic", │
│ 9         ┆           ┆           ┆ 9         ┆   ┆          ┆           ┆ ber"]     ┆ "TAGENE", │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "appris_a │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ lternativ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ e_1"]     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_1584 ┆ FCHS_1584 ┆ ELA       ┆ FCHS_1585 ┆ … ┆ -        ┆ null      ┆ ["MANE_se ┆ ["basic", │
│ 94        ┆ 94        ┆           ┆ 18        ┆   ┆          ┆           ┆ lect"]    ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ", …      │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "CCDS"]   │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘