In [1]:
import os
import datetime
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import matplotlib.pyplot as plt
from upsetplot import UpSet, from_contents
from IPython.display import display


os.environ["POLARS_MAX_THREADS"] = "16"

&nbsp;

&nbsp;

## up5p Diff Analysis Result

In [3]:
up5p_fantabio_diff_analysis_result = pl.read_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/transcript_cre/fantabio_HN2_up5p_v261002_diff_analysis_atac.parquet"
)

pl.Config.set_tbl_rows(2)
display(up5p_fantabio_diff_analysis_result)

shape: (4_423, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ [0.000001,  ┆ ["GSE101731 ┆ 3          ┆ ["GSE10173 │
│ 9758.6      ┆     ┆       ┆            ┆   ┆ 2.0457e-12, ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆ 0.00048…    ┆ 4C_120mi…   ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000067 ┆ 102 ┆ 58    ┆ 246        ┆ … ┆ [0.008726]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 8039.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120mi…   ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

## diff analysis + protein-coding transcripts

In [6]:
up5p_fantabio_diff_analysis_result_pc = up5p_fantabio_diff_analysis_result.filter(
    pl.col("transcript_type") == "protein_coding"
).with_columns(
    # Drop the Ensembl version suffix, e.g. ENST00000791171.1 -> ENST00000791171
    pl.col("transcript_id").str.replace(r"\.\d+$", "")
)

up5p_fantabio_diff_analysis_result_pc.select(
    "transcript_id"
).unique().write_csv(
    "../../out/enrichment_analysis/query/up5p_fantabio_diff_analysis_atac_result_pc_transcript_list.txt",
    separator="\t",
    include_header=False
)

display(up5p_fantabio_diff_analysis_result_pc)

shape: (3_018, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ [0.000001,  ┆ ["GSE101731 ┆ 3          ┆ ["GSE10173 │
│ 9758        ┆     ┆       ┆            ┆   ┆ 2.0457e-12, ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆ 0.00048…    ┆ 4C_120mi…   ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000089 ┆ 91  ┆ 47    ┆ 268        ┆ … ┆ [0.000075]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 2645        ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120mi…   ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

## Down5p + Diff-analysis

In [7]:
down5p_fantabio_diff_analysis_result = pl.read_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/transcript_cre/fantabio_HN2_bottom5p_v261002_diff_analysis_atac.parquet"
)

display(down5p_fantabio_diff_analysis_result)

shape: (1_925, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000048 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ [0.00734]   ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 9344.5      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120mi…   ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000046 ┆ 15  ┆ 233   ┆ 158        ┆ … ┆ [0.00744,   ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 0307.1      ┆     ┆       ┆            ┆   ┆ 0.0073]     ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120mi…   ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [9]:
down5p_fantabio_diff_analysis_result_pc = down5p_fantabio_diff_analysis_result.filter(
    pl.col("transcript_type") == "protein_coding"
).with_columns(
    # Drop the Ensembl version suffix, e.g. ENST00000791171.1 -> ENST00000791171
    pl.col("transcript_id").str.replace(r"\.\d+$", "")
)

down5p_fantabio_diff_analysis_result_pc.select(
    "transcript_id"
).unique().write_csv(
    "../../out/enrichment_analysis/query/down5p_fantabio_diff_analysis_atac_result_pc_transcript_list.txt",
    separator="\t",
    include_header=False
)


display(down5p_fantabio_diff_analysis_result_pc)

shape: (1_059, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000087 ┆ 77  ┆ 125   ┆ 204        ┆ … ┆ [0.008142]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 0205        ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120mi…   ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000052 ┆ 12  ┆ 200   ┆ 194        ┆ … ┆ [0.000033,  ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 7436        ┆     ┆       ┆            ┆   ┆ 0.000074]   ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120mi…   ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘