&nbsp;

# HN-score Transcript - fanta.bio CRE Intergration (Experimental)

- 全ての転写産物の結果を `join`できるか試してみる

In [2]:
import os
import datetime
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import matplotlib.pyplot as plt
from upsetplot import UpSet, from_contents
from IPython.display import display


os.environ["POLARS_MAX_THREADS"] = "16"

In [3]:
VERSION = datetime.datetime.now().strftime("%y%m")
Execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {Execute_date}")

Execute Date: 261001

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1. HN-score Transcript List

In [4]:
HNscore_transcript_all = pl.read_parquet(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/annotation/HNscore_gencode_human_261001_HN2_transcript_all_gencode_annotation.parquet"
)

display(HNscore_transcript_all)

shape: (517_038, 22)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ polyA_featu ┆ gene_source ┆ annotation ┆ annotation │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ res         ┆ ---         ┆ _remarks   ┆ _remark_co │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ str         ┆ ---        ┆ unt        │
│ str         ┆     ┆       ┆            ┆   ┆ list[str]   ┆             ┆ list[str]  ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ u32        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ null        ┆ ensembl_hav ┆ ["MANE_sel ┆ 1          │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ ect"]      ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆            ┆            │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ ["alternat ┆ 3          │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ e"]         ┆ ana_gene_ho ┆ ive 5'     ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆ UTR",      ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "inferr…   ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆            ┆            │
│ ENST0000054 ┆ 328 ┆ 9     ┆ 69         ┆ … ┆ null        ┆ ensembl_hav ┆ ["non      ┆ 1          │
│ 0260.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ canonical  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆ TEC"]      ┆            │
│ ENST0000067 ┆ 324 ┆ 7     ┆ 75         ┆ … ┆ null        ┆ ensembl_hav ┆ ["intropol ┆ 4          │
│ 6231.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ is_filtere ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆ d",        ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "Snapt…    ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000049 ┆ 15  ┆ 266   ┆ 125        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 7231.7      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆            ┆            │
│ ENST0000049 ┆ 12  ┆ 265   ┆ 129        ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0762.5      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆ mo_sapie…   ┆            ┆            │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ null       ┆ 0          │
│ 6094.5      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆ mo_sapie…   ┆            ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆            ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ null        ┆ ensembl_hav ┆ ["RNA-Seq  ┆ 1          │
│ 0179.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆ partial"]  ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. `fanta.bio` resource (BED file)

- directionality, fanta.bioでのアノテーション (PLA,ELA)からの情報を得るためにタブ区切りとして読み込む

In [5]:
# https://data.fanta.bio/cre/v1.2.1/00README_v1.2.1.txt
fantabio_bed = pl.read_csv(
    "../../Data/Database/fantabio/human-CREv1.2.1.hg38.cre-peaks.bed",
    separator="\t",
    n_threads=16,
    has_header=False,
    new_columns=[
        "cre_chrom",
        "cre_chrom_start",
        "cre_chrom_end",
        "cre_id",
        "score",
        "strand",
        "thickStart",
        "thickEnd",
        "itemRgb",
        "cre_name",
        "pooled_cre_scores"
    ]
).with_columns(
    pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
    pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
)

# Map exact RGB strings to human-readable names
rgb_to_name = {
    "153,0,0": "dark_red",
    "101,0,0": "dark_red",
    "50,0,0": "dark_red",
    "204,0,0": "red",
    "255,0,0": "red",
    "0,0,51": "dark_blue",
    "0,0,102": "dark_blue",
    "0,0,153": "blue",
    "0,0,204": "blue",
    "0,0,255": "blue",
    "0,0,0": "black",
    "255,202,74": "yellow",
}

fantabio_bed_select = fantabio_bed.with_columns(
    pl.col("itemRgb").replace_strict(
        rgb_to_name,
        default="other"
    ).alias("itemRgb_name")
).select(
    "cre_id",
    "cre_name",
    "directionality",
    "fantabio_cre_class",
    "itemRgb",
    "itemRgb_name"
)

display(fantabio_bed_select)

shape: (513_895, 6)
┌─────────────┬──────────────────┬────────────────┬────────────────────┬────────────┬──────────────┐
│ cre_id      ┆ cre_name         ┆ directionality ┆ fantabio_cre_class ┆ itemRgb    ┆ itemRgb_name │
│ ---         ┆ ---              ┆ ---            ┆ ---                ┆ ---        ┆ ---          │
│ str         ┆ str              ┆ f64            ┆ str                ┆ str        ┆ str          │
╞═════════════╪══════════════════╪════════════════╪════════════════════╪════════════╪══════════════╡
│ FCHS_1      ┆ cp1@DDX11L1      ┆ -1.0           ┆ PLA                ┆ 0,0,255    ┆ blue         │
│ FCHS_2      ┆ cp1@WASH7P       ┆ 1.0            ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447416 ┆ cp1@DDX11L17     ┆ -0.684211      ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447417 ┆ FCHS_447417      ┆ 0.485714       ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_3      ┆ cp2@LOC101928626 ┆ -1.0           ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ …           ┆ …                ┆ …              ┆ …                  ┆ …          ┆ …            │
│ FCHS_447311 ┆ FCHS_447311      ┆ 1.0            ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447312 ┆ FCHS_447312      ┆ 0.0            ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447313 ┆ FCHS_447313      ┆ -1.0           ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447314 ┆ FCHS_447314      ┆ -1.0           ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_593940 ┆ FCHS_593940      ┆ 0.989305       ┆ PLA                ┆ 204,0,0    ┆ red          │
└─────────────┴──────────────────┴────────────────┴────────────────────┴────────────┴──────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. `fanta.bio` resource (annotation meta-data)

- GENCODE transcript (ENST からはじまる ID) が近傍 (TSS ± 500b) に存在する シスエレメントのみを選抜する

In [6]:
# Download from https://data.fanta.bio/cre/v1.2.1/human/ in 2026/07/05

fantabio_human_metadata = pl.read_ndjson(
    "../../Data/Database/fantabio/human-CREv1.2.1.hg38.cre-peaks_annotation.jsonl.gz"
).join(
    fantabio_bed_select,
    on=[
        "cre_id",
        "cre_name"
    ],
    how="inner"
).drop(
    "cre_old_names",
    "tss_ncbi_geneids",
    "tss_hgnc_mgi_ids",
    "tss_uniprot_ids",
    "tss_gene_names",
    "tss_gene_symbols",
    "tss_gene_synonyms",
    "tss_gene_sources"
).with_columns(
    # Q-score は後々フィルタリングの条件に使うかもしれないため、cast(pl.Int64) で整数型に変換しておく
    # print(fanta_bio_human_metadata["chip_atlas_antigens"].dtype) で確認できる
    pl.col("chip_atlas_antigens").list.eval(
        pl.struct([
            pl.element().struct.field("antigen").alias("antigen"),
            pl.element().struct.field("maxqscore").cast(pl.Int64).alias("maxqscore"),
            pl.element().struct.field("experiments").list.eval(
                pl.struct([
                    pl.element().struct.field("id").alias("id"),
                    pl.element().struct.field("qscore").cast(pl.Int64).alias("qscore"),
                ])
            ).alias("experiments"),
        ])
    ).alias("chip_atlas_antigens"),
).explode(
    "tss_transcripts"
).unnest(
    "tss_transcripts"
).filter(
    (pl.col("transcript_id").str.contains("ENST")) # Point1: Ensembl Transcript ID のみに絞る
).with_columns(
    # Point2: "transcript_distance" は str 型で読み込まれるが, int 型に変換しておく
    pl.col("transcript_distance")
    .cast(pl.Float64, strict=False)
    .round(0) # 小数点以下を四捨五入 (8件のみ .5 が存在)
    .cast(pl.Int64)
)

pl.Config.set_tbl_rows(4)
print(f"fanta.bio GENCODE ensembl transcript count: {fantabio_human_metadata.select('transcript_id').n_unique()}")
print(f"fanta.bio GENCODE ensembl transcript-CRE pairs count: {fantabio_human_metadata.select(['transcript_id', 'cre_id']).n_unique()}")
display(fantabio_human_metadata)

fanta.bio GENCODE ensembl transcript count: 411060
fanta.bio GENCODE ensembl transcript-CRE pairs count: 1121578

shape: (1_121_578, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_chrom ┆ cre_chrom ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ itemRgb   ┆ itemRgb_ │
│ ---       ┆ ---       ┆ _start    ┆ _end      ┆   ┆ ality     ┆ cre_class ┆ ---       ┆ name     │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆ i64       ┆ str       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_1    ┆ chr1      ┆ 10610     ┆ 10687     ┆ … ┆ -1.0      ┆ PLA       ┆ 0,0,255   ┆ blue     │
│ FCHS_1    ┆ chr1      ┆ 10610     ┆ 10687     ┆ … ┆ -1.0      ┆ PLA       ┆ 0,0,255   ┆ blue     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_5939 ┆ chrY      ┆ 26409259  ┆ 26409692  ┆ … ┆ 0.666667  ┆ ELA       ┆ 255,202,7 ┆ yellow   │
│ 38        ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆          │
│ FCHS_5939 ┆ chrY      ┆ 56881615  ┆ 56881922  ┆ … ┆ 0.989305  ┆ PLA       ┆ 204,0,0   ┆ red      │
│ 40        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. `JOIN`

In [7]:
HNscore_transcript_all_fantabio = HNscore_transcript_all.join(
    fantabio_human_metadata,
    on=["transcript_id"],
    how="left", # 対応するCREがない場合は、None となる
    coalesce=True
).sort(
    "HN2",
    descending=True
)

print(f"HNscore_transcript - fantabio CRE pairs count: {HNscore_transcript_all_fantabio.select(['transcript_id', 'cre_id']).n_unique()}")
display(HNscore_transcript_all_fantabio)

HNscore_transcript - fantabio CRE pairs count: 1227198

shape: (1_227_198, 39)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ directional ┆ fantabio_cr ┆ itemRgb    ┆ itemRgb_na │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ity         ┆ e_class     ┆ ---        ┆ me         │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ ---         ┆ str        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆ f64         ┆ str         ┆            ┆ str        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ 0.982111    ┆ PLA         ┆ 204,0,0    ┆ red        │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ 0.943234    ┆ PLA         ┆ 204,0,0    ┆ red        │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ -0.368421   ┆ ELA         ┆ 255,202,74 ┆ yellow     │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│ 0179.2      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# HNscore_transcript_all_fantabio.write_parquet(
#     f"../../out/fantabio/parquet_file/HNscore_transcript_all_fantabio_v{Execute_date}.parquet",
#     compression_level=9
# )

In [ ]:
# HNscore_transcript_all_fantabio.write_json(
#     f"../../out/fantabio/json_file/HNscore_transcript_all_fantabio_v{Execute_date}.json"
# )