&nbsp;

# Heat Shock Factor 1 (HSF1) regulation up5p transcripts

In [1]:
import re
import os
import pathlib
import datetime
import subprocess
import polars as pl
from IPython.display import display
from IPython.display import Image
from pygenometracks.readGtf import ReadGtf

pl.Config.set_fmt_str_lengths(200)
os.environ["POLARS_MAX_THREADS"] = "16"

In [2]:
execute_date = datetime.datetime.now().strftime("%y%m%d")  # noqa: DTZ005
print(f"Execute Date: {execute_date}")

Execute Date: 261011

&nbsp;

&nbsp;

&nbsp;

# 1. Basic Information

- [upsetplot を作成した notebook](../06_transcript_characterization/06_6_up5p_lncRNA_intersect.ipynb) で使用したファイルを全て読み込む
- upset plot の結果は、あくまで transcript - cre id ペアに則って分類したものであり、transcript level でみると、実は既に他の要素に入っている場合があるため

In [3]:
up5p_fantabio_all = pl.read_parquet(
    "../../out/fantabio/parquet_file/up5p_transcript_fantabio_v261001.parquet"
)

pl.Config.set_tbl_rows(2)
display(up5p_fantabio_all)

shape: (63_099, 39)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ directional ┆ fantabio_cr ┆ itemRgb    ┆ itemRgb_na │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ity         ┆ e_class     ┆ ---        ┆ me         │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ ---         ┆ str        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆ f64         ┆ str         ┆            ┆ str        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ 0.982111    ┆ PLA         ┆ 204,0,0    ┆ red        │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ 0.5         ┆ ELA         ┆ 255,202,74 ┆ yellow     │
│ 4581.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [4]:
# 2. Diff Analysis (ATAC-seq)
up5p_fantabio_diff_analysis = pl.read_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/transcript_cre/fantabio_HN2_up5p_v261002_diff_analysis_atac.parquet"
)

pl.Config.set_tbl_rows(2)
display(up5p_fantabio_diff_analysis)

shape: (4_423, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ [0.000001,  ┆ ["GSE101731 ┆ 3          ┆ ["GSE10173 │
│ 9758.6      ┆     ┆       ┆            ┆   ┆ 2.0457e-12, ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆ 0.000487]   ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_d21_42 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min",   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE209675_ ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ mcf7_42C_60 ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆ min"]       ┆            ┆ , "GSE1735 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 36_atac_d2 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 1_42C_60mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "GSE2096 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 75_mcf7_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000067 ┆ 102 ┆ 58    ┆ 246        ┆ … ┆ [0.008726]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 8039.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [5]:
# 3. Diff Analysis (HSF1)
up5p_fantabio_diff_analysis_hsf1 = pl.read_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/transcript_cre/fantabio_HN2_up5p_v261008_diff_analysis_chipseq_hsf1.parquet"
)

display(up5p_fantabio_diff_analysis_hsf1)

shape: (2_292, 51)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ [1.5375e-22 ┆ ["pair1_GSE ┆ 2          ┆ ["pair1_GS │
│ 9758.6      ┆     ┆       ┆            ┆   ┆ ,           ┆ 38901_hsf1_ ┆            ┆ E38901_hsf │
│             ┆     ┆       ┆            ┆   ┆ 1.0794e-10] ┆ mcf10a_hs_4 ┆            ┆ 1_mcf10a_h │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ s_42C_60mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "pair6_GSE2 ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ 09667_hsf1_ ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ polyclonal_ ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ ab_hs_42C_6 ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "pair6_G │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ SE209667_h │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ sf1_polycl │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ onal_ab_hs │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed"] │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000054 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ [0.00608,   ┆ ["pair1_GSE ┆ 2          ┆ ["pair1_GS │
│ 9882.1      ┆     ┆       ┆            ┆   ┆ 0.007043]   ┆ 38901_hsf1_ ┆            ┆ E38901_hsf │
│             ┆     ┆       ┆            ┆   ┆             ┆ mcf10a_hs_4 ┆            ┆ 1_mcf10a_h │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ s_42C_60mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "pair6_GSE2 ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ 09667_hsf1_ ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ polyclonal_ ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ ab_hs_42C_6 ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "pair6_G │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ SE209667_h │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ sf1_polycl │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ onal_ab_hs │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed"] │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [6]:
up5p_fantabio_cre_divergent = pl.read_parquet(
    "../../out/transcript_classification/divergent_transcript/pc_common_cre_lncRNA_divergent/up5p_fantabio_pc_common_cre_lncRNA_divergent.parquet"
)

display(up5p_fantabio_cre_divergent)

shape: (2_397, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ cre_chrom ┆ … ┆ fantomcat ┆ screen_pr ┆ ensembl_p ┆ fantomca │
│ ---       ┆ ---       ┆ cre_class ┆ ---       ┆   ┆ _transcri ┆ omoter_su ┆ romoter_w ┆ t_string │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ pt_info   ┆ pport     ┆ indow_sup ┆ ent_supp │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ port      ┆ ort      │
│           ┆           ┆           ┆           ┆   ┆ list[stru ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ct[7]]    ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_1105 ┆ cp7@HSPH1 ┆ PLA       ┆ chr13     ┆ … ┆ [{"CATG00 ┆ supported ┆ supported ┆ not supp │
│ 16        ┆           ┆           ┆           ┆   ┆ 000014230 ┆ by SCREEN ┆ by Ensemb ┆ orted by │
│           ┆           ┆           ┆           ┆   ┆ .1","prom ┆           ┆ l/GENCODE ┆ FANTOM-C │
│           ┆           ┆           ┆           ┆   ┆ oter",138 ┆           ┆ promoter  ┆ AT (stri │
│           ┆           ┆           ┆           ┆   ┆ .6,730.6, ┆           ┆ window    ┆ ngent)   │
│           ┆           ┆           ┆           ┆   ┆ null,null ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,1.3800e- ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 10}]      ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_1772 ┆ cp1@SPAG9 ┆ PLA       ┆ chr17     ┆ … ┆ [{"CATG00 ┆ supported ┆ supported ┆ supporte │
│ 59        ┆           ┆           ┆           ┆   ┆ 000031741 ┆ by SCREEN ┆ by Ensemb ┆ d by FAN │
│           ┆           ┆           ┆           ┆   ┆ .1","prom ┆           ┆ l/GENCODE ┆ TOM-CAT  │
│           ┆           ┆           ┆           ┆   ┆ oter",347 ┆           ┆ promoter  ┆ (stringe │
│           ┆           ┆           ┆           ┆   ┆ .8,108.8, ┆           ┆ window    ┆ nt)      │
│           ┆           ┆           ┆           ┆   ┆ null,9.72 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 70e-33,5. ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 3900e-42} ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ]         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
e_derived_lncRNA = pl.read_parquet(
    "../../out/transcript_classification/enhancer_derived_lncRNA/up5p_enhancer_derived_lncRNA_v261010.parquet"
)

display(e_derived_lncRNA)

shape: (12_630, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ e_strand ┆ e_RNACent ┆ e_annotat ┆ e_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_9445 ┆ FCHS_9445 ┆ PLA       ┆ FCHS_9449 ┆ … ┆ -        ┆ URS0002A2 ┆ ["CLS3    ┆ ["basic", │
│ 1         ┆ 1         ┆           ┆ 9         ┆   ┆          ┆ 36EE      ┆ project"] ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ", …      │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "TAGENE"] │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_2656 ┆ cp2@LOC10 ┆ ELA       ┆ FCHS_2658 ┆ … ┆ +        ┆ URS0002A5 ┆ ["CLS3    ┆ ["basic", │
│ 30        ┆ 5369306   ┆           ┆ 30        ┆   ┆          ┆ 7053      ┆ project"] ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ", …      │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "TAGENE"] │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Upset plot Result

In [8]:
up5p_intersect_result = pl.read_csv(
    "../../out/transcript_classification/upsetplot/up5p_transcript_upset_data_v261010.tsv",
    separator="\t",
    n_threads=16
).with_columns(
    # Split "ENST...-FCHS_..." into transcript_id and cre_id
    pl.col("id")
    .str.split_exact("-", 1)
    .struct.rename_fields(["transcript_id", "cre_id"])
    .alias("id_parts")
).unnest("id_parts")


display(up5p_intersect_result)

shape: (8_607, 9)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ all   ┆ derived    ┆ Diff       ┆ Diff       ┆ … ┆ enhancer- ┆ id        ┆ transcrip ┆ cre_id    │
│ pairs ┆ from CLS3  ┆ Analysis   ┆ Analysis   ┆   ┆ derived   ┆ ---       ┆ t_id      ┆ ---       │
│ ---   ┆ project    ┆ (ATAC-seq) ┆ (HSF1)     ┆   ┆ ---       ┆ str       ┆ ---       ┆ str       │
│ bool  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ bool      ┆           ┆ str       ┆           │
│       ┆ bool       ┆ bool       ┆ bool       ┆   ┆           ┆           ┆           ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ true  ┆ false      ┆ false      ┆ false      ┆ … ┆ false     ┆ ENST00000 ┆ ENST00000 ┆ FCHS_3394 │
│       ┆            ┆            ┆            ┆   ┆           ┆ 508735.5- ┆ 508735.5  ┆ 38        │
│       ┆            ┆            ┆            ┆   ┆           ┆ FCHS_3394 ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ 38        ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ true  ┆ false      ┆ false      ┆ false      ┆ … ┆ true      ┆ ENST00000 ┆ ENST00000 ┆ FCHS_2389 │
│       ┆            ┆            ┆            ┆   ┆           ┆ 660374.1- ┆ 660374.1  ┆ 29        │
│       ┆            ┆            ┆            ┆   ┆           ┆ FCHS_2389 ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ 29        ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1. HSF1 regulation + divergent + Diff-Analysis

- 最も注目できる up5p transcripts の組み合わせ

In [9]:
hsf1_divergent_lncrna = up5p_intersect_result.filter(
    (pl.col("Diff Analysis (HSF1)") == True)
    & (pl.col("divergent") == True)
    & (pl.col("Diff Analysis (ATAC-seq)") == True)
    & (pl.col("enhancer-derived") == False)
    # & (pl.col("derived from CLS3 project") == True)
)

display(hsf1_divergent_lncrna)

shape: (20, 9)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ all   ┆ derived    ┆ Diff       ┆ Diff       ┆ … ┆ enhancer- ┆ id        ┆ transcrip ┆ cre_id    │
│ pairs ┆ from CLS3  ┆ Analysis   ┆ Analysis   ┆   ┆ derived   ┆ ---       ┆ t_id      ┆ ---       │
│ ---   ┆ project    ┆ (ATAC-seq) ┆ (HSF1)     ┆   ┆ ---       ┆ str       ┆ ---       ┆ str       │
│ bool  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ bool      ┆           ┆ str       ┆           │
│       ┆ bool       ┆ bool       ┆ bool       ┆   ┆           ┆           ┆           ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ true  ┆ false      ┆ true       ┆ true       ┆ … ┆ false     ┆ ENST00000 ┆ ENST00000 ┆ FCHS_3380 │
│       ┆            ┆            ┆            ┆   ┆           ┆ 665702.1- ┆ 665702.1  ┆ 98        │
│       ┆            ┆            ┆            ┆   ┆           ┆ FCHS_3380 ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ 98        ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ true  ┆ true       ┆ true       ┆ true       ┆ … ┆ false     ┆ ENST00000 ┆ ENST00000 ┆ FCHS_1105 │
│       ┆            ┆            ┆            ┆   ┆           ┆ 729764.1- ┆ 729764.1  ┆ 16        │
│       ┆            ┆            ┆            ┆   ┆           ┆ FCHS_1105 ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ 16        ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
hsf1_divergent_lncrna_list = up5p_fantabio_cre_divergent.filter(
    # pair としてフィルタリング
    (pl.col("lncrna_transcript_id").is_in(hsf1_divergent_lncrna.get_column("transcript_id").unique().implode()))
    & (pl.col("cre_id").is_in(hsf1_divergent_lncrna.get_column("cre_id").unique().implode()))
)

pl.Config.set_tbl_rows(20)
print(hsf1_divergent_lncrna_list.select(pl.col("pc_transcript_info").struct.field("gene_symbol").unique()))

pl.Config.set_tbl_rows(2)
display(hsf1_divergent_lncrna_list)

shape: (15, 1)
┌─────────────┐
│ gene_symbol │
│ ---         │
│ str         │
╞═════════════╡
│ IER5        │
│ HSPH1       │
│ DNAJB1      │
│ STIP1       │
│ ZFAND2A     │
│ HSP90AB1    │
│ UBC         │
│ SIRPA       │
│ HSPA4       │
│ TAF7        │
│ FKBP4       │
│ HSPA1B      │
│ ZSCAN31     │
│ TENT5A      │
│ SOD1        │
└─────────────┘

shape: (147, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ cre_chrom ┆ … ┆ fantomcat ┆ screen_pr ┆ ensembl_p ┆ fantomca │
│ ---       ┆ ---       ┆ cre_class ┆ ---       ┆   ┆ _transcri ┆ omoter_su ┆ romoter_w ┆ t_string │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ pt_info   ┆ pport     ┆ indow_sup ┆ ent_supp │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ port      ┆ ort      │
│           ┆           ┆           ┆           ┆   ┆ list[stru ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ct[7]]    ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_1105 ┆ cp7@HSPH1 ┆ PLA       ┆ chr13     ┆ … ┆ [{"CATG00 ┆ supported ┆ supported ┆ not supp │
│ 16        ┆           ┆           ┆           ┆   ┆ 000014230 ┆ by SCREEN ┆ by Ensemb ┆ orted by │
│           ┆           ┆           ┆           ┆   ┆ .1","prom ┆           ┆ l/GENCODE ┆ FANTOM-C │
│           ┆           ┆           ┆           ┆   ┆ oter",138 ┆           ┆ promoter  ┆ AT (stri │
│           ┆           ┆           ┆           ┆   ┆ .6,730.6, ┆           ┆ window    ┆ ngent)   │
│           ┆           ┆           ┆           ┆   ┆ null,null ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,1.3800e- ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 10}]      ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_3380 ┆ cp4@HSPA4 ┆ PLA       ┆ chr5      ┆ … ┆ null      ┆ supported ┆ supported ┆ not supp │
│ 98        ┆           ┆           ┆           ┆   ┆           ┆ by SCREEN ┆ by Ensemb ┆ orted by │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ l/GENCODE ┆ FANTOM-C │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ promoter  ┆ AT (stri │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ window    ┆ ngent)   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
# metascape でエンリッチメント解析を行うための protein-coding transcript のリストを取得
# metascape execution: 2026-10-11
hsf1_divergent_pc_transcript_list = hsf1_divergent_lncrna_list.select(
    pl.col("pc_transcript_id").unique()
)

# hsf1_divergent_pc_transcript_list.write_csv(
#     "../../out/metascape/transcript_list/up5p_diffanalysis_atac_hsf1/hsf1_divergent_pc_transcript_list.tsv",
#     separator="\t",
#     include_header=False
# )

# display(hsf1_divergent_pc_transcript_list)

In [35]:
# For TogoMCP survey
hsf1_divergent_pc_lncRNA_cre_list = hsf1_divergent_lncrna_list.select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "pc_transcript_id",
    "pc_transcript_distance",
    "pc_HN2",
    "lncrna_transcript_id",
    "lncrna_transcript_distance",
    "lncrna_HN2",
    "strand_type",
    "pc_lncrna_HN2"
).unique().sort(
    by=["pc_lncrna_HN2"],
    descending=True
)

hsf1_divergent_pc_lncRNA_cre_list.write_csv(
    "../../out/transcript_survey/TogoMCP_survey/hsf1_divergent_pc_lncRNA_common_cre_list.tsv",
    separator="\t",
    include_header=True
)

display(hsf1_divergent_pc_lncRNA_cre_list)

shape: (147, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ pc_transc ┆ … ┆ lncrna_tr ┆ lncrna_HN ┆ strand_ty ┆ pc_lncrn │
│ ---       ┆ ---       ┆ cre_class ┆ ript_id   ┆   ┆ anscript_ ┆ 2         ┆ pe        ┆ a_HN2    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ distance  ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ ---       ┆ i64       ┆ str       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_1105 ┆ cp7@HSPH1 ┆ PLA       ┆ ENST00000 ┆ … ┆ 0         ┆ 295       ┆ opposite  ┆ 558      │
│ 16        ┆           ┆           ┆ 954002.1  ┆   ┆           ┆           ┆ strand    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_3380 ┆ cp4@HSPA4 ┆ PLA       ┆ ENST00000 ┆ … ┆ 0         ┆ 62        ┆ opposite  ┆ 106      │
│ 98        ┆           ┆           ┆ 870719.1  ┆   ┆           ┆           ┆ strand    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
hsf1_divergent_lncrna_transcript_list = up5p_fantabio_diff_analysis.filter(
    # pair としてフィルタリング
    (pl.col("transcript_id").is_in(hsf1_divergent_lncrna.get_column("transcript_id").unique().implode()))
    & (pl.col("cre_id").is_in(hsf1_divergent_lncrna.get_column("cre_id").unique().implode()))
)

hsf1_divergent_lncrna_transcript_list.write_parquet(
    "../../out/transcript_survey/divergent_transcript/up5p_hsf1_divergent_lncrna_transcript_list.parquet"
)

display(hsf1_divergent_lncrna_transcript_list)

shape: (20, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000072 ┆ 315 ┆ 20    ┆ 71         ┆ … ┆ [0.000003,  ┆ ["GSE173536 ┆ 2          ┆ ["GSE17353 │
│ 9765.1      ┆     ┆       ┆            ┆   ┆ 6.8502e-7]  ┆ _atac_d21_4 ┆            ┆ 6_atac_d21 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "GSE173536 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _atac_t21_ │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 42C_60min_ │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ intersecti │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ng_human-C │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ REv1.2.1.h │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ g38.cre-pe │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ aks.bed"]  │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000081 ┆ 52  ┆ 8     ┆ 346        ┆ … ┆ [0.000105]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 0160.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# survey

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. HSF1-regulated lncRNA + diff-analysis (ATAC-seq) + enhancer-derived

In [13]:
hsf1_lncrna_enhancer_derived = up5p_intersect_result.filter(
    (pl.col("Diff Analysis (HSF1)") == True)
    & (pl.col("divergent") == False)
    & (pl.col("Diff Analysis (ATAC-seq)") == True)
    & (pl.col("enhancer-derived") == True)
)

display(hsf1_lncrna_enhancer_derived)

shape: (17, 9)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ all   ┆ derived    ┆ Diff       ┆ Diff       ┆ … ┆ enhancer- ┆ id        ┆ transcrip ┆ cre_id    │
│ pairs ┆ from CLS3  ┆ Analysis   ┆ Analysis   ┆   ┆ derived   ┆ ---       ┆ t_id      ┆ ---       │
│ ---   ┆ project    ┆ (ATAC-seq) ┆ (HSF1)     ┆   ┆ ---       ┆ str       ┆ ---       ┆ str       │
│ bool  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ bool      ┆           ┆ str       ┆           │
│       ┆ bool       ┆ bool       ┆ bool       ┆   ┆           ┆           ┆           ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ true  ┆ true       ┆ true       ┆ true       ┆ … ┆ true      ┆ ENST00000 ┆ ENST00000 ┆ FCHS_3450 │
│       ┆            ┆            ┆            ┆   ┆           ┆ 792518.1- ┆ 792518.1  ┆ 96        │
│       ┆            ┆            ┆            ┆   ┆           ┆ FCHS_3450 ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ 96        ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ true  ┆ true       ┆ true       ┆ true       ┆ … ┆ true      ┆ ENST00000 ┆ ENST00000 ┆ FCHS_2674 │
│       ┆            ┆            ┆            ┆   ┆           ┆ 842153.1- ┆ 842153.1  ┆ 10        │
│       ┆            ┆            ┆            ┆   ┆           ┆ FCHS_2674 ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ 10        ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
hsf1_lncrna_enhancer_derived_transcript_list = up5p_fantabio_all.filter(
    (pl.col("transcript_id").is_in(hsf1_lncrna_enhancer_derived.get_column("transcript_id").unique().implode()))
    & (pl.col("cre_id").is_in(hsf1_lncrna_enhancer_derived.get_column("cre_id").unique().implode()))
)

display(hsf1_lncrna_enhancer_derived_transcript_list)

shape: (17, 39)
┌──────────────┬─────┬───────┬────────────┬───┬──────────────┬─────────────┬─────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ directionali ┆ fantabio_cr ┆ itemRgb ┆ itemRgb_nam │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ ty           ┆ e_class     ┆ ---     ┆ e           │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---          ┆ ---         ┆ str     ┆ ---         │
│ str          ┆     ┆       ┆            ┆   ┆ f64          ┆ str         ┆         ┆ str         │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════════╪═════════════╪═════════╪═════════════╡
│ ENST00000686 ┆ 210 ┆ 24    ┆ 172        ┆ … ┆ 0.554413     ┆ PLA         ┆ 101,0,0 ┆ dark_red    │
│ 199.2        ┆     ┆       ┆            ┆   ┆              ┆             ┆         ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …            ┆ …           ┆ …       ┆ …           │
│ ENST00000752 ┆ 123 ┆ 74    ┆ 209        ┆ … ┆ 0.649832     ┆ PLA         ┆ 153,0,0 ┆ dark_red    │
│ 769.1        ┆     ┆       ┆            ┆   ┆              ┆             ┆         ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────────┴─────────────┴─────────┴─────────────┘

In [15]:
# check
FCHS_94451 = hsf1_lncrna_enhancer_derived_transcript_list.filter(
    pl.col("cre_id") == "FCHS_94451"
)

display(FCHS_94451)

shape: (1, 39)
┌──────────────┬─────┬───────┬────────────┬───┬──────────────┬─────────────┬─────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ directionali ┆ fantabio_cr ┆ itemRgb ┆ itemRgb_nam │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ ty           ┆ e_class     ┆ ---     ┆ e           │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---          ┆ ---         ┆ str     ┆ ---         │
│ str          ┆     ┆       ┆            ┆   ┆ f64          ┆ str         ┆         ┆ str         │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════════╪═════════════╪═════════╪═════════════╡
│ ENST00000812 ┆ 144 ┆ 16    ┆ 246        ┆ … ┆ -0.114194    ┆ PLA         ┆ 0,0,0   ┆ black       │
│ 391.1        ┆     ┆       ┆            ┆   ┆              ┆             ┆         ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────────┴─────────────┴─────────┴─────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2-1. Main Focus: CRE

- ENCODE-rE2G の予測で、どのような 遺伝子の promoter を標的にしているかをここで調べる

In [16]:
hsf1_lncrna_enhancer_derived_encode_re2g_list = e_derived_lncRNA.filter(
    (pl.col("e_transcript_id").is_in(hsf1_lncrna_enhancer_derived_transcript_list.get_column("transcript_id").unique().implode()))
    & (pl.col("cre_id").is_in(hsf1_lncrna_enhancer_derived_transcript_list.get_column("cre_id").unique().implode()))
)

display(hsf1_lncrna_enhancer_derived_encode_re2g_list)

shape: (119, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ e_strand ┆ e_RNACent ┆ e_annotat ┆ e_tags    │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_9445 ┆ FCHS_9445 ┆ PLA       ┆ FCHS_9449 ┆ … ┆ -        ┆ URS0002A2 ┆ ["CLS3    ┆ ["basic", │
│ 1         ┆ 1         ┆           ┆ 9         ┆   ┆          ┆ 36EE      ┆ project"] ┆ "Ensembl_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ canonical │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ", …      │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "TAGENE"] │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_1579 ┆ FCHS_1579 ┆ ELA       ┆ FCHS_1580 ┆ … ┆ -        ┆ URS0002A2 ┆ ["CLS3    ┆ ["TAGENE" │
│ 7         ┆ 7         ┆           ┆ 3         ┆   ┆          ┆ D986      ┆ project"] ┆ ]         │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [17]:
# (UP5P) target promoter side transcript candidate
fantabio_HN2_up5p_target_transcript_candidate = up5p_fantabio_all.select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "transcript_id",
    "HN2",
    "transcript_type",
    "gene_id",
    "gene_symbol",
    "strand",
    "RNACentral_ID",
    "annotation_remarks",
    "tags"
).unique().rename(
    # assign frag name "t" to target promoter side
    {
        "cre_id": "target_cre_id",
        "cre_name": "target_cre_name",
        "fantabio_cre_class": "target_fantabio_cre_class",
        "transcript_id": "t_transcript_id",
        "HN2": "t_HN2",
        "transcript_type": "t_transcript_type",
        "gene_id": "t_gene_id",
        "gene_symbol": "t_gene_symbol",
        "strand": "t_strand",
        "RNACentral_ID": "t_RNACentral_ID",
        "annotation_remarks": "t_annotation_remarks",
        "tags": "t_tags"
    }
)

display(fantabio_HN2_up5p_target_transcript_candidate)

shape: (63_099, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ target_cr ┆ target_cr ┆ target_fa ┆ t_transcr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ e_id      ┆ e_name    ┆ ntabio_cr ┆ ipt_id    ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ ---       ┆ ---       ┆ e_class   ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆ str       ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_1586 ┆ cp1@SLC7A ┆ ELA       ┆ ENST00000 ┆ … ┆ +        ┆ null      ┆ ["RNA-Seq ┆ ["RNA_Seq │
│ 20        ┆ 6OS       ┆           ┆ 562050.6  ┆   ┆          ┆           ┆ supported ┆ _supporte │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ only"]    ┆ d_only"]  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_1300 ┆ cp3@SNHG1 ┆ ELA       ┆ ENST00000 ┆ … ┆ -        ┆ null      ┆ null      ┆ []        │
│ 84        ┆ 0         ┆           ┆ 663212.1  ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [18]:
# (DOWN5P) target promoter side transcript candidate

down5p_fantabio_all = pl.read_parquet(
    "../../out/fantabio/parquet_file/bottom5p_transcript_fantabio_v261001.parquet"
)

fantabio_HN2_down5p_target_transcript_candidate = down5p_fantabio_all.select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "transcript_id",
    "HN2",
    "transcript_type",
    "gene_id",
    "gene_symbol",
    "strand",
    "RNACentral_ID",
    "annotation_remarks",
    "tags"
).unique().rename(
    # assign frag name "t" to target promoter side
    {
        "cre_id": "target_cre_id",
        "cre_name": "target_cre_name",
        "fantabio_cre_class": "target_fantabio_cre_class",
        "transcript_id": "t_transcript_id",
        "HN2": "t_HN2",
        "transcript_type": "t_transcript_type",
        "gene_id": "t_gene_id",
        "gene_symbol": "t_gene_symbol",
        "strand": "t_strand",
        "RNACentral_ID": "t_RNACentral_ID",
        "annotation_remarks": "t_annotation_remarks",
        "tags": "t_tags"
    }
)

display(fantabio_HN2_down5p_target_transcript_candidate)

shape: (66_960, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ target_cr ┆ target_cr ┆ target_fa ┆ t_transcr ┆ … ┆ t_strand ┆ t_RNACent ┆ t_annotat ┆ t_tags    │
│ e_id      ┆ e_name    ┆ ntabio_cr ┆ ipt_id    ┆   ┆ ---      ┆ ral_ID    ┆ ion_remar ┆ ---       │
│ ---       ┆ ---       ┆ e_class   ┆ ---       ┆   ┆ str      ┆ ---       ┆ ks        ┆ list[str] │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆          ┆ str       ┆ ---       ┆           │
│           ┆           ┆ str       ┆           ┆   ┆          ┆           ┆ list[str] ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_1724 ┆ cp22@ERBB ┆ ELA       ┆ ENST00000 ┆ … ┆ +        ┆ null      ┆ null      ┆ ["mRNA_st │
│ 62        ┆ 2         ┆           ┆ 580074.1  ┆   ┆          ┆           ┆           ┆ art_NF",  │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "mRNA_end │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ _NF", …   │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ "cds_end_ │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ NF"]      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ FCHS_4155 ┆ cp2@MIR68 ┆ PLA       ┆ ENST00000 ┆ … ┆ -        ┆ null      ┆ null      ┆ []        │
│ 04        ┆ 50,cp7@RP ┆           ┆ 525232.5  ┆   ┆          ┆           ┆           ┆           │
│           ┆ L8        ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

## 2-1-1: (enhancer) up5p - (target promoter) up5p (called UP-UP)

- 標的となる transcript も今回の解析では up5p transcript に分類されている pattern

In [19]:
hsf1_lncrna_enhancer_derived_encode_re2g_list_target = (
    hsf1_lncrna_enhancer_derived_encode_re2g_list
    .join(
        fantabio_HN2_up5p_target_transcript_candidate,
        on=["target_cre_id", "target_cre_name", "target_fantabio_cre_class"],
        how="inner"
    )
).sort(
    by=["re2g_dataset_count"],
    descending=True
).with_columns(
    # Join enhancer CRE, enhancer transcript, target CRE, and target gene
    pl.concat_str(
        [
            pl.col("cre_id"),
            pl.col("e_transcript_id"),
            # pl.col("target_cre_id"),
            # pl.col("t_gene_id"),
        ],
        separator="-",
    ).alias("cre-e_transcript")
).with_columns(
    # Join enhancer CRE, enhancer transcript, target CRE, and target gene
    pl.concat_str(
        [
            pl.col("cre_id"),
            pl.col("e_transcript_id"),
            pl.col("target_cre_id"),
            # pl.col("t_gene_id"),
        ],
        separator="-",
    ).alias("cre-e_transcript-target_cre")
).with_columns(
    # Join enhancer CRE, enhancer transcript, target CRE, and target gene
    pl.concat_str(
        [
            pl.col("cre_id"),
            pl.col("e_transcript_id"),
            pl.col("target_cre_id"),
            pl.col("t_gene_id"),
        ],
        separator="-",
    ).alias("cre-e_transcript-target_cre-t_gene_id")
)

hsf1_lncrna_enhancer_derived_encode_re2g_list_target.write_parquet(
    "../../out/transcript_survey/enhancer_derived_transcript/up5p_hsf1_enhancer_derived_encode_re2g_list_up5p_up5p.parquet"
)

display(hsf1_lncrna_enhancer_derived_encode_re2g_list_target)

shape: (171, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ t_tags    ┆ cre-e_tra ┆ cre-e_tra ┆ cre-e_tr │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---       ┆ nscript   ┆ nscript-t ┆ anscript │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ list[str] ┆ ---       ┆ arget_cre ┆ -target_ │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ cre-t_ge │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ ne_id    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_7366 ┆ cp2@LINC0 ┆ PLA       ┆ FCHS_7369 ┆ … ┆ ["basic", ┆ FCHS_7366 ┆ FCHS_7366 ┆ FCHS_736 │
│ 9         ┆ 2736      ┆           ┆ 4         ┆   ┆ "Ensembl_ ┆ 9-ENST000 ┆ 9-ENST000 ┆ 69-ENST0 │
│           ┆           ┆           ┆           ┆   ┆ canonical ┆ 00689737. ┆ 00689737. ┆ 00006897 │
│           ┆           ┆           ┆           ┆   ┆ ", …      ┆ 3         ┆ 3-FCHS_73 ┆ 37.3-FCH │
│           ┆           ┆           ┆           ┆   ┆ "TAGENE"] ┆           ┆ 694       ┆ S_73694- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ENSG0000 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0301979. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_8534 ┆ cp2@LINC0 ┆ PLA       ┆ FCHS_8538 ┆ … ┆ ["RNA_Seq ┆ FCHS_8534 ┆ FCHS_8534 ┆ FCHS_853 │
│ 8         ┆ 2731      ┆           ┆ 4         ┆   ┆ _supporte ┆ 8-ENST000 ┆ 8-ENST000 ┆ 48-ENST0 │
│           ┆           ┆           ┆           ┆   ┆ d_only"]  ┆ 00526377. ┆ 00526377. ┆ 00005263 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 1-FCHS_85 ┆ 77.1-FCH │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 384       ┆ S_85384- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ENSG0000 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0151503. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 15       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
# check
ENEMAL = hsf1_lncrna_enhancer_derived_encode_re2g_list_target.filter(
    pl.col("e_gene_symbol") == "ENEMAL"
)

display(ENEMAL)

shape: (0, 37)
┌────────┬──────────┬────────────┬────────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ cre_id ┆ cre_name ┆ fantabio_c ┆ target_cre ┆ … ┆ t_tags    ┆ cre-e_tran ┆ cre-e_tra ┆ cre-e_tra │
│ ---    ┆ ---      ┆ re_class   ┆ _id        ┆   ┆ ---       ┆ script     ┆ nscript-t ┆ nscript-t │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ list[str] ┆ ---        ┆ arget_cre ┆ arget_cre │
│        ┆          ┆ str        ┆ str        ┆   ┆           ┆ str        ┆ ---       ┆ -t_gene_i │
│        ┆          ┆            ┆            ┆   ┆           ┆            ┆ str       ┆ d         │
│        ┆          ┆            ┆            ┆   ┆           ┆            ┆           ┆ ---       │
│        ┆          ┆            ┆            ┆   ┆           ┆            ┆           ┆ str       │
╞════════╪══════════╪════════════╪════════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
└────────┴──────────┴────────────┴────────────┴───┴───────────┴────────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2-1-2: (enhancer) up5p - (target promoter) down5p (called UP-DOWN)

- 標的となる transcript が、今回の解析では、down5p に含まれるペア
- 念のため、既に UP-UP に含まれていないことも後で確認できるように、flag を付けておく
- 興味深いことに、UP-DOWN のペアの半分くらいは、同じ CRE の 遺伝子レベル で UP-UP と同様の CRE を標的にしている (違うのは transcript だけ)

In [21]:
hsf1_lncrna_enhancer_derived_encode_re2g_list_target_down5p = (
    hsf1_lncrna_enhancer_derived_encode_re2g_list
    .join(
        fantabio_HN2_down5p_target_transcript_candidate,
        on=["target_cre_id", "target_cre_name", "target_fantabio_cre_class"],
        how="inner"
    )
).sort(
    by=["re2g_dataset_count"],
    descending=True
).with_columns(
    # Join enhancer CRE, enhancer transcript, target CRE, and target gene
    pl.concat_str(
        [
            pl.col("cre_id"),
            pl.col("e_transcript_id"),
            # pl.col("target_cre_id"),
            # pl.col("t_gene_id"),
        ],
        separator="-",
    ).alias("cre-e_transcript")
).with_columns(
    # Join enhancer CRE, enhancer transcript, target CRE, and target gene
    pl.concat_str(
        [
            pl.col("cre_id"),
            pl.col("e_transcript_id"),
            pl.col("target_cre_id"),
            # pl.col("t_gene_id"),
        ],
        separator="-",
    ).alias("cre-e_transcript-target_cre")
).with_columns(
    # Join enhancer CRE, enhancer transcript, target CRE, and target gene
    pl.concat_str(
        [
            pl.col("cre_id"),
            pl.col("e_transcript_id"),
            pl.col("target_cre_id"),
            pl.col("t_gene_id"),
        ],
        separator="-",
    ).alias("cre-e_transcript-target_cre-t_gene_id")
)


hsf1_lncrna_enhancer_derived_encode_re2g_list_target_down5p.write_parquet(
    "../../out/transcript_survey/enhancer_derived_transcript/up5p_hsf1_enhancer_derived_encode_re2g_list_up5p_down5p.parquet"
)

display(hsf1_lncrna_enhancer_derived_encode_re2g_list_target_down5p)

shape: (93, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ t_tags    ┆ cre-e_tra ┆ cre-e_tra ┆ cre-e_tr │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---       ┆ nscript   ┆ nscript-t ┆ anscript │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ list[str] ┆ ---       ┆ arget_cre ┆ -target_ │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ cre-t_ge │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ ne_id    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_2799 ┆ FCHS_2799 ┆ PLA       ┆ FCHS_2799 ┆ … ┆ ["basic", ┆ FCHS_2799 ┆ FCHS_2799 ┆ FCHS_279 │
│ 18        ┆ 18        ┆           ┆ 32        ┆   ┆ "Ensembl_ ┆ 18-ENST00 ┆ 18-ENST00 ┆ 918-ENST │
│           ┆           ┆           ┆           ┆   ┆ canonical ┆ 000773816 ┆ 000773816 ┆ 00000773 │
│           ┆           ┆           ┆           ┆   ┆ ", … "exp ┆ .1        ┆ .1-FCHS_2 ┆ 816.1-FC │
│           ┆           ┆           ┆           ┆   ┆ _conf"]   ┆           ┆ 79932     ┆ HS_27993 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2-ENSG00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00024450 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.3      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_7366 ┆ cp2@LINC0 ┆ PLA       ┆ FCHS_7351 ┆ … ┆ ["basic", ┆ FCHS_7366 ┆ FCHS_7366 ┆ FCHS_736 │
│ 9         ┆ 2736      ┆           ┆ 0         ┆   ┆ "appris_p ┆ 9-ENST000 ┆ 9-ENST000 ┆ 69-ENST0 │
│           ┆           ┆           ┆           ┆   ┆ rincipal_ ┆ 00689737. ┆ 00689737. ┆ 00006897 │
│           ┆           ┆           ┆           ┆   ┆ 1",       ┆ 3         ┆ 3-FCHS_73 ┆ 37.3-FCH │
│           ┆           ┆           ┆           ┆   ┆ "CCDS"]   ┆           ┆ 510       ┆ S_73510- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ENSG0000 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0162241. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 14       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
# check
hsf1_lncrna_enhancer_derived_encode_re2g_list_target_down5p_filter = hsf1_lncrna_enhancer_derived_encode_re2g_list_target_down5p.filter(
    (
        pl.col("cre-e_transcript-target_cre-t_gene_id").is_in(
            hsf1_lncrna_enhancer_derived_encode_re2g_list_target.get_column("cre-e_transcript-target_cre-t_gene_id").unique().implode()
        )
    )
)

display(hsf1_lncrna_enhancer_derived_encode_re2g_list_target_down5p_filter)

shape: (46, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ t_tags    ┆ cre-e_tra ┆ cre-e_tra ┆ cre-e_tr │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ ---       ┆ nscript   ┆ nscript-t ┆ anscript │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ list[str] ┆ ---       ┆ arget_cre ┆ -target_ │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ cre-t_ge │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ ne_id    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_1075 ┆ FCHS_1075 ┆ PLA       ┆ FCHS_1074 ┆ … ┆ ["basic", ┆ FCHS_1075 ┆ FCHS_1075 ┆ FCHS_107 │
│ 51        ┆ 51        ┆           ┆ 77        ┆   ┆ "GENCODE_ ┆ 51-ENST00 ┆ 51-ENST00 ┆ 551-ENST │
│           ┆           ┆           ┆           ┆   ┆ Primary", ┆ 000776681 ┆ 000776681 ┆ 00000776 │
│           ┆           ┆           ┆           ┆   ┆ "TAGENE"] ┆ .1        ┆ .1-FCHS_1 ┆ 681.1-FC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 07477     ┆ HS_10747 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7-ENSG00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00007306 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0.18     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_8534 ┆ cp2@LINC0 ┆ PLA       ┆ FCHS_8538 ┆ … ┆ ["RNA_Seq ┆ FCHS_8534 ┆ FCHS_8534 ┆ FCHS_853 │
│ 8         ┆ 2731      ┆           ┆ 4         ┆   ┆ _supporte ┆ 8-ENST000 ┆ 8-ENST000 ┆ 48-ENST0 │
│           ┆           ┆           ┆           ┆   ┆ d_only"]  ┆ 00526377. ┆ 00526377. ┆ 00005263 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 1-FCHS_85 ┆ 77.1-FCH │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 384       ┆ S_85384- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ENSG0000 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0151503. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 15       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. Only HSF1-regulated lncRNA

- 他の要素をもたない lncRNA

In [23]:
only_hsf1_lncrna = up5p_intersect_result.filter(
    (pl.col("Diff Analysis (HSF1)") == True)
    & (pl.col("divergent") == False)
    & (pl.col("Diff Analysis (ATAC-seq)") == False)
    & (pl.col("enhancer-derived") == False)
)

display(only_hsf1_lncrna)

shape: (61, 9)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ all   ┆ derived    ┆ Diff       ┆ Diff       ┆ … ┆ enhancer- ┆ id        ┆ transcrip ┆ cre_id    │
│ pairs ┆ from CLS3  ┆ Analysis   ┆ Analysis   ┆   ┆ derived   ┆ ---       ┆ t_id      ┆ ---       │
│ ---   ┆ project    ┆ (ATAC-seq) ┆ (HSF1)     ┆   ┆ ---       ┆ str       ┆ ---       ┆ str       │
│ bool  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ bool      ┆           ┆ str       ┆           │
│       ┆ bool       ┆ bool       ┆ bool       ┆   ┆           ┆           ┆           ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ true  ┆ true       ┆ false      ┆ true       ┆ … ┆ false     ┆ ENST00000 ┆ ENST00000 ┆ FCHS_6153 │
│       ┆            ┆            ┆            ┆   ┆           ┆ 824599.1- ┆ 824599.1  ┆ 0         │
│       ┆            ┆            ┆            ┆   ┆           ┆ FCHS_6153 ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ 0         ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ true  ┆ true       ┆ false      ┆ true       ┆ … ┆ false     ┆ ENST00000 ┆ ENST00000 ┆ FCHS_4423 │
│       ┆            ┆            ┆            ┆   ┆           ┆ 776419.1- ┆ 776419.1  ┆ 31        │
│       ┆            ┆            ┆            ┆   ┆           ┆ FCHS_4423 ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ 31        ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [31]:
only_hsf1_lncrna_list = up5p_fantabio_diff_analysis_hsf1.filter(
    # pair としてフィルタリング
    (pl.col("transcript_id").is_in(only_hsf1_lncrna.get_column("transcript_id").unique().implode()))
    & (pl.col("cre_id").is_in(only_hsf1_lncrna.get_column("cre_id").unique().implode()))
).filter(
    pl.col("RNACentral_ID").is_not_null()
).join(
    up5p_fantabio_cre_divergent.select(pl.col("lncrna_transcript_id").unique()),
    left_on="transcript_id",
    right_on="lncrna_transcript_id",
    how="anti",
).join(
    e_derived_lncRNA.select(pl.col("e_transcript_id").unique()),
    left_on="transcript_id",
    right_on="e_transcript_id",
    how="anti",
)

only_hsf1_lncrna_list.write_parquet(
    "../../out/transcript_survey/only_hsf1/only_hsf1_lncrna_list.parquet"
)


pl.Config.set_tbl_rows(2)
display(only_hsf1_lncrna_list)

shape: (37, 51)
┌─────────────┬─────┬───────┬────────────┬───┬────────────┬─────────────┬─────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value    ┆ diff_datase ┆ diff_datase ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---        ┆ t           ┆ t_count     ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]  ┆ ---         ┆ ---         ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆            ┆ list[str]   ┆ u32         ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪════════════╪═════════════╪═════════════╪════════════╡
│ ENST0000065 ┆ 223 ┆ 25    ┆ 158        ┆ … ┆ [0.000862] ┆ ["pair6_GSE ┆ 1           ┆ ["pair6_GS │
│ 4233.1      ┆     ┆       ┆            ┆   ┆            ┆ 209667_hsf1 ┆             ┆ E209667_hs │
│             ┆     ┆       ┆            ┆   ┆            ┆ _polyclonal ┆             ┆ f1_polyclo │
│             ┆     ┆       ┆            ┆   ┆            ┆ _ab_hs_42C_ ┆             ┆ nal_ab_hs_ │
│             ┆     ┆       ┆            ┆   ┆            ┆ 60min"]     ┆             ┆ 42C_60min_ │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ intersecti │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ ng_human-C │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ REv1.2.1.h │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ g38.cre-pe │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ aks.bed"]  │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …          ┆ …           ┆ …           ┆ …          │
│ ENST0000060 ┆ 71  ┆ 27    ┆ 308        ┆ … ┆ [0.000862] ┆ ["pair6_GSE ┆ 1           ┆ ["pair6_GS │
│ 8396.2      ┆     ┆       ┆            ┆   ┆            ┆ 209667_hsf1 ┆             ┆ E209667_hs │
│             ┆     ┆       ┆            ┆   ┆            ┆ _polyclonal ┆             ┆ f1_polyclo │
│             ┆     ┆       ┆            ┆   ┆            ┆ _ab_hs_42C_ ┆             ┆ nal_ab_hs_ │
│             ┆     ┆       ┆            ┆   ┆            ┆ 60min"]     ┆             ┆ 42C_60min_ │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ intersecti │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ ng_human-C │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ REv1.2.1.h │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ g38.cre-pe │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ aks.bed"]  │
└─────────────┴─────┴───────┴────────────┴───┴────────────┴─────────────┴─────────────┴────────────┘

In [30]:
# survey
only_hsf1_lncrna_list_filter = only_hsf1_lncrna_list.filter(
    pl.col("HGNC_ID").is_null()
)

pl.Config.set_tbl_rows(4)
display(only_hsf1_lncrna_list_filter)

shape: (11, 51)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000083 ┆ 203 ┆ 50    ┆ 153        ┆ … ┆ [0.000017,  ┆ ["pair1_GSE ┆ 3          ┆ ["pair1_GS │
│ 9207.1      ┆     ┆       ┆            ┆   ┆ 1.2752e-9,  ┆ 38901_hsf1_ ┆            ┆ E38901_hsf │
│             ┆     ┆       ┆            ┆   ┆ 0.006806]   ┆ mcf10a_hs_4 ┆            ┆ 1_mcf10a_h │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ s_42C_60mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "pair6_GSE2 ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ 09667_hsf1_ ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ polyclonal_ ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ ab_hs_42C_6 ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min", "pai ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆ r8_GSE27067 ┆            ┆ , "pair6_G │
│             ┆     ┆       ┆            ┆   ┆             ┆ 1_hsf1_pc3m ┆            ┆ SE209667_h │
│             ┆     ┆       ┆            ┆   ┆             ┆ _sint_hs_42 ┆            ┆ sf1_polycl │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ onal_ab_hs │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "pair8_GS… │
│ ENST0000069 ┆ 141 ┆ 21    ┆ 244        ┆ … ┆ [0.000862]  ┆ ["pair6_GSE ┆ 1          ┆ ["pair6_GS │
│ 3438.3      ┆     ┆       ┆            ┆   ┆             ┆ 209667_hsf1 ┆            ┆ E209667_hs │
│             ┆     ┆       ┆            ┆   ┆             ┆ _polyclonal ┆            ┆ f1_polyclo │
│             ┆     ┆       ┆            ┆   ┆             ┆ _ab_hs_42C_ ┆            ┆ nal_ab_hs_ │
│             ┆     ┆       ┆            ┆   ┆             ┆ 60min"]     ┆            ┆ 42C_60min_ │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ intersecti │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ng_human-C │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ REv1.2.1.h │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ g38.cre-pe │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ aks.bed"]  │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000082 ┆ 97  ┆ 42    ┆ 267        ┆ … ┆ [0.00031]   ┆ ["pair6_GSE ┆ 1          ┆ ["pair6_GS │
│ 4599.1      ┆     ┆       ┆            ┆   ┆             ┆ 209667_hsf1 ┆            ┆ E209667_hs │
│             ┆     ┆       ┆            ┆   ┆             ┆ _polyclonal ┆            ┆ f1_polyclo │
│             ┆     ┆       ┆            ┆   ┆             ┆ _ab_hs_42C_ ┆            ┆ nal_ab_hs_ │
│             ┆     ┆       ┆            ┆   ┆             ┆ 60min"]     ┆            ┆ 42C_60min_ │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ intersecti │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ng_human-C │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ REv1.2.1.h │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ g38.cre-pe │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ aks.bed"]  │
│ ENST0000082 ┆ 97  ┆ 42    ┆ 267        ┆ … ┆ [0.00031]   ┆ ["pair6_GSE ┆ 1          ┆ ["pair6_GS │
│ 4599.1      ┆     ┆       ┆            ┆   ┆             ┆ 209667_hsf1 ┆            ┆ E209667_hs │
│             ┆     ┆       ┆            ┆   ┆             ┆ _polyclonal ┆            ┆ f1_polyclo │
│             ┆     ┆       ┆            ┆   ┆             ┆ _ab_hs_42C_ ┆            ┆ nal_ab_hs_ │
│             ┆     ┆       ┆            ┆   ┆             ┆ 60min"]     ┆            ┆ 42C_60min_ │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ intersecti │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ng_human-C │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ REv1.2.1.h │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ g38.cre-pe │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ aks.bed"]  │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘