# GEO Metadata validated and modified process (Gemini-2.0-flash FALSE & Infered has control FALSE)

- ヒトの熱ストレスに関連するRNA-Seqにおいて、Gemini-2.0-flash の判断と自分の判断の結果、解析に使用するに値するデータのメタデータを整理するnotebook
- 整理する際、なぜこのようなデータフレームの処理をするのかについても記載する
- `geofetch`から取得したデータと`iseq`から取得したデータ
- [../GenAI_validate/geo_metadata_genai_validation_false_no_control.tsv](../../Data/curation/GenAI_validate/20250504/geo_metadata_genai_validation_false_no_control.tsv) に分類されたものについてここに記載する

- **いくつかのデータは使用できそうなので収集しておく**

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_cols(100)
pl.Config.set_tbl_rows(4)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera",
    "tax_lineage",
    "bam_md5",
    "fastq_md5",
    "sra_md5"
]

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1. GSE124510 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-05-04
- [Proteasome inhibitor-induced modulation reveals the spliceosome as a specific therapeutic vulnerability in multiple myeloma](https://doi.org/10.1038/s41467-020-15521-4)
- `bortezomib`などのデータをフィルタリングし、コントロールと `42C for 4 h`のデータを収集

In [4]:
ID = "GSE124510"

GSE124510_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "RNA-Seq")
).filter(
    (pl.col("sample_title").str.contains(r'MM.1S 0 h')) |
    (pl.col("sample_title").str.contains(r'MM.1S heat shock'))
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Hyper Prep RNA sequencing kit").alias("rna_library"), # add rna_library column from GEO webpage (KAPA Biosystems)
    pl.lit("https://doi.org/10.1038/s41467-020-15521-4").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("240 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
    pl.lit("MM.1S").alias("cell_line")

).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE124510 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE124510_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE124510_iseq_filtered = GSE124510[[s.name for s in GSE124510 if not (s.null_count() == GSE124510.height)]]

GSE124510_combined = GSE124510_PEP.join(
    GSE124510_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE124510_combined = GSE124510_combined[[s.name for s in GSE124510_combined if not (s.null_count() == GSE124510_combined.height)]]

if GSE124510_combined is not None:
    GSE124510_combined.write_csv(
        "../../Data/metadata/metadata_modified/GSE124510_modified_metadata.tsv",
        separator='\t'
    )

# display(GSE124510_combined)

In [5]:
defined_pairs_gse124510 = [
    ("SRR10761036", "SRR10761033"), # MM.1S heat shock 4 h mRNA replicate 1 vs MM.1S 0 h control mRNA replicate 1
    ("SRR10761037", "SRR10761034"), # MM.1S heat shock 4 h mRNA replicate 2 vs MM.1S 0 h control mRNA replicate 2
    ("SRR10761038", "SRR10761035")  # MM.1S heat shock 4 h mRNA replicate 3 vs MM.1S 0 h control mRNA replicate 3
]

paired_metadata_df_gse124510 = create_paired_metadata(
    combined_df=GSE124510_combined,
    defined_sample_pairs=defined_pairs_gse124510,
    sample_id_column_name="accession" # default value, but specified to clarify
)


if paired_metadata_df_gse124510 is not None:
    paired_metadata_df_gse124510.write_csv(
        "../../Data/metadata/metadata_paired/GSE124510_paired_metadata.tsv",
        separator = '\t'
    )
    
    display(paired_metadata_df_gse124510)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 86)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ exp ┆ tim ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ eri ┆ epo ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ men ┆ int ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ t   ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ --- ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ ion ┆ _id ┆ nam ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ str ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ --- ┆ --- ┆ e   ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ l_c ┆ --- ┆ str ┆ str ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆     ┆     ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ mm_ ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ MM. ┆ GSM ┆ Pub ┆ Dec ┆ Feb ┆ SRA ┆ 1   ┆ MM. ┆ Hom ┆ 960 ┆ For ┆ Hea ┆ pol ┆ jun ┆ GPL ┆ Hec ┆ Wii ┆ Lab ┆ Uni ┆ 185 ┆ San ┆ CAL ┆ 941 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ MM. ┆ hea ┆ 4 h ┆ UCS ┆ "de ┆ SAM ┆ Hyp ┆ htt ┆ 42  ┆ 240 ┆ 37  ┆ SRR ┆ Ill ┆ Pro ┆ SRA ┆ cDN ┆ 202 ┆ 338 ┆ 235 ┆ ILL ┆ Gen ┆ MM. ┆ SRP ┆ 367 ┆ Pro ┆ MM. ┆ Ill ┆ Ill ┆ MM. ┆ 111 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ GSM ┆ GEO ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 107 ┆ 107 ┆ 1s_ ┆ A   ┆ o   ┆ RED ┆     ┆ 107 ┆ 743 ┆ 1S  ┆ 423 ┆ lic ┆ 23  ┆ 18  ┆     ┆     ┆ 1S  ┆ o   ┆ 6   ┆ hea ┆ t   ┆ yA  ┆ cba ┆ 203 ┆ tor ┆ ta  ┆ ora ┆ ver ┆ Ber ┆ Fra ┆ IFO ┆ 07  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 423 ┆ E   ┆ 124 ┆     ┆ 743 ┆ 1S  ┆ t   ┆ vs  ┆ C   ┆ lin ┆ N13 ┆ er  ┆ ps: ┆ C   ┆ min ┆ C   ┆ 107 ┆ umi ┆ tea ┆ 827 ┆ A   ┆ 0-1 ┆ 713 ┆ 234 ┆ UMI ┆ eri ┆ 1S  ┆ 174 ┆ 714 ┆ tea ┆ 1S  ┆ umi ┆ umi ┆ 1S  ┆ 049 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 423 ┆ 423 ┆ al  ┆ 423 ┆     ┆ 0-1 ┆ NA5 ┆ 588 ┆ 0-1 ┆ 124 │
│ 610 ┆ 610 ┆ hea ┆     ┆ sap ┆     ┆     ┆ 610 ┆ 525 ┆ hea ┆ 170 ┆ on  ┆ 201 ┆ 202 ┆     ┆     ┆ mye ┆ sap ┆     ┆ t   ┆ sho ┆ RNA ┆ se_ ┆ 01  ┆ ,Ha ┆ Lab ┆ tor ┆ sit ┆ ry  ┆ nci ┆ RNI ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 170 ┆     ┆ 510 ┆     ┆ 525 ┆     ┆ sho ┆ 0 h ┆ hg1 ┆ k_c ┆ 673 ┆ Pre ┆ //d ┆     ┆ .   ┆ (in ┆ 610 ┆ na  ┆ som ┆ 993 ┆     ┆ 0-2 ┆ 167 ┆ 831 ┆ NA  ┆ c   ┆ hea ┆ 924 ┆ 29  ┆ som ┆ hea ┆ na  ┆ na  ┆     ┆ 715 ┆ q   ┆ RIP ┆     ┆     ┆ 170 ┆ 170 ┆ RNA ┆ 170 ┆     ┆ 0-2 ┆ 122 ┆ 042 ┆ 0-2 ┆ 510 │
│ 36  ┆ 33  ┆ t_s ┆     ┆ ien ┆     ┆     ┆ 36  ┆ 3   ┆ t   ┆ 7   ┆ Feb ┆ 9   ┆ 0   ┆     ┆     ┆ lom ┆ ien ┆     ┆ sho ┆ ck  ┆     ┆ tab ┆     ┆ n-L ┆     ┆ y   ┆ y   ┆ St, ┆ sco ┆ A   ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 7   ┆     ┆     ┆     ┆ 3   ┆     ┆ ck  ┆ (un ┆ 9   ┆ 2g_ ┆ 568 ┆ p   ┆ oi. ┆     ┆     ┆ fer ┆ 36  ┆ HiS ┆ e   ┆     ┆     ┆ 9   ┆ 0   ┆ 9;2 ┆     ┆     ┆ t   ┆     ┆ vs  ┆ e   ┆ t   ┆ HiS ┆ HiS ┆     ┆ 58  ┆     ┆ TOM ┆     ┆     ┆ 7   ┆ 7_r ┆ was ┆ 7   ┆     ┆ 9   ┆ 68  ┆ 6   ┆ 9   ┆     │
│     ┆     ┆ hoc ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ sho ┆ vs  ┆ 18  ┆     ┆     ┆     ┆     ┆ a   ┆ s   ┆     ┆ ck  ┆ exp ┆     ┆ les ┆     ┆ i,H ┆     ┆ Med ┆ of  ┆ Ste ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ ind ┆ tre ┆     ┆ fw5 ┆ vs  ┆ RNA ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ inh ┆     ┆     ┆     ┆ vs  ┆ 441 ┆     ┆     ┆ sho ┆     ┆ 402 ┆ inh ┆ sho ┆ eq  ┆ eq  ┆     ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ext ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ k_4 ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ ck  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ sam ┆ eri ┆     ┆ _DM ┆     ┆ uan ┆     ┆ ici ┆ Cal ┆ 290 ┆     ┆     ┆     ┆     ┆ 400 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ uce ┆ ate ┆     ┆ rv_ ┆ SAM ┆ seq ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 400 ┆ ibi ┆     ┆     ┆     ┆ 372 ┆ 959 ┆     ┆     ┆ ck  ┆     ┆ 796 ┆ ibi ┆ ck  ┆ 400 ┆ 400 ┆     ┆ 121 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ rac ┆ GSM ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ _h_ ┆     ┆     ┆     ┆     ┆ 107 ┆ 743 ┆ 4 h ┆ 423 ┆ 0   ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ ple ┆ men ┆     ┆ SO_ ┆     ┆ g   ┆     ┆ ne  ┆ ifo ┆ /Rm ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 423 ┆     ┆     ┆     ┆ 743 ┆     ┆ d   ┆ d)  ┆     ┆ xpr ┆ N13 ┆ uen ┆ .10 ┆     ┆     ┆     ┆ 107 ┆ 0   ┆ tor ┆     ┆     ┆     ┆ 416 ┆ 142 ┆     ┆     ┆ 4 h ┆     ┆ 39  ┆ tor ┆ 4 h ┆ 0   ┆ 0   ┆     ┆ 644 ┆     ┆     ┆     ┆     ┆ 423 ┆ GSM ┆ ted ┆ 423 ┆     ┆     ┆     ┆ 588 ┆     ┆     │
│     ┆     ┆ mrn ┆     ┆     ┆     ┆     ┆ 610 ┆ 525 ┆ mRN ┆ 170 ┆     ┆     ┆     ┆     ┆     ┆ lin ┆     ┆     ┆ s,  ┆ t   ┆     ┆ vs_ ┆     ┆     ┆     ┆     ┆ rni ┆ 241 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 170 ┆     ┆     ┆     ┆ 525 ┆     ┆ int ┆     ┆     ┆ .tx ┆ 673 ┆ cin ┆ 38/ ┆     ┆     ┆     ┆ 610 ┆ seq ┆ -in ┆     ┆     ┆     ┆ 615 ┆ vs  ┆     ┆     ┆ mRN ┆     ┆     ┆ -in ┆ mRN ┆     ┆ seq ┆     ┆ 509 ┆     ┆     ┆     ┆     ┆ 170 ┆ 423 ┆ by  ┆ 170 ┆     ┆     ┆     ┆ 042 ┆     ┆     │
│     ┆     ┆ a_r ┆     ┆     ┆     ┆     ┆ 33  ┆ 0   ┆ A   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ MM. ┆ and ┆     ┆ hea ┆     ┆     ┆     ┆     ┆ a   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ 0   ┆     ┆ ron ┆     ┆     ┆ t"  ┆ 597 ┆ g   ┆ s41 ┆     ┆     ┆     ┆ 33  ┆ uen ┆ duc ┆     ┆     ┆     ┆ 9   ┆ 259 ┆     ┆     ┆ A   ┆     ┆     ┆ duc ┆ A   ┆     ┆ uen ┆     ┆ 78  ┆     ┆     ┆     ┆     ┆ 4   ┆ 170 ┆ sta ┆ 4   ┆     ┆     ┆     ┆ 3   ┆     ┆     │
│     ┆     ┆ epl ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1S  ┆ Tim ┆     ┆ tsh ┆     ┆     ┆     ┆     ┆ San ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ret ┆     ┆     ┆ in- ┆     ┆ kit ┆ 467 ┆     ┆     ┆     ┆     ┆ cin ┆ ed  ┆     ┆     ┆     ┆     ┆ 060 ┆     ┆     ┆ rep ┆     ┆     ┆ ed  ┆ rep ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4_r ┆ nda ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ica ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cul ┆ eco ┆     ┆ ock ┆     ┆     ┆     ┆     ┆ Fra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ent ┆     ┆     ┆ hou ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆ g:  ┆ mod ┆     ┆     ┆     ┆     ┆ 912 ┆     ┆     ┆ lic ┆     ┆     ┆ mod ┆ lic ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ rd  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ te_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tur ┆ urs ┆     ┆ _jc ┆     ┆     ┆     ┆     ┆ nci ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ se  ┆     ┆     ┆ 0-1 ┆     ┆     ┆     ┆     ┆ GSM ┆ ula ┆     ┆     ┆     ┆     ┆ 6;2 ┆     ┆     ┆ ate ┆     ┆     ┆ ula ┆ ate ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆ e   ┆     ┆ n27 ┆     ┆     ┆     ┆     ┆ sco ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C++ ┆     ┆     ┆ 552 ┆     ┆     ┆     ┆     ┆ 423 ┆ tio ┆     ┆     ┆     ┆     ┆ 715 ┆     ┆     ┆ 1   ┆     ┆     ┆ tio ┆ 1   ┆     ┆ 423 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆ MM. ┆     ┆ 2.t ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ scr ┆     ┆     ┆ 1-4 ┆     ┆     ┆     ┆     ┆ 170 ┆ n   ┆     ┆     ┆     ┆     ┆ 541 ┆     ┆     ┆ vs  ┆     ┆     ┆ n   ┆ vs  ┆     ┆ 170 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ mm_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ MM. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ 1S  ┆     ┆ sv  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ipt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7:  ┆ rev ┆     ┆     ┆     ┆     ┆ 135 ┆     ┆     ┆ MM. ┆     ┆     ┆ rev ┆ MM. ┆     ┆ 7:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1s_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1S  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inc ┆ cul ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MM. ┆ eal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1S  ┆     ┆     ┆ eal ┆ 1S  ┆     ┆ MM. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0_h ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0 h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uba ┆ tur ┆     ┆ jun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ out ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1S  ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0 h ┆     ┆     ┆ s   ┆ 0 h ┆     ┆ 1S  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _co ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆ es  ┆     ┆ cba ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ put ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆ the ┆ con ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆ wer ┆     ┆ se_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆ spl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆ spl ┆ tro ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eas ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ol_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42C ┆ e   ┆     ┆ tab ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆ ice ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ ice ┆ l   ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ mrn ┆     ┆     ┆     ┆     ┆     ┆     ┆ mRN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ gro ┆     ┆ les ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ UCS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆ oso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mRN ┆     ┆     ┆ oso ┆ mRN ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Qia ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. GSE194098 (SINGLE,PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-04
- [HSF2 cooperates with HSF1 to drive a transcriptional program critical for the malignant state](https://doi.org/10.1126/sciadv.abj6526)
- HSF1,2のKDなどのデータが含まれている
- 熱ショックが加えられているデータを発見！
- フィルタリングしてデータを収集
- `we performed RNA-seq in our HSF2 knockout MDA-MB-231 cell lines grown either at 37°C or following a 42°C heat shock along with wild-type and HSF1 knockout control lines.`という記述あり
- Supplementary Figure 7. に以下のような記載がある
- `Gene expression changes of heat shock (HS) treated (42°C, 1 hour) MDA-MB-231 cells with either HSF1 (sgHSF1) or HSF2 (sgHSF2) knockout, expressed as log2 fold-change (L2FC) relative to non-targeting sgRNA controls without heat shock.`

In [6]:
GSE194098_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE194098/GSE194098_PEP/GSE194098_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "RNA-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).filter(
    (pl.col("sample_library_strategy") == "RNA-Seq") &
    ((pl.col("sample_title").str.contains(r'MDAMB231_sgHSF1_Control_')) |
     (pl.col("sample_title").str.contains(r'MDAMB231_sgHSF2_Control_')) |
     (pl.col("sample_title").str.contains(r'MDAMB231_sgHSF1_HeatShock_')) |
     (pl.col("sample_title").str.contains(r'MDAMB231_sgHSF2_HeatShock_')) |
     (pl.col("sample_title").str.contains(r'MDAMB231_WT_HeatShock_')) |
     (pl.col("sample_title").str.contains(r'MDAMB231_WT_Control_'))
     )
).with_columns(
    pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession"),
    pl.lit("Lexogen QuantSeq FWD Kit").alias("rna_library"), # add rna_library column from GEO webpage (Lexogen)
    pl.lit("https://doi.org/10.1126/sciadv.abj6526").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE194098 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE194098_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE194098_iseq_filtered = GSE194098[[s.name for s in GSE194098 if not (s.null_count() == GSE194098.height)]]

GSE194098_combined = GSE194098_PEP.join(
    GSE194098_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE194098_combined = GSE194098_combined[[s.name for s in GSE194098_combined if not (s.null_count() == GSE194098_combined.height)]]

if GSE194098_combined is not None:
    GSE194098_combined.write_csv(
        "../../Data/metadata/metadata_modified/GSE194098_modified_metadata.tsv",
        separator='\t'
    )

# display(GSE194098_combined)

In [7]:
defined_pairs_gse194098 = [
   ("SRR17682123", "SRR17682125"), # MDAMB231_sgHSF1_HeatShock_A vs MDAMB231_sgHSF1_Control_A
   ("SRR17682122", "SRR17682124"), # MDAMB231_sgHSF1_HeatShock_B vs MDAMB231_sgHSF1_Control_B
   ("SRR17682203", "SRR17682121"), # MDAMB231_sgHSF2_HeatShock_A vs MDAMB231_sgHSF2_Control_A
   ("SRR17682201", "SRR17682120"), # MDAMB231_sgHSF2_HeatShock_B vs MDAMB231_sgHSF2_Control_B
   ("SRR17682198", "SRR17682200"), # MDAMB231_WT_HeatShock_A vs MDAMB231_WT_Control_A
   ("SRR17682197", "SRR17682199")  # MDAMB231_WT_HeatShock_B vs MDAMB231_WT_Control_B
]

paired_metadata_df_gse194098 = create_paired_metadata(
    combined_df=GSE194098_combined,
    defined_sample_pairs=defined_pairs_gse194098,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse194098 is not None:
    paired_metadata_df_gse194098.write_csv(
        "../../Data/metadata/metadata_paired/GSE194098_paired_metadata.tsv",
        separator = '\t'
    )

    display(paired_metadata_df_gse194098)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 80)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ vec ┆ sir ┆ ant ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ tor ┆ na_ ┆ ibo ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ --- ┆ sgr ┆ dy  ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ str ┆ na  ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆     ┆ --- ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ ion ┆ _id ┆ nam ┆ ema ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆ str ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ --- ┆ e   ┆ il  ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ str ┆ --- ┆ --- ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆     ┆ str ┆ str ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ mda ┆ MDA ┆ GSM ┆ Pub ┆ Jan ┆ Mar ┆ SRA ┆ 1   ┆ can ┆ Hom ┆ 960 ┆ Hea ┆ Cel ┆ tot ┆ Lex ┆ MDA ┆ GPL ┆ Mar ┆ men ┆ Bio ┆ 303 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ MDA ┆ N/A ┆ sgH ┆ N/A ┆ hg3 ┆ SAM ┆ Lex ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Nex ┆ HSF ┆ SRA ┆ cDN ┆ 202 ┆ 135 ┆ 167 ┆ ILL ┆ Gen ┆ MDA ┆ SRP ┆ 389 ┆ HSF ┆ MDA ┆ Nex ┆ Nex ┆ 288 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Lex ┆ GSM ┆ MDA ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 176 ┆ 176 ┆ mb2 ┆ MB2 ┆ 582 ┆ lic ┆ 20  ┆ 15  ┆     ┆     ┆ cer ┆ o   ┆ 6   ┆ tSh ┆ ls  ┆ al  ┆ oge ┆ MB2 ┆ 185 ┆ c,, ┆ dil ┆ che ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 582 ┆ E   ┆ 194 ┆     ┆ 138 ┆ MB2 ┆     ┆ SF1 ┆     ┆ 8   ┆ N25 ┆ oge ┆ ps: ┆ C   ┆ min ┆ C   ┆ 176 ┆ tSe ┆ 2   ┆ 135 ┆ A   ┆ 2-0 ┆ 030 ┆ 017 ┆ UMI ┆ eri ┆ MB2 ┆ 356 ┆ 307 ┆ 2   ┆ MB2 ┆ tSe ┆ tSe ┆ 681 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 582 ┆ 582 ┆ oge ┆ 582 ┆ MB2 ┆ 582 ┆ 2-0 ┆ NA7 ┆ 117 ┆ 2-0 ┆ 194 │
│ 821 ┆ 821 ┆ 31_ ┆ 31_ ┆ 805 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ cel ┆ sap ┆     ┆ ock ┆ wer ┆ RNA ┆ n   ┆ 31_ ┆ 73  ┆ Men ┆ lo@ ┆ mis ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 805 ┆     ┆ 098 ┆     ┆ 454 ┆ 31  ┆     ┆ .1  ┆     ┆     ┆ 144 ┆ n   ┆ //d ┆     ┆ .   ┆     ┆ 821 ┆ q   ┆ coo ┆ 944 ┆     ┆ 3-1 ┆ 960 ┆ 520 ┆ NA  ┆ c   ┆ 31_ ┆ 009 ┆ 0   ┆ coo ┆ 31_ ┆ q   ┆ q   ┆ 297 ┆ q   ┆ RIP ┆     ┆     ┆ 805 ┆ 805 ┆ n   ┆ 805 ┆ 31  ┆ 805 ┆ 3-1 ┆ 990 ┆ 225 ┆ 3-1 ┆ 098 │
│ 23  ┆ 25  ┆ sgh ┆ sgH ┆ 6   ┆ Mar ┆ 2   ┆ 2   ┆     ┆     ┆ l   ┆ ien ┆     ┆ ,   ┆ e   ┆     ┆ 3'  ┆ HS_ ┆     ┆ dil ┆ nor ┆ try ┆ eri ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 6   ┆     ┆     ┆     ┆ 34  ┆     ┆     ┆     ┆     ┆     ┆ 533 ┆ Qua ┆ oi. ┆     ┆     ┆     ┆ 23  ┆ 500 ┆ per ┆ 5   ┆     ┆ 8   ┆ vs  ┆ vs  ┆     ┆     ┆ sgH ┆     ┆ vs  ┆ per ┆ sgH ┆ 500 ┆ 500 ┆ vs  ┆     ┆ TOM ┆     ┆     ┆ 6   ┆ 6_r ┆ 3'  ┆ 6_r ┆     ┆ 6   ┆ 8   ┆ 44  ┆ 50  ┆ 8   ┆     │
│     ┆     ┆ sf1 ┆ SF1 ┆ vs  ┆ 15  ┆     ┆     ┆     ┆     ┆ lin ┆ s   ┆     ┆ See ┆ gro ┆     ┆ Qua ┆ hts ┆     ┆ lo  ┆ thw ┆ and ┆ or  ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ ntS ┆ org ┆     ┆     ┆     ┆ vs  ┆ seq ┆ ate ┆     ┆     ┆     ┆ 118 ┆ 146 ┆     ┆     ┆ SF1 ┆     ┆ 341 ┆ ate ┆ SF1 ┆     ┆ seq ┆ 253 ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ Qua ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ _he ┆ _He ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ sam ┆ wn  ┆     ┆ ntS ┆ eq. ┆     ┆     ┆ est ┆ Mol ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ eq  ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ uen ┆ s   ┆     ┆     ┆     ┆ 141 ┆ 770 ┆     ┆     ┆ _He ┆     ┆ 747 ┆ s   ┆ _He ┆     ┆ uen ┆ 739 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ ntS ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ ats ┆ atS ┆ 582 ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆ at  ┆     ┆ eq  ┆ all ┆     ┆     ┆ ern ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 582 ┆     ┆     ┆     ┆ 138 ┆     ┆     ┆     ┆     ┆     ┆ N25 ┆ FWD ┆ .11 ┆     ┆     ┆     ┆ 176 ┆ cin ┆ wit ┆     ┆     ┆     ┆ 619 ┆ 862 ┆     ┆     ┆ atS ┆     ┆ 6   ┆ wit ┆ atS ┆     ┆ cin ┆ 045 ┆     ┆     ┆     ┆     ┆ 582 ┆ GSM ┆ eq  ┆ GSM ┆     ┆ 582 ┆     ┆     ┆ 117 ┆     ┆     │
│     ┆     ┆ hoc ┆ hoc ┆ 805 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sec ┆ 37° ┆     ┆ FWD ┆ .co ┆     ┆     ┆ .ed ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 805 ┆     ┆     ┆     ┆ 454 ┆     ┆     ┆     ┆     ┆     ┆ 144 ┆ Kit ┆ 26/ ┆     ┆     ┆     ┆ 821 ┆ g:  ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hoc ┆     ┆     ┆ h   ┆ hoc ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ 805 ┆ 582 ┆ FWD ┆ 582 ┆     ┆ 805 ┆     ┆     ┆ 225 ┆     ┆     │
│     ┆     ┆ k_a ┆ k_A ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆ C   ┆     ┆ for ┆ unt ┆     ┆     ┆ u   ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ 32  ┆     ┆     ┆     ┆     ┆     ┆ 535 ┆     ┆ sci ┆     ┆     ┆     ┆ 25  ┆ GSM ┆ HSF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k_A ┆     ┆     ┆ HSF ┆ k_A ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 805 ┆ for ┆ 805 ┆     ┆ 4   ┆     ┆     ┆ 48  ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ and ┆     ┆ Ill ┆ s.t ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ adv ┆     ┆     ┆     ┆     ┆ 582 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ 1   ┆ vs  ┆     ┆ 582 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4_r ┆ Ill ┆ 4_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ mda ┆ MDA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ 5%  ┆     ┆ umi ┆ xt  ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ab ┆     ┆     ┆     ┆     ┆ 805 ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MDA ┆     ┆     ┆ to  ┆ MDA ┆     ┆ 805 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ umi ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ mb2 ┆ MB2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆ CO2 ┆     ┆ na, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ j65 ┆     ┆     ┆     ┆     ┆ 6:  ┆ dri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MB2 ┆     ┆     ┆ dri ┆ MB2 ┆     ┆ 6:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 31_ ┆ 31_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atm ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆ MDA ┆ ve  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 31_ ┆     ┆     ┆ ve  ┆ 31_ ┆     ┆ MDA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ sgh ┆ sgH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ent ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MB2 ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sgH ┆     ┆     ┆ a   ┆ sgH ┆     ┆ MB2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ sf1 ┆ SF1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 31_ ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SF1 ┆     ┆     ┆ tra ┆ SF1 ┆     ┆ 31_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _co ┆ _Co ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Con ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sgH ┆ nsc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Co ┆     ┆     ┆ nsc ┆ _Co ┆     ┆ sgH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ntr ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SF1 ┆ rip ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆ rip ┆ ntr ┆     ┆ SF1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ol_ ┆ ol_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _He ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol_ ┆     ┆     ┆ tio ┆ ol_ ┆     ┆ _He ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ a   ┆ A   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ See ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atS ┆ nal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A   ┆     ┆     ┆ nal ┆ A   ┆     ┆ atS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sam ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hoc ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆ hoc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆ Qia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k_A ┆ gra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gra ┆     ┆     ┆ k_A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Qia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sec ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ RNe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ cri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cri ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ tic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tic ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atm ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE127890 (SINGLE) Nanopore

- validate date 2025-05-04
- [Native molecule sequencing by nano-ID reveals synthesis and stability of RNA isoforms](https://doi.org/10.1101/gr.257857.119)
- 以前の研究でも使用しているnanoporeのデータで、RNAのisoformを検出するための手法 nano-ID (nanopore sequencing–based isoform dynamics) を開発した論文
- `To show the advantages of nano-ID, we subjected human K562 cells to heat shock (42°C) for 60 min in the presence of 5EU (5EU 60 min HS) (Fig. 4A).`
- 上記のような記述に関するデータを収集
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

#### GSE234617 (SINGLE) NO DOWLOAD

- validate date 2025-05-06
- [AFF4 globally affects the release of paused RNA polymerase II in HEL cells](https://pubmed.ncbi.nlm.nih.gov/37609817/)
- この論文の全文にアクセスすることができなかった
- また、メタデータを見てもこのデータには熱ストレスではなく、AFF4をノックダウンしているデータが見られたため、今回はこの論文は収集しない

In [8]:
# GSE234617_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE234617/GSE234617_PEP/GSE234617_PEP_raw.csv",
#     separator=','
# )

# display(GSE234617_PEP)

#### GSE240883 (SINGLE) NO DOWNLOAD

- validate date 2025-05-04
- [Phosphorylation of a nuclear condensate regulates cohesion and mRNA retention](https://doi.org/10.1038/s41467-024-55469-3)
- 熱ストレスには特に関連していないデータのみだったので、今回は解析に使用しない

In [9]:
# GSE240883_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE240883/GSE240883_PEP/GSE240883_PEP_raw.csv",
#     separator=','
# )

# display(GSE240883_PEP)

#### GSE262079 (SINGLE) NO DOWNLOAD

- validate date 2025-05-06
- [First-in-class mitogen-activated protein kinase (MAPK) p38α: MAPK-activated protein kinase 2 dual signal modulator with anti-inflammatory and endothelial-stabilizing properties](https://doi.org/10.1124/jpet.124.002281)
- hyperthermia (FRH (febrile-range hyperthermia)) に関する研究
- `p38 inhibitor, SB203580`処理のデータと、`SF7044(GEn1124)/TNFa` 処理のデータ、`UM101`処理のデータ、DMSO処理のデータが含まれている
- hyperthermiaに関するデータは含まれていないので今回は収集しない

In [10]:
# GSE262079_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE262079/GSE262079_PEP/GSE262079_PEP_raw.csv",
#     separator=','
# )

# display(GSE262079_PEP)

#### GSE240891 (SINGLE) NO DOWNLOAD

- validate date 2025-05-06
- [Phosphorylation of a nuclear condensate regulates cohesion and mRNA retention](https://doi.org/10.1038/s41467-024-55469-3)
- 熱ショックに関する実験は行われているが、RNA-seqに関するデータ,このGEOのデータは`biotinylated RNA`に関するデータ
- 今回は収集しない

In [11]:
# GSE240891_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE240891/GSE240891_PEP/GSE240891_PEP_raw.csv",
#     separator=','
# )

# display(GSE240891_PEP)

#### GSE137591 (SINGLE) NO DOWNLOAD

- validate date 2025-05−06
- [HSF1 Activation Can Restrict HIV Replication](https://doi.org/10.1021/acsinfecdis.0c00166)
- `single-colony human T lymphocyte (CEM) cell line` と `constitutively active variant of HSF1 (cHSF1)` と`18h 1 ug/ml Doxycycline (dox) treatment`に関連するデータ
- 論文中では熱ショック処理実験をしているが、GEOに登録されているデータには熱ショック関連のデータがない
- 今回は収集しない

In [12]:
# GSE137591_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE137591/GSE137591_PEP/GSE137591_PEP_raw.csv",
#     separator=','
# )

# display(GSE137591_PEP)

#### GSE202189 (SINGLE) NO DOWNLOAD

- validate date 2025-05-06
- [SPT6 functions in transcriptional pause/release via PAF1C recruitment](https://doi.org/10.1016/j.molcel.2022.06.037)
- SPT6 と [AID (activation-induced cytidine deaminase)](https://www.yodosha.co.jp/jikkenigaku/keyword/index.html?id=1821) を導入しているデータ
- 論文中では熱ショックをかけている記述があるが、GEOに登録されているデータではこのデータがないため、今回は収集しない

In [13]:
# GSE202189_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE202189/GSE202189_PEP/GSE202189_PEP_raw.csv",
#     separator=','
# )

# display(GSE202189_PEP)

#### GSE208005 （SINGLE） NO DOWNLOAD

- validation date: 2025-05-06
- [Co-targeting HSP90 alpha and CDK7 overcomes resistance against HSP90 inhibitors in BCR-ABL1+ leukemia cells](https://doi.org/10.1038/s41419-023-06337-3)
- HSP90のノックアウトや、阻害剤のPU-H71(Zelavespib)などが処理されているデータ
- 熱ストレスに関するデータは含まれていないため、今回は収集しない

In [14]:
# GSE208005_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE208005/GSE208005_PEP/GSE208005_PEP_raw.csv",
#     separator=','
# )

# display(GSE208005_PEP)

### GSE202187 (SINGLE) PRO-seq

- validation date: 2025-05-06
- [SPT6 functions in transcriptional pause/release via PAF1C recruitment](https://doi.org/10.1016/j.molcel.2022.06.037)
- GSE202189に関連するデータで、PRO-seqのデータ
- PRO-seqとSPT6に対するauxin-inducible degradation (AID) systemが行われている論文
- 42℃, 60min.
- nacsent RNAのデータが使えるかわからないが、念の為収集
- 処理を[12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)に移動

#### GSE181161 (SINGLE) NO DOWNLOAD

- validation date: 2025-05−06
- [Quantifying RNA synthesis at rate-limiting steps of transcription using nascent RNA-sequencing data](https://doi.org/10.1016/j.xpro.2021.101036)
- PRO-seqのデータで、conditionカラムをみると `Unstressed (no heat shock)`のデータのみ含まれているため、今回は収集しない

In [15]:
# GSE181161_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE181161/GSE181161_PEP/GSE181161_PEP_raw.csv",
#     separator=','
# )

# display(GSE181161_PEP)

#### GSE165211 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-06
- [Cancer-Associated Fibroblasts Promote Aggressive Gastric Cancer Phenotypes via Heat Shock Factor 1–Mediated Secretion of Extracellular Vesicles](https://doi.org/10.1158/0008-5472.CAN-20-2756)
- HSF1に関連した論文だが、熱ショックに関連したデータは含まれていなかったため、今回は収集しない

In [16]:
# GSE165211_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE165211/GSE165211_PEP/GSE165211_PEP_raw.csv",
#     separator=','
# )

# display(GSE165211_PEP)

#### GSE164717 (SINGLE) NO DOWNLOAD

- validation date 2025-05−06
- [Inhibition of HSP90 as a Strategy to Radiosensitize Glioblastoma: Targeting the DNA Damage Response and Beyond](https://doi.org/10.3389/fonc.2021.612354)
- `The human GBM cell lines LN229 and T98G` に関して、HSP90 inhibition 処理のデータをかけているデータ
- 今回はこのデータを収集しない

In [17]:
# GSE164717_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE164717/GSE164717_PEP/GSE164717_PEP_raw.csv",
#     separator=','
# )

# display(GSE164717_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. GSE180253 (SINGLE) RNA-seq

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-06
- [m6Am-seq reveals the dynamic m6Am methylation in the human transcriptome](https://doi.org/10.1038/s41467-021-25105-5)
- m6Am-seq を行うための、`Input` として使用されている RNA-seq データを収集する
- `heat_shock_` と `Untreated_` のデータを念の為収集する
- bulk RNA-seq以外のデータの処理を[./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に移動

In [18]:
GSE180253_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE180253/GSE180253_PEP/GSE180253_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "RNA-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).filter(
    ((pl.col("sample_title").str.contains(r'heat_shock_')) | 
     (pl.col("sample_title").str.contains(r'Untreated_'))) & # remove HSF1 knockdown data
    ~(pl.col("sample_title").str.contains(r'Hypoxia_')) # remove HSF1 knockdown data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("SMARTer® Stranded Total RNA-Seq Kit v2—Pico Input Mammalian (634413, Takara – Clontech, Japan)").alias("rna_library"), # add rna_library column from GEO page
    pl.lit("https://doi.org/10.1038/s41467-021-25105-5").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE180253 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE180253_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE180253_iseq_filtered = GSE180253[[s.name for s in GSE180253 if not (s.null_count() == GSE180253.height)]]


GSE180253_combined_rna_seq = GSE180253_PEP.join(
    GSE180253_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE180253_combined_rna_seq = GSE180253_combined_rna_seq[[s.name for s in GSE180253_combined_rna_seq if not (s.null_count() == GSE180253_combined_rna_seq.height)]]

GSE180253_combined_rna_seq.write_csv(
    "../../Data/metadata/metadata_modified/GSE180253_rna_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE180253_combined_rna_seq)

In [19]:
# RNA-seq
defined_pairs_gse180253_rna_seq = [
    ("SRR15177495", "SRR15177509") # heat_shock_input vs Untreated_input
]

paired_metadata_df_gse180253_rna_seq = create_paired_metadata(
    combined_df=GSE180253_combined_rna_seq, 
    defined_sample_pairs=defined_pairs_gse180253_rna_seq,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse180253_rna_seq is not None:
    paired_metadata_df_gse180253_rna_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE180253_rna_seq_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse180253_rna_seq)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 85)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hea ┆ cDN ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ hea ┆ GSM ┆ Pub ┆ Jul ┆ Jul ┆ SRA ┆ 1   ┆ HEK ┆ Hom ┆ 960 ┆ pol ┆ RNA ┆ GPL ┆ Kai ┆ li_ ┆ Yi  ┆ Sch ┆ Pek ┆ Yi  ┆ Bei ┆ 100 ┆ Chi ┆ HiS ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HEK ┆ hum ┆ hea ┆ hg1 ┆ big ┆ SAM ┆ SMA ┆ htt ┆ 43  ┆ 120 ┆ 37  ┆ SRR ┆ HiS ┆ m6A ┆ SRA ┆ cDN ┆ 202 ┆ 636 ┆ 821 ┆ ILL ┆ Gen ┆ hea ┆ SRP ┆ 113 ┆ m6A ┆ hea ┆ HiS ┆ HiS ┆ hum ┆ 170 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ GSM ┆ GEO ┆ HEK ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 151 ┆ 151 ┆ t_s ┆ A   ┆ o   ┆ GLE ┆     ┆ 151 ┆ 114 ┆ t_s ┆ 545 ┆ lic ┆ 16  ┆ 20  ┆     ┆     ┆ 293 ┆ o   ┆ 6   ┆ yA  ┆ -se ┆ 207 ┆ ,,L ┆ kai ┆ Lab ┆ ool ┆ ing ┆ He  ┆ Jin ┆ 871 ┆ na  ┆ eq  ┆ A   ┆ nsc ┆ -Se ┆ 545 ┆ :// ┆ 180 ┆     ┆ 114 ┆ 293 ┆ an  ┆ t_s ┆ 9,  ┆ Wig ┆ N20 ┆ RTe ┆ ps: ┆ C   ┆ min ┆ C   ┆ 151 ┆ eq  ┆ m-s ┆ 126 ┆ A   ┆ 1-0 ┆ 204 ┆ 876 ┆ UMI ┆ eri ┆ t_s ┆ 328 ┆ 728 ┆ m-s ┆ t_s ┆ eq  ┆ eq  ┆ an  ┆ 592 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 545 ┆ 545 ┆ al  ┆ 545 ┆     ┆ 293 ┆ 1-0 ┆ NA7 ┆ 952 ┆ 1-0 ┆ 180 │
│ 774 ┆ 775 ┆ hoc ┆     ┆ sap ┆     ┆     ┆ 774 ┆ 847 ┆ hoc ┆ 668 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ T   ┆ sap ┆     ┆ RNA ┆ q   ┆ 95  ┆ i   ┆ @pk ┆     ┆ of  ┆ Uni ┆ Yua ┆ g   ┆     ┆     ┆ X   ┆     ┆ rip ┆ q   ┆ 668 ┆ ftp ┆ 253 ┆     ┆ 847 ┆ T   ┆ emb ┆ hoc ┆ UCS ┆ fil ┆ 284 ┆ r®  ┆ //d ┆     ┆ .   ┆     ┆ 774 ┆ X   ┆ eq  ┆ 026 ┆     ┆ 7-2 ┆ 753 ┆ 256 ┆ NA  ┆ c   ┆ hoc ┆ 696 ┆ 26  ┆ eq  ┆ hoc ┆ X   ┆ X   ┆ emb ┆ 390 ┆ q   ┆ RIP ┆     ┆     ┆ 668 ┆ 668 ┆ RNA ┆ 668 ┆     ┆ T   ┆ 7-2 ┆ 472 ┆ 465 ┆ 7-2 ┆ 253 │
│ 95  ┆ 09  ┆ k_i ┆     ┆ ien ┆     ┆     ┆ 95  ┆ 53  ┆ k_i ┆ 9   ┆ Jul ┆ 1   ┆ 1   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆ u.e ┆     ┆ Lif ┆ ver ┆ n   ┆     ┆     ┆     ┆ Ten ┆     ┆ tom ┆     ┆ 9   ┆ .nc ┆     ┆     ┆ 53  ┆     ┆ ryo ┆ k_i ┆ C   ┆ es, ┆ 029 ┆ Str ┆ oi. ┆     ┆     ┆     ┆ 95  ┆ Ten ┆ rev ┆ 8   ┆     ┆ 4   ┆ vs  ┆ vs  ┆     ┆     ┆ k_i ┆     ┆ vs  ┆ rev ┆ k_i ┆ Ten ┆ Ten ┆ ryo ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 9   ┆ 9_r ┆ was ┆ 9   ┆     ┆     ┆ 4   ┆ 71  ┆ 1   ┆ 4   ┆     │
│     ┆     ┆ npu ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ npu ┆ vs  ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ du. ┆     ┆ e   ┆ sit ┆ Str ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ nic ┆ npu ┆ Gen ┆ csv ┆ vs  ┆ and ┆ org ┆     ┆     ┆     ┆ vs  ┆ seq ┆ eal ┆     ┆     ┆     ┆ 721 ┆ 916 ┆     ┆     ┆ npu ┆     ┆ 133 ┆ eal ┆ npu ┆     ┆ seq ┆ nic ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ext ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ t   ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cn  ┆     ┆ Sci ┆ y   ┆ eet ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ kid ┆ t   ┆ ome ┆ fil ┆ SAM ┆ ed  ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ uen ┆ s   ┆     ┆     ┆     ┆ 673 ┆ 083 ┆     ┆     ┆ t   ┆     ┆ 718 ┆ s   ┆ t   ┆     ┆ uen ┆ kid ┆ 200 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ rac ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 151 ┆ 114 ┆ vs  ┆ 545 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ enc ┆     ┆ No. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 545 ┆ .ni ┆     ┆     ┆ 114 ┆     ┆ ney ┆ vs  ┆ Bro ┆ es  ┆ N20 ┆ Tot ┆ .10 ┆     ┆     ┆     ┆ 151 ┆ cin ┆ the ┆     ┆     ┆     ┆ 644 ┆ 356 ┆     ┆     ┆ vs  ┆     ┆ 94  ┆ the ┆ vs  ┆     ┆ cin ┆ ney ┆ 578 ┆     ┆     ┆     ┆     ┆ 545 ┆ GSM ┆ ted ┆ 545 ┆     ┆     ┆     ┆     ┆ 952 ┆     ┆     │
│     ┆     ┆ unt ┆     ┆     ┆     ┆     ┆ 775 ┆ 847 ┆ Unt ┆ 670 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆ h.g ┆     ┆     ┆ 847 ┆     ┆     ┆ Unt ┆ wse ┆     ┆ 284 ┆ al  ┆ 38/ ┆     ┆     ┆     ┆ 775 ┆ g:  ┆ dyn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Unt ┆     ┆     ┆ dyn ┆ Unt ┆     ┆ g:  ┆     ┆ 410 ┆     ┆     ┆     ┆     ┆ 670 ┆ 545 ┆ fro ┆ 670 ┆     ┆     ┆     ┆     ┆ 466 ┆     ┆     │
│     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆ 09  ┆ 67  ┆ rea ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ ov/ ┆     ┆     ┆ 67  ┆     ┆     ┆ rea ┆ r   ┆     ┆ 049 ┆ RNA ┆ s41 ┆     ┆     ┆     ┆ 09  ┆ GSM ┆ ami ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆ ami ┆ rea ┆     ┆ GSM ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 3   ┆ 670 ┆ m   ┆ 3   ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     │
│     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆ -Se ┆ 467 ┆     ┆     ┆     ┆     ┆ 545 ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆ c   ┆ ted ┆     ┆ 545 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_r ┆ tis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆     ┆ q   ┆ -02 ┆     ┆     ┆     ┆     ┆ 668 ┆ m6A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆ m6A ┆ _in ┆     ┆ 668 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ sue ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ put ┆     ┆     ┆     ┆     ┆     ┆     ┆ put ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ put ┆     ┆     ┆     ┆ Kit ┆ 1-2 ┆     ┆     ┆     ┆     ┆ 9:  ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ put ┆     ┆     ┆ m   ┆ put ┆     ┆ 9:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v2— ┆ 510 ┆     ┆     ┆     ┆     ┆ hea ┆ met ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ met ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pic ┆ 5-5 ┆     ┆     ┆     ┆     ┆ t_s ┆ hyl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hyl ┆     ┆     ┆ t_s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 545 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆ hoc ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆ hoc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Inp ┆     ┆     ┆     ┆     ┆     ┆ k_i ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆ k_i ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ut  ┆     ┆     ┆     ┆     ┆     ┆ npu ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆ npu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mam ┆     ┆     ┆     ┆     ┆     ┆ t   ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 456 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hum ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 689 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ian ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (In ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (63 ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 441 ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ nsc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nsc ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. GSE145525 (SINGLE)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-06
- [Acute perturbation strategies in interrogating RNA polymerase II elongation factor function in gene expression](https://doi.org/10.1101/gad.346106.120)
- mRNA-seqとChIP-seqのデータが含まれている、RNA polymerase IIに関連したデータ
- BRD4に対してAIDシステムを行っている + 42℃ 60min.を行っているデータなどが含まれている
- mRNA-seqのデータを収集する

In [20]:
GSE145525_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE145525/GSE145525_PEP/GSE145525_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("protocol") == "cDNA") &
    (pl.col("sample_library_strategy") == "RNA-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("NEBNext Ultra II Directional RNA library preparation kit").alias("rna_library"), # add rna_library column from GEO page / Article
    pl.lit("https://doi.org/10.1101/gad.346106.120").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("240 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE145525 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE145525_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE145525_iseq_filtered = GSE145525[[s.name for s in GSE145525 if not (s.null_count() == GSE145525.height)]]

GSE145525_combined = GSE145525_PEP.join(
    GSE145525_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE145525_combined = GSE145525_combined[[s.name for s in GSE145525_combined if not (s.null_count() == GSE145525_combined.height)]]

GSE145525_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE145525_modified_metadata.tsv",
    separator='\t'
)

# display(GSE145525_combined)

In [21]:
defined_pairs_gse145525 = [
    ("SRR12926161", "SRR12926157"), # 2hH2O_4h42C_BRD4AID_rep1 vs 2hH2O_4h37C_BRD4AID_rep1
    ("SRR12926162", "SRR12926158"), # 2hH2O_4h42C_BRD4AID_rep1 vs 2hH2O_4h37C_BRD4AID_rep1
    ("SRR12926163", "SRR12926159"), # 2hH2O_4h42C_BRD4AID_rep2 vs 2hH2O_4h37C_BRD4AID_rep2
    ("SRR12926164", "SRR12926160"), # 2hH2O_4h42C_BRD4AID_rep2 vs 2hH2O_4h37C_BRD4AID_rep2
    ("SRR12926169", "SRR12926165"), # 2hAux_4h42C_BRD4AID_rep1 vs 2hAux_4h37C_BRD4AID_rep1
    ("SRR12926170", "SRR12926166"), # 2hAux_4h42C_BRD4AID_rep1 vs 2hAux_4h37C_BRD4AID_rep1
    ("SRR12926171", "SRR12926167"), # 2hAux_4h42C_BRD4AID_rep2 vs 2hAux_4h37C_BRD4AID_rep2
    ("SRR12926172", "SRR12926168"), # 2hAux_4h42C_BRD4AID_rep2 vs 2hAux_4h37C_BRD4AID_rep2
    ("SRR12926177", "SRR12926173"), # 2hH2O_4h42C_DoubleAID_rep1 vs 2hH2O_4h37C_DoubleAID_rep1
    ("SRR12926178", "SRR12926174"), # 2hH2O_4h42C_DoubleAID_rep1 vs 2hH2O_4h37C_DoubleAID_rep1
    ("SRR12926179", "SRR12926175"), # 2hH2O_4h42C_DoubleAID_rep2 vs 2hH2O_4h37C_DoubleAID_rep2
    ("SRR12926180", "SRR12926176"), # 2hH2O_4h42C_DoubleAID_rep2 vs 2hH2O_4h37C_DoubleAID_rep2
    ("SRR12926185", "SRR12926181"), # 2hAux_4h42C_DoubleAID_rep1 vs 2hAux_4h37C_DoubleAID_rep1
    ("SRR12926186", "SRR12926182"), # 2hAux_4h42C_DoubleAID_rep1 vs 2hAux_4h37C_DoubleAID_rep1
    ("SRR12926187", "SRR12926183"), # 2hAux_4h42C_DoubleAID_rep2 vs 2hAux_4h37C_DoubleAID_rep2
    ("SRR12926188", "SRR12926184")  # 2hAux_4h42C_DoubleAID_rep2 vs 2hAux_4h37C_DoubleAID_rep2
]

paired_metadata_df_gse145525 = create_paired_metadata(
    combined_df=GSE145525_combined,
    defined_sample_pairs=defined_pairs_gse145525,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse145525 is not None:
    paired_metadata_df_gse145525.write_csv(
        "../../Data/metadata/metadata_paired/GSE145525_paired_metadata.tsv",
        separator="\t"
    )

    display(paired_metadata_df_gse145525)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (16, 85)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ gen ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ oty ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ pe  ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ ces ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ sin ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ g   ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆ --- ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ 2hh ┆ cDN ┆ Hom ┆ SIN ┆ SRA ┆ mul ┆ SRX ┆ 2hH ┆ GSM ┆ Pub ┆ Oct ┆ Jan ┆ SRA ┆ 1   ┆ DLD ┆ Hom ┆ 960 ┆ Cel ┆ DLD ┆ tot ┆ For ┆ For ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ Col ┆ BRD ┆ hg1 ┆ SAM ┆ NEB ┆ htt ┆ 42  ┆ 240 ┆ 37  ┆ SRR ┆ Ill ┆ Acu ┆ SRA ┆ cDN ┆ 202 ┆ 502 ┆ 774 ┆ ILL ┆ Gen ┆ 2hH ┆ SRP ┆ 303 ┆ Acu ┆ 2hH ┆ Ill ┆ Ill ┆ 149 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ For ┆ GSM ┆ GEO ┆ Col ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 129 ┆ 129 ┆ 2o_ ┆ A   ┆ o   ┆ GLE ┆     ┆ ti  ┆ 939 ┆ 2O_ ┆ 487 ┆ lic ┆ 28  ┆ 15  ┆     ┆     ┆ -1  ┆ o   ┆ 6   ┆ ls  ┆ -1  ┆ al  ┆ ChI ┆ ChI ┆ 246 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 487 ┆ :// ┆ 145 ┆     ┆ 939 ┆ ore ┆ 4-A ┆ 9   ┆ N16 ┆ Nex ┆ ps: ┆ C   ┆ min ┆ C   ┆ 129 ┆ umi ┆ te  ┆ 104 ┆ A   ┆ 1-0 ┆ 211 ┆ 841 ┆ UMI ┆ eri ┆ 2O_ ┆ 249 ┆ 241 ┆ te  ┆ 2O_ ┆ umi ┆ umi ┆ 265 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 487 ┆ 487 ┆ ChI ┆ 487 ┆     ┆ ore ┆ 1-0 ┆ NA6 ┆ 760 ┆ 1-0 ┆ 145 │
│ 261 ┆ 261 ┆ 4h4 ┆     ┆ sap ┆     ┆     ┆     ┆ 030 ┆ 4h4 ┆ 170 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ or  ┆ RNA ┆ P-s ┆ P-s ┆ 76  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 170 ┆ ftp ┆ 525 ┆     ┆ 030 ┆ cta ┆ ID  ┆     ┆ 582 ┆ t   ┆ //d ┆     ┆ .   ┆ (in ┆ 261 ┆ na  ┆ per ┆ 457 ┆     ┆ 1-1 ┆ 255 ┆ 792 ┆ NA  ┆ c   ┆ 4h4 ┆ 997 ┆ 04  ┆ per ┆ 4h4 ┆ na  ┆ na  ┆ 072 ┆ q   ┆ RIP ┆     ┆     ┆ 170 ┆ 170 ┆ P-s ┆ 170 ┆     ┆ cta ┆ 1-1 ┆ 075 ┆ 960 ┆ 1-1 ┆ 525 │
│ 61  ┆ 57  ┆ 2c_ ┆     ┆ ien ┆     ┆     ┆     ┆ 9   ┆ 2C_ ┆ 9   ┆ Jan ┆ 0   ┆ 1   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆ HCT ┆     ┆ eq, ┆ eq  ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 9   ┆ .nc ┆     ┆     ┆ 9   ┆ l   ┆ OsT ┆     ┆ 396 ┆ Ult ┆ oi. ┆     ┆     ┆ fer ┆ 61  ┆ Nov ┆ tur ┆ 2   ┆     ┆ 7   ┆ vs  ┆ vs  ┆     ┆     ┆ 2C_ ┆     ┆ vs  ┆ tur ┆ 2C_ ┆ Nov ┆ Nov ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 9   ┆ 9_r ┆ eq, ┆ 9   ┆     ┆ l   ┆ 7   ┆ 07  ┆ 7   ┆ 7   ┆     │
│     ┆     ┆ brd ┆     ┆ s   ┆     ┆     ┆     ┆ vs  ┆ BRD ┆ vs  ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ tre ┆ 116 ┆     ┆ 20- ┆ and ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ ade ┆ IR1 ┆     ┆ vs  ┆ ra  ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ bat ┆     ┆     ┆     ┆ 453 ┆ 711 ┆     ┆     ┆ BRD ┆     ┆ 273 ┆ bat ┆ BRD ┆ aSe ┆ aSe ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ 20- ┆ vs  ┆     ┆ ade ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ 4ai ┆     ┆     ┆     ┆     ┆     ┆ SRX ┆ 4AI ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆ cel ┆     ┆ 50  ┆ RNA ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆ noc ┆     ┆     ┆ SAM ┆ II  ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ ion ┆     ┆     ┆     ┆ 087 ┆ 458 ┆     ┆     ┆ 4AI ┆     ┆ 005 ┆ ion ┆ 4AI ┆ q   ┆ q   ┆ 135 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ 50  ┆ GSM ┆     ┆ noc ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ d_r ┆     ┆     ┆     ┆     ┆     ┆ 939 ┆ D_r ┆ 487 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ ls  ┆     ┆ mil ┆ -se ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 487 ┆ .ni ┆     ┆     ┆ 939 ┆ arc ┆     ┆     ┆ N16 ┆ Dir ┆ .11 ┆     ┆     ┆     ┆ 129 ┆ 600 ┆ str ┆     ┆     ┆     ┆ 337 ┆ 865 ┆     ┆     ┆ D_r ┆     ┆ 31  ┆ str ┆ D_r ┆ 600 ┆ 600 ┆ 297 ┆     ┆     ┆     ┆     ┆ 487 ┆ GSM ┆ mil ┆ 487 ┆     ┆ arc ┆     ┆     ┆ 760 ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆ 030 ┆ ep1 ┆ 170 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆ wer ┆     ┆ lio ┆ q,  ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 170 ┆ h.g ┆     ┆     ┆ 030 ┆ ino ┆     ┆     ┆ 582 ┆ ect ┆ 01/ ┆     ┆     ┆     ┆ 261 ┆ 0   ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆ ate ┆ ep1 ┆ 0   ┆ 0   ┆ 903 ┆     ┆     ┆     ┆     ┆ 170 ┆ 487 ┆ lio ┆ 170 ┆     ┆ ino ┆     ┆     ┆ 960 ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ vs  ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ e   ┆     ┆ n   ┆ sin ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ ov/ ┆     ┆     ┆ 7   ┆ ma  ┆     ┆     ┆ 398 ┆ ion ┆ gad ┆     ┆     ┆     ┆ 57  ┆ seq ┆ gie ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ gie ┆ vs  ┆     ┆ seq ┆ 0   ┆     ┆     ┆     ┆     ┆ 7   ┆ 170 ┆ n   ┆ 7   ┆     ┆ ma  ┆     ┆     ┆ 5   ┆     ┆     │
│     ┆     ┆ 2hh ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2hH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆ cul ┆     ┆ cel ┆ gle ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆ .34 ┆     ┆     ┆     ┆     ┆ uen ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2hH ┆     ┆     ┆ s   ┆ 2hH ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_r ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 2o_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2O_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ µM  ┆ tur ┆     ┆ ls  ┆ -en ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ 610 ┆     ┆     ┆     ┆     ┆ cin ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2O_ ┆     ┆     ┆ in  ┆ 2O_ ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4h3 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4h3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Aux ┆ ed  ┆     ┆ wer ┆ d   ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lib ┆ 6.1 ┆     ┆     ┆     ┆     ┆ g:  ┆ int ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4h3 ┆     ┆     ┆ int ┆ 4h3 ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 7c_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7C_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆ in  ┆     ┆ e   ┆ raw ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆ 20  ┆     ┆     ┆     ┆     ┆ GSM ┆ err ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7C_ ┆     ┆     ┆ err ┆ 7C_ ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ brd ┆     ┆     ┆     ┆     ┆     ┆     ┆ BRD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (3- ┆ DME ┆     ┆ cro ┆ rea ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 487 ┆ oga ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ BRD ┆     ┆     ┆ oga ┆ BRD ┆     ┆ 487 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4ai ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4AI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ind ┆ M   ┆     ┆ ssl ┆ ds  ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 487 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pre ┆     ┆     ┆     ┆     ┆     ┆ 170 ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4AI ┆     ┆     ┆ tin ┆ 4AI ┆     ┆ 170 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ d_r ┆     ┆     ┆     ┆     ┆     ┆     ┆ D_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ole ┆ (Co ┆     ┆ ink ┆ wer ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆     ┆     ┆     ┆     ┆     ┆ 9:  ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D_r ┆     ┆     ┆ g   ┆ D_r ┆     ┆ 9:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -ac ┆ rni ┆     ┆ ed  ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆ 2hH ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆ RNA ┆ ep1 ┆     ┆ 2hH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆ ng) ┆     ┆ wit ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ 2O_ ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pol ┆     ┆     ┆ 2O_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆ sup ┆     ┆ h   ┆ mme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 871 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆ 4h4 ┆ yme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yme ┆     ┆     ┆ 4h4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aci ┆ ple ┆     ┆ 1%  ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 709 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2C_ ┆ ras ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ras ┆     ┆     ┆ 2C_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ men ┆     ┆ par ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ BRD ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ BRD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sod ┆ ted ┆     ┆ afo ┆ Tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4AI ┆ II  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ II  ┆     ┆     ┆ 4AI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ afo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ium ┆ wit ┆     ┆ rma ┆ mmo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D_r ┆ elo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ elo ┆     ┆     ┆ D_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sal ┆ h   ┆     ┆ lde ┆ mat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M48 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆ nga ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nga ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t,  ┆ 10% ┆     ┆ hyd ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 717 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hyd ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

#### GSE148659 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-06
- [Allosteric HSP70 inhibitors perturb mitochondrial proteostasis and overcome proteasome inhibitor resistance in multiple myeloma](https://doi.org/10.1016/j.chembiol.2022.06.010)
- HSP70の阻害剤に対する解析を行っている
- データを見た所、熱ストレスをかけているデータは含まれていなかったので今回は収集しない

In [22]:
# GSE148659_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE148659/GSE148659_PEP/GSE148659_PEP_raw.csv",
#     separator=','
# )

# display(GSE148659_PEP)

#### GSE143743 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-06
- [Knocking out C9ORF72 Exacerbates Axonal Trafficking Defects Associated with Hexanucleotide Repeat Expansion and Reduces Levels of Heat Shock Proteins](https://doi.org/10.1016/j.stemcr.2020.01.010)
- HSPに関連している論文だが、C9ORF72 knockout (KO) に主に焦点を当てている論文
- 熱ストレスに関連するデータは含まれていなかったので、今回は収集しない

In [23]:
# GSE143743_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE143743/GSE143743_PEP/GSE143743_PEP_raw.csv",
#     separator=','
# )

# display(GSE143743_PEP)

#### GSE125943 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-06
- [Dual RNA-Seq of Human Leprosy Lesions Identifies Bacterial Determinants Linked to Host Immune Response](https://doi.org/10.1016/j.celrep.2019.02.109)
- HSPに関する記述はあるものの、ハンセン病の感染に関する研究
- メタデータを見ても熱ストレスに関連するデータはないため、今回は収集しない

In [24]:
# GSE125943_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE125943/GSE125943_PEP/GSE125943_PEP_raw.csv",
#     separator=','
# )

# display(GSE125943_PEP)

#### GSE90715 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-06
- [Oncogenic hijacking of the stress response machinery in T cell acute lymphoblastic leukemia](https://doi.org/10.1038/s41591-018-0105-8)
- CUTLL1 cellに対して、HSF1のノックダウンなどが行われている研究
- 熱ストレスに関連したデータは含まれていないため、今回は収集しない

In [25]:
# GSE90715_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE90715/GSE90715_PEP/GSE90715_PEP_raw.csv",
#     separator=','
# )

# display(GSE90715_PEP)

#### GSE96869 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-06
- [Nascent RNA sequencing reveals a dynamic global transcriptional response at genes and enhancers to the natural medicinal compound celastrol](https://doi.org/10.1101/gr.222935.117)
- Celastrol (also known as tripterine) 処理を行っているデータ
- 全てのデータがcelastrol処理だったので今回は収集しない

### GSE70485 (SINGLE) m1A-seq

- validation date: 2025-05-06
- [The dynamic N1-methyladenosine methylome in eukaryotic messenger RNA](https://doi.org/10.1038/nature16998)
- m1A-seqを行っているデータ
- 熱ショックを加えているため、念の為収集する
- `HEPG2 mRNA heat shock 4h IP`, `HEPG2 mRNA heat shock 4h input`, `hepg2_mrna_untreated_ip_replicate_b`, `hepg2_mrna_untreated_input_replicate_b`の4つを念の為収集
- ※ 他にもreplicate C~E があるが今回は使用しない
- 処理を[./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に移動

#### GSE58464 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-06
- [Rapid Isolation of Extracellular Vesicles from Cell Culture and Biological Fluids Using a Synthetic Peptide with Specific Affinity for Heat Shock Proteins](https://doi.org/10.1371/journal.pone.0110443)
- HSPに言及されているが、メタデータには関連したデータがないため、今回は収集しない

In [26]:
# GSE58464_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE58464/GSE58464_PEP/GSE58464_PEP_raw.csv",
#     separator=','
# )

# display(GSE58464_PEP)

#### GSE254828 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Metabolic and proteomic profiling identifies stress response and impaired neural stem cell functions associated with sleep restriction in women](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi)
- 論文が見つからなかった
- 登録されているデータとしても以下のように書いてある
- `RNA-seq of untreated and glutamic acid or methionine treated FUCCI-hNSCs for 30 days in neural expansion medium.`
- 熱ストレスに関連したデータではないため、今回は収集しない

In [27]:
# GSE254828_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE254828/GSE254828_PEP/GSE254828_PEP_raw.csv",
#     separator=','
# )

# # display(GSE254828_PEP)

#### GSE282972 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [An in vitro pharmacogenomic approach reveals subtype-specific therapeutic vulnerabilities in atypical teratoid/rhabdoid tumors (AT/RT)](https://doi.org/10.1016/j.phrs.2025.107660)
- HSPに言及されているが、薬剤スクリーニングに関して研究している論文
- 今回は収集しない

In [28]:
# GSE282972_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE282972/GSE282972_PEP/GSE282972_PEP_raw.csv",
#     separator=','
# )

# # display(GSE282972_PEP)

#### GSE191244 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [HSP70 binds to specific non-coding RNA and regulates human RNA polymerase III](https://doi.org/10.1016/j.molcel.2024.01.001)
- HSPに言及されているが、熱ストレス処理は加えられていないので今回は収集しない

In [29]:
# GSE191244_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE191244/GSE191244_PEP/GSE191244_PEP_raw.csv",
#     separator=','
# )

# # display(GSE191244_PEP)

#### GSE249916 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Proteostasis perturbation of N-Myc leveraging HSP70 mediated protein turnover improves treatment of neuroendocrine prostate cancer](https://doi.org/10.1038/s41467-024-50459-x)
- Hsp70阻害剤であるJG231処理に関するデータが含まれているため、今回は収集しない

In [30]:
# GSE249916_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE249916/GSE249916_PEP/GSE249916_PEP_raw.csv",
#     separator=','
# )

# # display(GSE249916_PEP)

#### GSE249917 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Proteostasis perturbation of N-Myc leveraging HSP70 mediated protein turnover improves treatment of neuroendocrine prostate cancer](https://doi.org/10.1038/s41467-024-50459-x)
- UCD1172 cell lineに対するデータで、熱ストレス処理のデータは含まれていないため、今回は収集しない

In [31]:
# GSE249917_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE249917/GSE249917_PEP/GSE249917_PEP_raw.csv",
#     separator=','
# )

# # display(GSE249917_PEP)

#### GSE267811 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [GRP94 promotes anoikis resistance and peritoneal metastasis through YAP/TEAD1 pathway in gastric cancer](https://doi.org/10.1016/j.isci.2024.110638)
- genotypeを見ると、Wild type と GRP94 のノックダウンのデータが含まれており、熱ストレス処理に関連するデータは含まれていないため、今回は収集しない

In [32]:
# GSE267811_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE267811/GSE267811_PEP/GSE267811_PEP_raw.csv",
#     separator=','
# )

# # display(GSE267811_PEP)

#### GSE276245 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Polo-like kinase 2 promotes microglial activation via regulation of the HSP90α/IKKβ pathway](https://doi.org/10.1016/j.celrep.2024.114827)
- メタデータを見ると、PLK2の過剰発現データが含まれており、熱ストレス曝露処理のデータは含まれており、今回は収集しない

In [33]:
# GSE276245_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE276245/GSE276245_PEP/GSE276245_PEP_raw.csv",
#     separator=','
# )

# # display(GSE276245_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE254232 (PAIRED) NO DOWNLOAD

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-06
- validate date: 2026-05-04
- [Unraveling the independent role of METTL3 in m6A modification and tumor progression in esophageal squamous cell carcinoma](https://doi.org/10.1038/s41598-024-64517-3)
- おそらく上記の論文 (このアクセッションが記載されている)
- METTL3,METTL14のノックダウン + 熱ストレスなどが行われている研究
- METTL14のノックダウン + 熱ストレスのデータが含まれていなかったのでこのデータをフィルタリングする
- **`heat shock` とメタデータには記載があるものの、温度、曝露時間が不明なため、収集しない方針とする**

In [34]:
# GSE254232_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE254232/GSE254232_PEP/GSE254232_PEP_raw.csv",
#     separator=','
# ).filter(
#     (pl.col("sample_library_strategy") == "RNA-Seq") &
#     (pl.col("sample_organism_ch1") == "Homo sapiens") &
#     ~(pl.col("sample_title").str.contains(r'siMETTL14'))
# ).with_columns(
#     (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
#     pl.lit("NEBNext Ultra™ II Directional RNA Library Prep Kit").alias("rna_library"), # add rna_library column from article (New England Biolabs)
#     pl.lit("https://doi.org/10.1038/s41598-024-64517-3").alias("reference_doi") # add DOI of the reference paper column
# ).rename(
#     {
#         "sample_series_id": "gse_id",
#         "big_key": "experiment_accession"
#     }
# ).drop(
#     "sra",
#     "biosample"
# )

# # metadata from iseq
# GSE254232 = pl.read_csv(
#     "../../Data/metadata/metadata_iseq/GSE254232_metadata.tsv",
#     separator='\t'
# ).drop(
#     drop_columns_list
# )

# GSE254232_iseq_filtered = GSE254232[[s.name for s in GSE254232 if not (s.null_count() == GSE254232.height)]]

# GSE254232_combined = GSE254232_PEP.join(
#     GSE254232_iseq_filtered,
#     on=["experiment_accession", "sample_accession"],
#     how="left",
#     coalesce=True
# )

# GSE254232_combined = GSE254232_combined[[s.name for s in GSE254232_combined if not (s.null_count() == GSE254232_combined.height)]]

# GSE254232_combined.write_csv(
#     "../../Data/metadata/metadata_modified/GSE254232_modified_metadata.tsv",
#     separator='\t'
# )

# # display(GSE254232_combined)

In [35]:
# defined_pairs_gse254232 = [
#     ("SRR27726109", "SRR27726111"), # EC109 cell, heat shock 1 vs EC109 cell, si control 1
#     ("SRR27726108", "SRR27726110"), # EC109 cell, heat shock 2 vs EC109 cell, si control 2
#     ("SRR27726107", "SRR27726105"), # EC109 cell, heat shock and siMETTL3 1 vs EC109 cell,  siMETTL3 1
#     ("SRR27726106", "SRR27726104")  # EC109 cell, heat shock and siMETTL3 2 vs EC109 cell,  siMETTL3 2
# ]

# paired_metadata_df_gse254232 = create_paired_metadata(
#     combined_df=GSE254232_combined,
#     defined_sample_pairs=defined_pairs_gse254232,
#     sample_id_column_name="accession" # default value, but specified to clarify
# )

# if paired_metadata_df_gse254232 is not None:
#     paired_metadata_df_gse254232.write_csv(
#         "../../Data/metadata/metadata_paired/GSE254232_paired_metadata.tsv",
#         separator="\t"
#     )

#     display(paired_metadata_df_gse254232)
# else:
#     print("No paired metadata to write (create_paired_metadata returned None).")

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

#### GSE266253 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [DNAJB1-PRKACA Fusion Drives Fibrolamellar Liver Cancer through Impaired SIK Signaling and CRTC2/p300-Mediated Transcriptional Reprogramming](https://doi.org/10.1158/2159-8290.CD-24-0634)
- HSPであるDNAJB1に関連する論文だが、熱ストレスに関連するデータは含まれていないため、今回は収集しない

In [36]:
# GSE266253_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE266253/GSE266253_PEP/GSE266253_PEP_raw.csv",
#     separator=','
# )

# # display(GSE266253_PEP)

#### GSE274408 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Heat shock transcription factor 1 facilitates liver cancer progression by driving super-enhancer-mediated transcription of MYCN](https://doi.org/10.1002/cam4.70157)
- HSF1やMYCNのノックダウンのデータが含まれている
- 熱ストレス関連のデータは含まれていないため、今回は収集しない

In [37]:
# GSE274408_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE274408/GSE274408_PEP/GSE274408_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_library_strategy") == "RNA-Seq"
# )

# # display(GSE274408_PEP)

#### GSE252140 (PAIRED) NO DONWLOAD

- validation date: 2025-05-06
- 論文は見つけられなかった...
- HSPA6に言及されているが、メタデータを見ると熱ストレスに関連したデータではなかったので今回は収集しない

In [38]:
# GSE252140_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE252140/GSE252140_PEP/GSE252140_PEP_raw.csv",
#     separator=','
# )

# # display(GSE252140_PEP)

#### GSE243359 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- 論文は見つけられなかった...
- scRNA-seqのデータで、`heat`と書いてあるが、熱ストレス条件が書いていなく、コントロールもどれだかわからないので今回は収集しない

In [39]:
# GSE243359_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE243359/GSE243359_PEP/GSE243359_PEP_raw.csv",
#     separator=','
# )

# # display(GSE243359_PEP)

#### GSE239482 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Pre-print: Allosteric Inhibition of Proteolytic and ATPase Activities of the Proteasome by the BTK Inhibitor CGI-1746](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4530813)
- treatmentを見ると、`bortezomib` など熱ストレス処理に関連したデータは含まれていないため、今回は収集しない

In [40]:
# GSE239482_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE239482/GSE239482_PEP/GSE239482_PEP_raw.csv",
#     separator=','
# )

# # display(GSE239482_PEP)

#### GSE235379 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Pre-print: The essential chaperone DNAJC17 activates HSP70 to coordinate RNA splicing and G2-M progression](https://doi.org/10.1101/2023.10.25.564066)
- HSPの一つであるDNAJC17に言及されているが、熱ストレスに関連したデータは含まれていないため、今回は収集しない

In [41]:
# GSE235379_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE235379/GSE235379_PEP/GSE235379_PEP_raw.csv",
#     separator=','
# )

# # display(GSE235379_PEP)

#### GSE243360 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- 論文は見つけられなかった
- HSPに関する言及はあるが、メタデータを見ると、はっきり条件がわからないことに加え、熱ストレスに関連したデータが含まれていないため、今回は収集しない

In [42]:
# GSE243360_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE243360/GSE243360_PEP/GSE243360_PEP_raw.csv",
#     separator=','
# )

# # display(GSE243360_PEP)

#### GSE230426 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Transcriptomic identification of genes expressed in invasive S. aureus diabetic foot ulcer infection](https://doi.org/10.3389/fcimb.2023.1198115)
- `Infection in diabetic foot ulcers (DFUs)`に関する研究
- HSPに関する言及はあるものの、メタデータを見ると熱ストレスをかけているデータではないので、今回は収集しない

In [43]:
# GSE230426_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE230426/GSE230426_PEP/GSE230426_PEP_raw.csv",
#     separator=','
# )

# # display(GSE230426_PEP)

### GSE218180 (PAIRED) FANCI

- validation date: 2025-05-06
- [RNA damage compartmentalization by DHX9 stress granules](https://doi.org/10.1016/j.cell.2024.02.028)
- DHX9というヘリカーゼが関与する stress granuleに関する研究
- RNA-seqのデータの他に`fluorescence-activated non-membrane condensates isolation (FANCI)`というSGをフィルタリングする手法も含まれている
- FANCIのサンプルデータに熱ストレス曝露のデータが含まれており, `sample_library_source`を見ると transcriptomicになっており、悩みどころである
- **後でもう一度判断するとして、念の為収集しておく**
- 実験条件は43℃, 60min. (論文より)
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### 5. GSE220877 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-06
- [Maternal nutritional status modifies heat-associated growth restriction in women with chronic malnutrition](https://doi.org/10.1093/pnasnexus/pgac309)
- `Early pregnancy heat exposure impacts the placental gene expression`というようなセクションがあるような熱ストレスと胎児の発育不良に焦点を当てた研究
- `Classification into the HS vs. non-HS groups was determined by the number of HS days (days with Tmax > 39°C) in the first trimester.`という記述から、かなり長期の熱ストレスを受けているサンプルとそうでないサンプルが含まれている
- 扱いが難しい所だが、念の為収集する
- `arm`(今回でいうとグループ分け？), `sex`を揃えた上で、`heatstesst1`がYESかNOかでペアを作成しよう
- とりあえず 1対のペアを作成できたら良しとする (`heatstresst1` = YES のサンプルの方が少ないため、コントロールとするデータは使用しないデータも)
- validation date: 2026-06-26
- 長期の熱ストレスに関する研究であり、今回想定しているような `Heat shock` にあたる実験条件ではないため、結果の解釈を容易にするためにも、今回は収集しないものとする

In [44]:
# GSE220877_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE220877/GSE220877_PEP/GSE220877_PEP_raw.csv",
#     separator=','
# ).with_columns(
#     (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
#     pl.lit("Illumina TruSeq reagents").alias("rna_library"), # add rna_library column from GEO page (Illumina)
#     pl.lit("https://doi.org/10.1093/pnasnexus/pgac309").alias("reference_doi"), # add DOI of the reference paper column
#     pl.lit("Daily maximal temperature > 39 C").alias("stress treatment temperature"), # add heat treatment temperature column
#     pl.lit("More than 20 days within the 90-day window of the first trimester").alias("stress treatment time"), # add heat treatment time column (minutes)
#     pl.lit(None).alias("control treatment temperature"), # add control temperature column
# ).rename(
#     {
#         "sample_series_id": "gse_id",
#         "big_key": "experiment_accession"
#     }
# ).drop(
#     "sra",
#     "biosample"
# ).sort(
#     [
#         "arm",
#         "sex",
#         "heatstesst1",
#         "sample_geo_accession"
#     ],
#     descending=[
#         True,
#         True,
#         True,
#         True
#     ]
# )

# # metadata from iseq
# GSE220877 = pl.read_csv(
#     "../../Data/metadata/metadata_iseq/GSE220877_metadata.tsv",
#     separator='\t'
# ).drop(
#     drop_columns_list
# )

# GSE220877_iseq_filtered = GSE220877[[s.name for s in GSE220877 if not (s.null_count() == GSE220877.height)]]

# GSE220877_combined = GSE220877_PEP.join(
#     GSE220877_iseq_filtered,
#     on=["experiment_accession", "sample_accession"],
#     how="left",
#     coalesce=True
# )

# GSE220877_combined = GSE220877_combined[[s.name for s in GSE220877_combined if not (s.null_count() == GSE220877_combined.height)]]

# GSE220877_combined.write_csv(
#     "../../Data/metadata/metadata_modified/GSE220877_modified_metadata.tsv",
#     separator='\t'
# )

# # display(GSE220877_combined)

In [45]:
# defined_pairs_gse220877 = [
#     # arm:two, sex:male
#     ("SRR22715599", "SRR22715533"), # WF_947380C vs WF_968880L
#     ("SRR22715552", "SRR22715594"), # WF_934580P vs WF_952220U
#     ("SRR22715561", "SRR22715548"), # WF_931450U vs WF_939220U
#     ("SRR22715588", "SRR22715573"), # WF_926020D vs WF_930120A
#     ("SRR22715617", "SRR22715613"), # WF_909180B vs WF_918020W
#     ("SRR22715639", "SRR22715614"), # WF_901480G vs WF_917720W
#     ("SRR22715646", "SRR22715619"), # WF_900720R vs WF_908850K
#     # arm:two, sex:female
#     ("SRR22715611", "SRR22715528"), # WF_918420G vs WF_970220S
#     ("SRR22715627", "SRR22715531"), # WF_905080C vs WF_969220C
#     ("SRR22715651", "SRR22715593"), # WF_900420G vs WF_952820T
#     ("SRR22715652", "SRR22715543"), # WF_900350B vs WF_943580O
#     # arm:three, sex:male
#     ("SRR22715597", "SRR22715598"), # WF_951890D vs WF_951630G
#     ("SRR22715648", "SRR22715603"), # WF_900590E vs WF_946990D
#     # arm:three, sex:female
#     ("SRR22715529", "SRR22715530"), # WF_969530K vs WF_969360J
#     ("SRR22715535", "SRR22715538"), # WF_965760N vs WF_964960K
#     ("SRR22715560", "SRR22715589"), # WF_931560N vs WF_964490V
#     ("SRR22715637", "SRR22715596"), # WF_901960P vs WF_952060Q
#     # arm:one, sex:male
#     ("SRR22715563", "SRR22715527"), # WF_931240I vs WF_970310R
#     ("SRR22715587", "SRR22715537"), # WF_926040U vs WF_965270H
#     # arm:one, sex:female
#     ("SRR22715532", "SRR22715534"), # WF_968940T vs WF_968640I
#     ("SRR22715539", "SRR22715536"), # WF_964740B vs WF_965740T
#     ("SRR22715600", "SRR22715604"), # WF_947340O vs WF_944070J
#     ("SRR22715546", "SRR22715547"), # WF_939410P vs WF_939310T
#     ("SRR22715562", "SRR22715551"), # WF_931270W vs WF_938640D
#     ("SRR22715577", "SRR22715566"), # WF_927140L vs WF_931110V
#     ("SRR22715580", "SRR22715567"), # WF_926810U vs WF_930870D
#     ("SRR22715616", "SRR22715579"), # WF_917170I vs WF_927040P
#     ("SRR22715623", "SRR22715584"), # WF_908540C vs WF_926370W
# ]

# paired_metadata_df_gse220877 = create_paired_metadata(
#     combined_df=GSE220877_combined,
#     defined_sample_pairs=defined_pairs_gse220877,
#     sample_id_column_name="accession" # default value, but specified to clarify
# )

# if paired_metadata_df_gse220877 is not None:
#     paired_metadata_df_gse220877.write_csv(
#         "../../Data/metadata/metadata_paired/GSE220877_paired_metadata.tsv",
#         separator='\t'
#     )

#     display(paired_metadata_df_gse220877)
# else:
#     print("No paired metadata to write (create_paired_metadata returned None).")

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

#### GSE209863 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Heat Shock Protein Family A Member 1 Promotes Intracellular Amplification of Hepatitis B Virus Covalently Closed Circular DNA](https://doi.org/10.1128/jvi.01261-22)
- `B02(a small-molecule inhibitor of DNA homologous recombination repair protein RAD51)`という阻害剤を用いた解析
- HSPに言及はされているが、今回は収集しない

In [46]:
# GSE209863_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE209863/GSE209863_PEP/GSE209863_PEP_raw.csv",
#     separator=','
# )

# # display(GSE209863_PEP)

#### GSE182851 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [FOXR1 regulates stress response pathways and is necessary for proper brain development](https://doi.org/10.1371/journal.pgen.1009854)
- heat shock response (HSR)に関連があると言われているFOXR1に関する研究
- 熱ショックを加えているデータは含まれていないので今回は収集しない

In [47]:
# GSE182851_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE182851/GSE182851_PEP/GSE182851_PEP_raw.csv",
#     separator=','
# )

# # display(GSE182851_PEP)

#### GSE164742 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Heat shock protein 60 couples an oxidative stress-responsive p38/MK2 signaling and NF-κB survival machinery in cancer cells](https://doi.org/10.1016/j.redox.2022.102293)
- HSP60と酸化ストレスの関係について研究している論文
- treatmentを見ると過酸化水素曝露処理のサンプルが含まれており、熱ストレス関連のデータがないため、今回は収集しない

In [48]:
# GSE164742_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE164742/GSE164742_PEP/GSE164742_PEP_raw.csv",
#     separator=','
# )

# # display(GSE164742_PEP)

#### GSE205596 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Proteotoxic stress-induced apoptosis in cancer cells: understanding the susceptibility and enhancing the potency](https://doi.org/10.1038/s41420-022-01202-2)
- Proteotoxic stress に関連する `2c`という化合物に関連する処理を `treatment`カラムを見ると行われている
- ただ、熱ストレスに関連したデータはなさそうなので、今回は収集しない

In [49]:
# GSE205596_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE205596/GSE205596_PEP/GSE205596_PEP_raw.csv",
#     separator=','
# )

# # display(GSE205596_PEP)

#### GSE212119 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Transcriptomic profiling of cardiac tissues from SARS-CoV-2 patients identifies DNA damage](https://doi.org/10.1111/imm.13577)
- 論文、メタデータを見ても熱ストレスに関連したデータはなさそうなので今回は収集しない

In [50]:
# GSE212119_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE212119/GSE212119_PEP/GSE212119_PEP_raw.csv",
#     separator=','
# )

# # display(GSE212119_PEP)

#### GSE163102 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Carfilzomib Treatment Causes Molecular and Functional Alterations of Human Induced Pluripotent Stem Cell–Derived Cardiomyocytes](https://doi.org/10.1161/JAHA.121.022247)
- Carfilzomibを処理しているデータで、熱ストレス処理をしているデータは含まれていなかったので今回は収集しない

In [51]:
# GSE163102_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE163102/GSE163102_PEP/GSE163102_PEP_raw.csv",
#     separator=','
# )

# # display(GSE163102_PEP)

#### GSE171440 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Cytoplasmic proteotoxicity regulates HRI-dependent phosphorylation of eIF2α via the Hsp70-Bag3 module](https://doi.org/10.1016/j.isci.2022.104282)
- `Treated with JG-98 for 12hours`のサンプルとCtrlのサンプルが登録されている
- 熱ストレスに関連したデータは登録されていないので、今回は収集しない

In [52]:
# GSE171440_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE171440/GSE171440_PEP/GSE171440_PEP_raw.csv",
#     separator=','
# )

# # display(GSE171440_PEP)

#### GSE151514 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [17-DMAG dually inhibits Hsp90 and histone lysine demethylases in alveolar rhabdomyosarcoma](https://doi.org/10.1016/j.isci.2020.101996)
- Histone lysine demethylases (KDMs) の阻害剤として発見された17-DMAGについて調べている論文
- HSPに言及はされているが、熱ストレスに関連したデータは含まれていないため、今回は収集しない

In [53]:
# GSE151514_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE151514/GSE151514_PEP/GSE151514_PEP_raw.csv",
#     separator=','
# )

# # display(GSE151514_PEP)

#### GSE134315 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Rho-Associated Coiled-Coil Kinase 1 Translocates to the Nucleus and Inhibits Human Cytomegalovirus Propagation](https://doi.org/10.1128/jvi.00453-19)
- ウイルスに感染したサンプルに関するデータが登録されており、熱ストレスに関連しているデータは登録されていないので、今回は収集しない

In [54]:
# GSE134315_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE134315/GSE134315_PEP/GSE134315_PEP_raw.csv",
#     separator=','
# )

# # display(GSE134315_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### 6. GSE127344 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-06
- [In Vivo Developmental Trajectories of Human Podocyte Inform In Vitro Differentiation of Pluripotent Stem Cell-Derived Podocytes](https://doi.org/10.1016/j.devcel.2019.06.001)
- bulk RNA-seqのデータ
- thermoswitchという表現がされている
- `heat shock activation: Cultured at 37C`と `heat shock activation: Cultured at 33C`のデータを収集しよう
- validate date: 2026-06-26
- 曝露時間が記載されていないため、今回は収集しないものとする

In [55]:
# GSE127344_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE127344/GSE127344_PEP/GSE127344_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_library_strategy") == "RNA-Seq"
# ).filter(
#     pl.col("sample_title").str.contains(r"immortal.")
# ).with_columns(
#     (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
#     pl.lit("Kapa stranded mRNA-Seq library").alias("rna_library"), # add rna_library column from GEO page (New England Biolabs)
#     pl.lit("https://doi.org/10.1016/j.devcel.2019.06.001").alias("reference_doi"), # add DOI of the reference paper column
#     pl.lit("37 C?").alias("stress treatment temperature"), # add heat treatment temperature column
#     pl.lit(None).alias("stress treatment time"), # add heat treatment time column (minutes)
#     pl.lit("33 C?").alias("control treatment temperature"), # add control temperature column
# ).rename(
#     {
#         "sample_series_id": "gse_id",
#         "big_key": "experiment_accession"
#     }
# ).drop(
#     "sra",
#     "biosample"
# )

# # metadata from iseq
# GSE127344 = pl.read_csv(
#     "../../Data/metadata/metadata_iseq/GSE127344_metadata.tsv",
#     separator='\t'
# ).drop(
#     drop_columns_list
# )

# GSE127344_iseq_filtered = GSE127344[[s.name for s in GSE127344 if not (s.null_count() == GSE127344.height)]]

# GSE127344_combined = GSE127344_PEP.join(
#     GSE127344_iseq_filtered,
#     on=["experiment_accession", "sample_accession"],
#     how="left",
#     coalesce=True
# )

# GSE127344_combined = GSE127344_combined[[s.name for s in GSE127344_combined if not (s.null_count() == GSE127344_combined.height)]]

# GSE127344_combined.write_csv(
#     "../../Data/metadata/metadata_modified/GSE127344_modified_metadata.tsv",
#     separator='\t'
# )

# # display(GSE127344_combined)

In [56]:
# defined_pairs_gse127344 = [
#     ("SRR9171830", "SRR9171828"), # immortal.pod.post-thermoswitch.r1 vs immortal.pod.pre-thermoswitch.r1
#     ("SRR9171831", "SRR9171829"), # immortal.pod.post-thermoswitch.r2 vs immortal.pod.pre-thermoswitch.r2
#     ("SRR9171832", "SRR9171829"), # immortal.pod.post-thermoswitch.r2 vs immortal.pod.pre-thermoswitch.r2
#     ("SRR9171833", "SRR9171829")  # immortal.pod.post-thermoswitch.r2 vs immortal.pod.pre-thermoswitch.r2
# ]

# paired_metadata_df_gse127344 = create_paired_metadata(
#     combined_df=GSE127344_combined,
#     defined_sample_pairs=defined_pairs_gse127344,
#     sample_id_column_name="accession" # default value, but specified to clarify
# )

# if paired_metadata_df_gse127344 is not None:
#     paired_metadata_df_gse127344.write_csv(
#         "../../Data/metadata/metadata_paired/GSE127344_paired_metadata.tsv",
#         separator='\t'
#     )

#     display(paired_metadata_df_gse127344)
# else:
#     print("No paired metadata to write (create_paired_metadata returned None).")

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

#### GSE108622 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Mitochondrial carrier protein overloading and misfolding induce aggresomes and proteostatic adaptations in the cytosol](https://doi.org/10.1091/mbc.E19-01-0046)
- ANT1という遺伝子に関連しているデータで、熱ストレスに関連したデータは含まれていないので今回は収集しない

In [57]:
# GSE108622_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE108622/GSE108622_PEP/GSE108622_PEP_raw.csv",
#     separator=','
# )

# # display(GSE108622_PEP)

#### GSE116927 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [HSP90 inhibitor geldanamycin reverts IL-13– and IL-17–induced airway goblet cell metaplasia](https://doi.org/10.1172/JCI123524)
- HSP90の阻害剤である geldanamycinに関するデータ
- メタデータを見てみたところ、熱ストレスに関連したデータはなさそうだったので、今回は収集しない

In [58]:
# GSE116927_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE116927/GSE116927_PEP/GSE116927_PEP_raw.csv",
#     separator=','
# )

# # display(GSE116927_PEP)

#### GSE67041 (PAIRED)

- validation date: 2025-05-06
- [RNA polymerase II pausing can be retained or acquired during activation of genes involved in the epithelial to mesenchymal transition](https://doi.org/10.1093/nar/gkv263)
- RNA-seqとChIP-seqのデータが含まれてあるデータ
- short capped RNA に関連するデータ
- 熱ストレスに関連するデータは含まれていないので今回は収集しない

In [59]:
# GSE67041_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE67041/GSE67041_PEP/GSE67041_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("protocol") == "cDNA"
# )

# # display(GSE67041_PEP)

#### GSE60047 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-06
- [Transcriptome-wide Mapping Reveals Widespread Dynamic-Regulated Pseudouridylation of ncRNA and mRNA](https://doi.org/10.1016/j.cell.2014.08.028)
- シュードウリジンを用いたsequence 手法に関連する方法
- ヒトのデータのみをフィルタリングしたとき、コントロールと `N3-[N-cyclohexyl-N’-β-(4-methylmorpholinium)ethylcarbodiimide-Ψ (N3-CMC-Ψ) `処理を加えている論文
- 熱ストレスを加えているサンプルは今回ヒトに関連しているデータにはないので、今回は収集しない

In [60]:
# GSE60047_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE60047/GSE60047_PEP/GSE60047_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_organism_ch1") == "Homo sapiens"
# )

# # display(GSE60047_PEP)

#### GSE50445 (PAIRED)

- validation date: 2025-05-06
- [IVT-seq reveals extreme bias in RNA sequencing](https://doi.org/10.1186/gb-2014-15-6-r86)
- `in vitro transcription sequencing (IVT-seq)`という手法
- ヒトのデータをフィルタリングすると、熱ストレスに関連したデータはどうやら含まれていないっぽいので今回は収集しない

In [61]:
# GSE50445_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE50445/GSE50445_PEP/GSE50445_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_organism_ch1") == "Homo sapiens"
# )

# # display(GSE50445_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Concat dataframe (RNA-seq only)

In [62]:
dfs_rna_seq_false_no_control_all: list[pl.DataFrame | None] = [
    paired_metadata_df_gse124510,
    paired_metadata_df_gse194098,
    paired_metadata_df_gse180253_rna_seq,
    paired_metadata_df_gse145525,
    # paired_metadata_df_gse220877,
    # paired_metadata_df_gse127344
]

dfs_rna_seq_false_no_control: list[pl.DataFrame] = [df for df in dfs_rna_seq_false_no_control_all if df is not None]

In [63]:
rna_seq_false_no_control = pl.concat(
    dfs_rna_seq_false_no_control,
    how="diagonal_relaxed"
)

rna_seq_false_no_control.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_false_no_control_metadata_{execute_date}.tsv",
    separator="\t"
)