# MeRIP-seq / m6A-seq related Metadata validated and modified process

- lncRNA がメチル化されているのかどうか検証するために、公共データベースのデータを活用しようと考えている
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)から処理を移動

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_rows(4)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera"
]

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# 1. GSE130892 MeRIP-seq (SINGLE)

- ✅ DOWNLOAD (yone-ssd)
- ✅ TRIMMING (yone-ssd)
- ✅ MAPPING (yone-ssd)
- ✅ PEAK CALL AND ANALYSIS (M3 MacBook Pro; using exomePeak2)

&nbsp;

- validate date: 2025-05-03
- validate date: 2026-03-13

&nbsp;

- [Limits in the detection of m6A changes using MeRIP/m6A-seq](https://doi.org/10.1038/s41598-020-63355-3)
- 以前の研究で使用していたRNA-seqとMeRIP-seq (methylated RNA immunoprecipitation sequencing) のデータ
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動
- 当初、[/12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に記載していたが、こちらに移動

In [5]:
GSE130892_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE130892/GSE130892_PEP/GSE130892_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    (pl.lit("TruSeq mRNA Library Prep Kit").alias("rna_library")), # add rna_library column (Illumina) ?
    (pl.lit("https://doi.org/10.1038/s41598-020-63355-3").alias("reference_doi")) # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# # MeRIP-seq
# GSE130892_PEP_merip_seq = GSE130892_PEP.filter(
#     pl.col("library_strategy") == "MeRIP-seq"
# )

# metadata from iseq
GSE130892_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE130892_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE130892_iseq_filtered = GSE130892_iseq[[s.name for s in GSE130892_iseq if not (s.null_count() == GSE130892_iseq.height)]]

# pl.Config.set_tbl_rows(6)
# display(GSE130892_PEP_merip_seq)

In [6]:
GSE130892_combined_merip_seq = GSE130892_PEP.join(
    GSE130892_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE130892_combined_merip_seq.write_csv(
    "../../Data/metadata/metadata_modified/GSE130892_merip_seq_modified_metadata.tsv",
    separator='\t'
)

pl.Config.set_tbl_rows(12)
display(GSE130892_combined_merip_seq)

shape: (12, 84)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_na ┆ protocol ┆ organism  ┆ read_type ┆ … ┆ accession ┆ secondary ┆ first_pub ┆ study_ali │
│ me        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ str       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆          ┆           ┆           ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│           ┆          ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ heatshock ┆ cDNA     ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902956 ┆ SRS473644 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_in ┆          ┆ sapiens   ┆           ┆   ┆ 2         ┆ 9         ┆ 0         ┆           │
│ put_1     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ heatshock ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902956 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_ip ┆          ┆ sapiens   ┆           ┆   ┆ 3         ┆ 2         ┆ 0         ┆           │
│ _1        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ heatshock ┆ cDNA     ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902956 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_in ┆          ┆ sapiens   ┆           ┆   ┆ 4         ┆ 0         ┆ 0         ┆           │
│ put_2     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ heatshock ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902956 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_ip ┆          ┆ sapiens   ┆           ┆   ┆ 5         ┆ 3         ┆ 0         ┆           │
│ _2        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ heatshock ┆ cDNA     ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902956 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_in ┆          ┆ sapiens   ┆           ┆   ┆ 6         ┆ 1         ┆ 0         ┆           │
│ put_3     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ heatshock ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902956 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_ip ┆          ┆ sapiens   ┆           ┆   ┆ 7         ┆ 5         ┆ 0         ┆           │
│ _3        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ untreated ┆ cDNA     ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902956 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_in ┆          ┆ sapiens   ┆           ┆   ┆ 8         ┆ 4         ┆ 0         ┆           │
│ put_1     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ untreated ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902956 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_ip ┆          ┆ sapiens   ┆           ┆   ┆ 9         ┆ 6         ┆ 0         ┆           │
│ _1        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ untreated ┆ cDNA     ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902957 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_in ┆          ┆ sapiens   ┆           ┆   ┆ 0         ┆ 7         ┆ 0         ┆           │
│ put_2     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ untreated ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902957 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_ip ┆          ┆ sapiens   ┆           ┆   ┆ 1         ┆ 8         ┆ 0         ┆           │
│ _2        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ untreated ┆ cDNA     ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902957 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_in ┆          ┆ sapiens   ┆           ┆   ┆ 2         ┆ 9         ┆ 0         ┆           │
│ put_3     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ untreated ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ SRR902957 ┆ SRS473646 ┆ 2019-05-1 ┆ GSE130892 │
│ _total_ip ┆          ┆ sapiens   ┆           ┆   ┆ 3         ┆ 0         ┆ 0         ┆           │
│ _3        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
# MeRIP-seq
# note: IP vs input (RNA-seq data as background)
defined_pairs_gse130892_merip_seq = [
    ("SRR9029563", "SRR9029562"), # heatshock_total_IP_1 vs heatshock_total_input_1
    ("SRR9029565", "SRR9029564"), # heatshock_total_IP_2 vs heatshock_total_input_2
    ("SRR9029567", "SRR9029566"), # heatshock_total_IP_3 vs heatshock_total_input_3
    ("SRR9029569", "SRR9029568"), # untreated_total_IP_1 vs untreated_total_input_1
    ("SRR9029571", "SRR9029570"), # untreated_total_IP_2 vs untreated_total_input_2
    ("SRR9029573", "SRR9029572")  # untreated_total_IP_3 vs untreated_total_input_3
]

paired_metadata_df_gse130892_merip_seq = create_paired_metadata(
    combined_df=GSE130892_combined_merip_seq,
    defined_sample_pairs=defined_pairs_gse130892_merip_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse130892_merip_seq is not None:
    paired_metadata_df_gse130892_merip_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE130892_merip_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse130892_merip_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 85)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol  ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_al │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---       ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ ias      │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR902956 ┆ SRR902956 ┆ heatshock ┆ other vs  ┆ … ┆ PRJNA5419 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE13089 │
│ 3         ┆ 2         ┆ _total_ip ┆ cDNA      ┆   ┆ 15        ┆ 2 vs SRS4 ┆ 0         ┆ 2        │
│           ┆           ┆ _1 vs hea ┆           ┆   ┆           ┆ 736449    ┆           ┆          │
│           ┆           ┆ tshock_to ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ tal_input ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _1        ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR902956 ┆ SRR902956 ┆ heatshock ┆ other vs  ┆ … ┆ PRJNA5419 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE13089 │
│ 5         ┆ 4         ┆ _total_ip ┆ cDNA      ┆   ┆ 15        ┆ 3 vs SRS4 ┆ 0         ┆ 2        │
│           ┆           ┆ _2 vs hea ┆           ┆   ┆           ┆ 736450    ┆           ┆          │
│           ┆           ┆ tshock_to ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ tal_input ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _2        ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR902956 ┆ SRR902956 ┆ heatshock ┆ other vs  ┆ … ┆ PRJNA5419 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE13089 │
│ 7         ┆ 6         ┆ _total_ip ┆ cDNA      ┆   ┆ 15        ┆ 5 vs SRS4 ┆ 0         ┆ 2        │
│           ┆           ┆ _3 vs hea ┆           ┆   ┆           ┆ 736451    ┆           ┆          │
│           ┆           ┆ tshock_to ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ tal_input ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _3        ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR902956 ┆ SRR902956 ┆ untreated ┆ other vs  ┆ … ┆ PRJNA5419 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE13089 │
│ 9         ┆ 8         ┆ _total_ip ┆ cDNA      ┆   ┆ 15        ┆ 6 vs SRS4 ┆ 0         ┆ 2        │
│           ┆           ┆ _1 vs unt ┆           ┆   ┆           ┆ 736454    ┆           ┆          │
│           ┆           ┆ reated_to ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ tal_input ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _1        ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR902957 ┆ SRR902957 ┆ untreated ┆ other vs  ┆ … ┆ PRJNA5419 ┆ SRS473645 ┆ 2019-05-1 ┆ GSE13089 │
│ 1         ┆ 0         ┆ _total_ip ┆ cDNA      ┆   ┆ 15        ┆ 8 vs SRS4 ┆ 0         ┆ 2        │
│           ┆           ┆ _2 vs unt ┆           ┆   ┆           ┆ 736457    ┆           ┆          │
│           ┆           ┆ reated_to ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ tal_input ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _2        ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR902957 ┆ SRR902957 ┆ untreated ┆ other vs  ┆ … ┆ PRJNA5419 ┆ SRS473646 ┆ 2019-05-1 ┆ GSE13089 │
│ 3         ┆ 2         ┆ _total_ip ┆ cDNA      ┆   ┆ 15        ┆ 0 vs SRS4 ┆ 0         ┆ 2        │
│           ┆           ┆ _3 vs unt ┆           ┆   ┆           ┆ 736459    ┆           ┆          │
│           ┆           ┆ reated_to ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ tal_input ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _3        ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# 2. GSE164200 (SINGLE) m6A-RIP-seq

- ✅ DOWNLOAD (yone-ssd)
- ✅ TRIMMING (yone-ssd)
- ✅ MAPPING (yone-ssd)
- ✅ PEAK CALL AND ANALYSIS (M3 MacBook Pro; using exomePeak2)

&nbsp;

- validate date: 2026-02-22

&nbsp;

- [m6 A modification of HSATIII lncRNAs regulates temperature-dependent splicing](https://doi.org/10.15252/embj.2021107976)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)から再度こちらに処理を移動

In [8]:
GSE164200_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE164200/GSE164200_PEP/GSE164200_PEP_raw.csv",
    separator=','
)

pl.Config.set_tbl_rows(20)
display(GSE164200_PEP)

shape: (20, 47)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_na ┆ protocol ┆ organism  ┆ read_type ┆ … ┆ genome_bu ┆ supplemen ┆ biosample ┆ sra       │
│ me        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ild       ┆ tary_file ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ ---       ┆ s_format_ ┆ str       ┆ str       │
│ str       ┆          ┆           ┆           ┆   ┆ str       ┆ and_conte ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ nt        ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ ---       ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ a1_37-inp ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ut_rep1   ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208964    ┆ 087       │
│ a1_37-ip- ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ rep1      ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208963    ┆ 088       │
│ a2_37-inp ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ut_rep2   ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208962    ┆ 089       │
│ a2_37-ip- ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ rep2      ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208961    ┆ 090       │
│ b1_hs-con ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ trol-inpu ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ t_rep1    ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208960    ┆ 091       │
│ b1_hs-con ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ trol-ip-r ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ep1       ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208959    ┆ 092       │
│ b2_hs-con ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ trol-inpu ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ t_rep2    ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208958    ┆ 093       │
│ b2_hs-con ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ trol-ip-r ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ep2       ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208957    ┆ 094       │
│ c1_hs-hsa ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ tiiikd-in ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ put_rep1  ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208956    ┆ 095       │
│ c1_hs-hsa ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ tiiikd-re ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ p1        ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208955    ┆ 096       │
│ c2_hs-hsa ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ tiiikd-in ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ put_rep2  ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208986    ┆ 097       │
│ c2_hs-hsa ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ tiiikd-ip ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ -rep2     ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208985    ┆ 098       │
│ d1_recove ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ry-contro ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ l-input_r ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│ ep1       ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208984    ┆ 099       │
│ d1_recove ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ry-contro ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ l-ip-rep1 ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208983    ┆ 100       │
│ d2_recove ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ry-contro ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ l-input_r ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│ ep2       ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208981    ┆ 101       │
│ d2_recove ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ry-contro ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ l-ip-rep2 ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208980    ┆ 102       │
│ e1_recove ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ry-hsatii ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ikd-input ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│ _rep1     ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208978    ┆ 103       │
│ e1_recove ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ry-hsatii ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ikd-rep1  ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208977    ┆ 104       │
│ e2_recove ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ry-hsatii ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ikd-input ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│ _rep2     ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208975    ┆ 105       │
│ e2_recove ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ human     ┆ An exel   ┆ https://w ┆ https://w │
│ ry-hsatii ┆          ┆ sapiens   ┆           ┆   ┆ hg19      ┆ file      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ikd-ip-re ┆          ┆           ┆           ┆   ┆           ┆ including ┆ lm.nih.go ┆ lm.nih.go │
│ p2        ┆          ┆           ┆           ┆   ┆           ┆ m6A peaks ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ for each  ┆ le/SAMN17 ┆ m=SRX9774 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample    ┆ 208974    ┆ 106       │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘